<?php
declare(strict_types=1);

function r2_landing_fields():array {return ['hero_title'=>'Título principal','hero_text'=>'Texto principal','about_title'=>'Título de presentación','about_text'=>'Presentación del negocio','services_title'=>'Título de productos y servicios','service_1_title'=>'Tarjeta 1 · título','service_1_text'=>'Tarjeta 1 · texto','service_2_title'=>'Tarjeta 2 · título','service_2_text'=>'Tarjeta 2 · texto','service_3_title'=>'Tarjeta 3 · título','service_3_text'=>'Tarjeta 3 · texto','contact_title'=>'Título de contacto','contact_text'=>'Texto de contacto'];}
function r2_design(App $app,array $u,?array $t):void {
    $tid=(int)($t['id']??0);$section=$t?'contenido':'contenido';
    if(is_post()){verify_csrf();try{
        foreach(r2_landing_fields() as $key=>$label)r2_set($app,$tid,$key,mb_substr(trim((string)($_POST[$key]??'')),0,3000));
        foreach(['hero_image','about_image','service_1_image','service_2_image','service_3_image'] as $key){if(isset($_POST['clear_'.$key]))r2_set($app,$tid,$key,'');elseif($image=upload_image($key))r2_set($app,$tid,$key,$image);}
        flash('success','Diseño guardado.');
    }catch(Throwable $ex){flash('error',$ex->getMessage());}redirect(url(($t?'admin':'master').'/contenido'));}
    admin_shell_start($t?'Diseño y página del negocio':'Web oficial de FISITAAP',$u,$t,'contenido');echo '<p><a class="btn btn-light" target="_blank" href="'.url($t['slug']??'').'">Ver página</a> <a class="btn btn-light" href="'.url(($t?'admin':'master').'/contenido-anterior').'">Banners, blog y contenido anterior</a></p><section class="card admin-card"><form method="post" enctype="multipart/form-data">'.csrf_field();
    foreach(r2_landing_fields() as $key=>$label){echo '<label>'.e($label).'<textarea class="input" name="'.e($key).'" maxlength="3000" rows="2">'.e(r2_setting($app,$tid,$key)).'</textarea></label>';}
    foreach(['hero_image'=>'Imagen principal','about_image'=>'Imagen de presentación','service_1_image'=>'Tarjeta 1','service_2_image'=>'Tarjeta 2','service_3_image'=>'Tarjeta 3'] as $key=>$label){$image=r2_setting($app,$tid,$key);echo '<label>'.e($label).($image?'<img class="r2-editor-image" src="'.e(public_media_url($image)).'" alt="">':'').'<input class="input" type="file" name="'.e($key).'" accept="image/jpeg,image/png,image/webp"></label><label><input type="checkbox" name="clear_'.e($key).'"> Quitar imagen</label>';}
    echo '<button class="btn">Guardar diseño</button></form></section>';admin_shell_end();
}
function r2_landing(App $app,?array $t):void {
    $tid=(int)($t['id']??0);$name=$t['name']??$app->setting('site_name','FISITAAP');$official=!$t;
    $content=$t?$app->all('SELECT * FROM tenant_content WHERE tenant_id=? AND is_active=1 ORDER BY sort_order,id',[$tid]):[];
    $hero=null;$about=null;foreach($content as $c){if($c['section_key']==='home_slider'&&!$hero)$hero=$c;if($c['section_key']==='home_block'&&!$about)$about=$c;}
    $defaults=['hero_title'=>$hero['title']??($official?$app->setting('home_slide_1_title','Tu negocio, más cerca de tus clientes.'):'Lo que necesitas, más cerca de ti.'),'hero_text'=>$hero['body']??($official?$app->setting('home_slide_1_text','Catálogo, ventas y administración desde un solo lugar.'):'Productos y atención cercana para tu día a día.'),'hero_image'=>$hero['image']??($official?$app->setting('home_slide_1_image'):''),'about_title'=>$about['title']??'Un negocio cercano. Una atención que se nota.','about_text'=>$about['body']??($t['address']??$app->setting('footer_text','Conoce nuestras herramientas y los negocios afiliados.')),'about_image'=>$about['image']??'','services_title'=>$official?'Herramientas para tu negocio':'Productos y servicios','contact_title'=>'Conversemos. Será un gusto atenderte.','contact_text'=>$t['business_hours']??$app->setting('contact_text'),'service_1_title'=>'Nuestros productos','service_1_text'=>'Conoce nuestro catálogo.','service_2_title'=>'Atención personalizada','service_2_text'=>'Consulta y encuentra lo que necesitas.','service_3_title'=>'Pedidos y entregas','service_3_text'=>'Revisa las opciones del negocio.'];
    $value=fn(string $key)=>r2_setting($app,$tid,$key,(string)($defaults[$key]??''));
    $catalog=$t?url($t['slug'].'/'.catalog_segment($t)):url('demo');$phone=preg_replace('/\D/','',(string)($t['whatsapp']??$app->setting('master_whatsapp')));$wa=$phone!==''?'https://wa.me/'.$phone:$catalog;$heroImage=$value('hero_image');
    $brand=!empty($t['logo'])?'<img src="'.e(public_media_url($t['logo'])).'" alt="'.e($name).'">':e($name);layout_start($name,$t);echo '<div class="r2-landing"><header class="r2-public-nav"><a class="r2-wordmark" href="'.url($t['slug']??'').'">'.$brand.'</a><nav><a href="#inicio">Inicio</a><a href="#nosotros">Nosotros</a><a href="#servicios">'.($official?'Herramientas':'Productos').'</a><a href="#contacto">Contacto</a><a class="btn" href="'.e($catalog).'">'.($official?'Ver demostración':'Ver catálogo').'</a></nav></header><main><section id="inicio" class="r2-hero">'.($heroImage?'<img src="'.e(public_media_url($heroImage)).'" alt="">':'').'<div><h1>'.e($value('hero_title')).'</h1><p>'.nl2br(e($value('hero_text'))).'</p><a class="btn" href="'.e($catalog).'">'.($official?'Conocer FISITAAP':'Ver catálogo o menú').'</a><a class="r2-outline" href="#nosotros">Conoce nuestro negocio</a></div></section><section id="nosotros" class="r2-about">'.($value('about_image')?'<img src="'.e(public_media_url($value('about_image'))).'" alt="">':'<div class="r2-about-placeholder">'.e($name).'</div>').'<div><small>NOSOTROS</small><h2>'.e($value('about_title')).'</h2><p>'.nl2br(e($value('about_text'))).'</p><div class="r2-promises"><span>Atención personal</span><span>Variedad</span><span>Compromiso</span></div><a class="btn btn-light" href="'.e($catalog).'">Explorar catálogo</a></div></section><section id="servicios" class="r2-services"><h2>'.e($value('services_title')).'</h2><div class="r2-service-grid">';
    for($i=1;$i<=3;$i++){echo '<article>'.($value('service_'.$i.'_image')?'<img src="'.e(public_media_url($value('service_'.$i.'_image'))).'" alt="">':'').'<div><h3>'.e($value('service_'.$i.'_title')).'</h3><p>'.e($value('service_'.$i.'_text')).'</p><a href="'.e($i===2?$wa:$catalog).'">'.($i===2?'Consultar':'Ver productos').' →</a></div></article>';}echo '</div><p class="r3-business-catalog"><a class="btn" href="'.e($catalog).'">Ver catálogo completo →</a></p></section>';
    if($official){echo '<section class="r2-directory" id="negocios"><h2>'.e($app->setting('directory_title','Negocios afiliados')).'</h2><div class="r2-service-grid">';foreach($app->all('SELECT name,slug,logo,catalog_label FROM tenants WHERE is_active=1 AND is_listed=1 AND slug NOT IN ("tienda-demo","restaurante-demo") ORDER BY name LIMIT 100') as $shop)echo '<a class="card admin-card" href="'.url($shop['slug']).'">'.($shop['logo']?'<img class="r2-shop-logo" src="'.e(public_media_url($shop['logo'])).'" alt="">':'').'<h3>'.e($shop['name']).'</h3><span>'.e($shop['catalog_label']).' →</span></a>';echo '</div></section>';}
    echo '<section id="contacto" class="r2-contact"><div><small>CONTACTO</small><h2>'.e($value('contact_title')).'</h2><p>'.nl2br(e($value('contact_text'))).'</p>'.($t?'<p>⌖ '.e($t['address']).'</p><p>☎ '.e($t['phone']).'</p><p>◷ '.nl2br(e($t['business_hours']??'')).'</p>':'').'<a class="btn" href="'.e($wa).'">Escríbenos por WhatsApp</a></div><div>'.($t?safe_map_embed((string)$t['map_embed']):'<h3>Comienza con FISITAAP</h3><p>Prueba el catálogo y la administración.</p><a class="btn btn-light" href="'.url('owner-login').'">Acceso de negocios</a>').'</div></section></main><footer><strong>'.e($name).'</strong><span>Catálogo / Menú</span>';foreach(['facebook_url'=>'Facebook','instagram_url'=>'Instagram','tiktok_url'=>'TikTok'] as $key=>$label){$link=$t[$key]??$app->setting($key);if(preg_match('~^https?://~i',(string)$link))echo '<a href="'.e($link).'" rel="noopener">'.$label.'</a>';}if(!$official)echo '<a href="'.url().'" class="r2-platform-offer"><img src="'.e($app->setting('platform_logo',url('assets/fisitapp-logo.webp'))).'" alt="FISITAAP" style="width:110px;max-height:40px;object-fit:contain"><span>¿Quieres vender con FISITAAP?</span></a>';echo '</footer></div>';r2_chat_widget($app,$t);layout_end();
}

function r2_new_customer(App $app,array $t,string $name,string $phone,?array $creator=null,string $source='web'):array {
    $name=trim($name);$phone=preg_replace('/\D/','',$phone);if($name===''||mb_strlen($name)>150||!preg_match('/^(506)?[0-9]{8}$/',$phone))throw new DomainException('Escribe tu nombre y un teléfono de Costa Rica de 8 dígitos.');
    $email='cliente-'.bin2hex(random_bytes(16)).'@registro.fisitaap.local';
    $app->exec('INSERT INTO users(name,email,phone,password_hash,role,is_active) VALUES(?,?,?,?,"customer",1)',[$name,$email,$phone,password_hash(bin2hex(random_bytes(32)),PASSWORD_BCRYPT)]);$id=(int)$app->db->lastInsertId();
    $app->exec('INSERT INTO tenant_customers(tenant_id,user_id) VALUES(?,?)',[$t['id'],$id]);$app->exec('INSERT INTO fisitaap_r2_customer_sources(tenant_id,user_id,source,created_by) VALUES(?,?,?,?)',[$t['id'],$id,$source,$creator['id']??null]);
    return (array)$app->one('SELECT id,name,email,phone,role,tenant_id,is_active,force_password_change FROM users WHERE id=?',[$id]);
}
function r2_customer_checkout(App $app,array $t,array $raw):?array {
    if(current_user()||!r2_active($app)||is_demo_tenant_v12($t))return current_user();
    if(!rate_limit_persistent($app,'quick_register',client_identity(),8,300))json_response(['ok'=>false,'error'=>'Espera unos minutos antes de crear otra cuenta.'],429);
    try{$u=r2_new_customer($app,$t,(string)($raw['guest_name']??''),(string)($raw['guest_phone']??''));session_regenerate_id(true);$_SESSION['user']=$u;$_SESSION['active_tenant_slug']=$t['slug'];return $u;}catch(DomainException $ex){json_response(['ok'=>false,'error'=>$ex->getMessage()],422);}
}
function r2_customers(App $app,array $u,array $t,string $section):void {
    if(is_post()){verify_csrf();try{
        $cid=(int)($_POST['customer_id']??0);
        if(($_POST['action']??'')==='credit'){
            if(!in_array($u['role'],['tenant_admin','manager'],true)||restructure_can_r1($app,$u,$section,'credit')===false)throw new DomainException('Crédito no autorizado.');
            if(!$app->one('SELECT user_id FROM tenant_customers WHERE tenant_id=? AND user_id=?',[$t['id'],$cid]))throw new DomainException('Cliente no disponible.');
            $limit=r2_number($_POST['credit_limit']??0);$days=(int)r2_number($_POST['payment_terms_days']??30,1,3650);
            $app->exec('INSERT INTO customer_credit_profiles(tenant_id,user_id,credit_enabled,credit_limit,payment_terms_days) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE credit_enabled=VALUES(credit_enabled),credit_limit=VALUES(credit_limit),payment_terms_days=VALUES(payment_terms_days)',[$t['id'],$cid,isset($_POST['credit_enabled'])?1:0,$limit,$days]);
        }else{r2_new_customer($app,$t,(string)($_POST['name']??''),(string)($_POST['phone']??''),$u,'panel');}
        flash('success','Cliente actualizado.');
    }catch(Throwable $ex){flash('error',$ex->getMessage());}r2_redirect($section);}
    admin_shell_start(['clientes-crear'=>'Crear cliente','clientes-buscar'=>'Buscar clientes','clientes-historial'=>'Historial de clientes','credito'=>'Crédito','clientes'=>'Clientes'][$section]??'Clientes',$u,$t,$section);
    if($section==='clientes-crear'){echo '<section class="card admin-card" style="max-width:700px">'.r2_form('create').field('Nombre','name','',true).field('Teléfono','phone','',true).'<button class="btn">Crear cliente</button></form></section>';admin_shell_end();return;}
    $q=mb_substr(trim((string)($_GET['q']??'')),0,100);echo '<section class="card admin-card"><form method="get">'.field('Nombre o teléfono','q',$q).'<button class="btn btn-light">Buscar</button></form><div class="table-wrap"><table class="table"><tr><th>Cliente</th><th>Compras</th><th>Origen</th><th>Crédito</th><th>Detalle</th></tr>';
    $rows=$app->all('SELECT u.id,u.name,u.phone,u.created_at,cs.source,COALESCE(cp.credit_enabled,0) credit_enabled,COALESCE(cp.credit_limit,0) credit_limit,COALESCE(cp.current_balance,0) current_balance,COALESCE(cp.payment_terms_days,30) payment_terms_days,(SELECT COUNT(*) FROM orders o WHERE o.tenant_id=tc.tenant_id AND o.user_id=u.id AND o.status!="cancelled") online_count,(SELECT COALESCE(SUM(total),0) FROM orders o WHERE o.tenant_id=tc.tenant_id AND o.user_id=u.id AND o.status!="cancelled") online_total,(SELECT COUNT(*) FROM sales s WHERE s.tenant_id=tc.tenant_id AND s.customer_id=u.id AND s.status="completed") pos_count,(SELECT COALESCE(SUM(total),0) FROM sales s WHERE s.tenant_id=tc.tenant_id AND s.customer_id=u.id AND s.status="completed") pos_total FROM tenant_customers tc JOIN users u ON u.id=tc.user_id LEFT JOIN fisitaap_r2_customer_sources cs ON cs.tenant_id=tc.tenant_id AND cs.user_id=u.id LEFT JOIN customer_credit_profiles cp ON cp.tenant_id=tc.tenant_id AND cp.user_id=u.id WHERE tc.tenant_id=? AND (u.name LIKE ? OR u.phone LIKE ?) ORDER BY u.name LIMIT 300',[$t['id'],'%'.$q.'%','%'.$q.'%']);
    foreach($rows as $r){echo '<tr><td>'.e($r['name']).'<br>'.e($r['phone']).'</td><td>'.((int)$r['online_count']+(int)$r['pos_count']).' · '.money((float)$r['online_total']+(float)$r['pos_total']).'</td><td>'.e(['web'=>'Web','panel'=>'Panel','caja'=>'Caja'][$r['source']??'']??'Registro anterior').'<br>'.e($r['created_at']).'</td><td>';if($section==='credito')echo r2_form('credit').pos_hidden_148('customer_id',$r['id']).'<label><input type="checkbox" name="credit_enabled" '.($r['credit_enabled']?'checked':'').'> Autorizar</label>'.field('Límite','credit_limit',$r['credit_limit'],true,'number','.01').field('Plazo (días)','payment_terms_days',$r['payment_terms_days'],true,'number','1').'<button class="btn btn-light">Guardar</button></form>';else echo ($r['credit_enabled']?'Disponible '.money(max(0,(float)$r['credit_limit']-(float)$r['current_balance'])):'Sin crédito').'<br>Saldo '.money((float)$r['current_balance']);echo '</td><td><a class="btn btn-light" href="?customer='.(int)$r['id'].'">Historial</a></td></tr>';}
    echo '</table></div></section>';$cid=(int)($_GET['customer']??0);if($cid&&$app->one('SELECT user_id FROM tenant_customers WHERE tenant_id=? AND user_id=?',[$t['id'],$cid])){
        echo '<section class="card admin-card" style="margin-top:20px"><h2>Compras del cliente</h2><table class="table"><tr><th>Fecha</th><th>Documento</th><th>Canal</th><th>Total</th><th>Estado</th></tr>';foreach($app->all('SELECT created_at,order_number number,"Web" channel,total,status FROM orders WHERE tenant_id=? AND user_id=? UNION ALL SELECT created_at,sale_number,"Caja",total,status FROM sales WHERE tenant_id=? AND customer_id=? ORDER BY created_at DESC LIMIT 300',[$t['id'],$cid,$t['id'],$cid]) as $r)echo '<tr><td>'.e($r['created_at']).'</td><td>'.e($r['number']).'</td><td>'.e($r['channel']).'</td><td>'.money((float)$r['total']).'</td><td>'.e(ui_label_qa($r['status'])).'</td></tr>';echo '</table><h3>Fidelización</h3>';foreach($app->all('SELECT l.* FROM loyalty_ledger l JOIN loyalty_accounts a ON a.id=l.account_id WHERE a.tenant_id=? AND a.user_id=? ORDER BY l.id DESC LIMIT 100',[$t['id'],$cid]) as $r)echo '<p>'.e($r['created_at'].' · '.$r['event']).' · '.e($r['points_delta']??$r['points']??'').'</p>';echo '</section>';}
    admin_shell_end();
}

function r2_kpis(App $app,array $u,array $t):void {
    [$from,$to]=valid_report_dates_v1();$rows=$app->all('SELECT DATE(created_at) day,SUM(total) total,COUNT(*) count FROM (SELECT created_at,total FROM orders WHERE tenant_id=? AND status!="cancelled" AND DATE(created_at) BETWEEN ? AND ? UNION ALL SELECT created_at,total FROM sales WHERE tenant_id=? AND status="completed" AND DATE(created_at) BETWEEN ? AND ?) x GROUP BY DATE(created_at) ORDER BY day',[$t['id'],$from,$to,$t['id'],$from,$to]);$sum=array_sum(array_column($rows,'total'));$count=array_sum(array_column($rows,'count'));$max=max([1,...array_column($rows,'total')]);
    admin_shell_start('KPIs',$u,$t,'kpis');echo '<section class="card admin-card"><form method="get"><div class="split">'.field('Desde','from',$from,true,'date').field('Hasta','to',$to,true,'date').'</div><button class="btn btn-light">Actualizar</button></form></section><div class="grid grid-3" style="margin:20px 0">';foreach(['Ventas'=>money((float)$sum),'Operaciones'=>(string)$count,'Ticket promedio'=>money($count?$sum/$count:0)] as $label=>$v)echo '<article class="card stat"><small>'.e($label).'</small><h2>'.e($v).'</h2></article>';echo '</div><section class="card admin-card"><h2>Ventas por día</h2><div class="r2-chart" role="img" aria-label="Ventas diarias del periodo">';foreach($rows as $row)echo '<div class="r2-bar"><span>'.money((float)$row['total']).'</span><i style="height:'.max(1,(int)round((float)$row['total']/$max*180)).'px"></i><small>'.e($row['day']).'</small></div>';if(!$rows)echo '<p>No hay ventas en este periodo.</p>';echo '</div></section><section class="card admin-card" style="margin-top:20px"><h2>Productos más vendidos</h2><table class="table"><tr><th>Producto</th><th>Cantidad</th><th>Neto</th></tr>';
    foreach($app->all('SELECT name,SUM(quantity) quantity,SUM(amount) amount FROM (SELECT i.product_name name,i.quantity,i.line_subtotal amount FROM order_items i JOIN orders o ON o.id=i.order_id WHERE o.tenant_id=? AND o.status!="cancelled" AND DATE(o.created_at) BETWEEN ? AND ? UNION ALL SELECT i.product_name,i.quantity,i.line_subtotal FROM sale_items i JOIN sales s ON s.id=i.sale_id WHERE s.tenant_id=? AND s.status="completed" AND DATE(s.created_at) BETWEEN ? AND ?) x GROUP BY name ORDER BY amount DESC LIMIT 20',[$t['id'],$from,$to,$t['id'],$from,$to]) as $row)echo '<tr><td>'.e($row['name']).'</td><td>'.e($row['quantity']).'</td><td>'.money((float)$row['amount']).'</td></tr>';echo '</table></section>';admin_shell_end();
}

function r2_customer_access(App $app):void {
    $u=require_login(['customer']);$u=$app->one('SELECT * FROM users WHERE id=? AND role="customer" AND is_active=1',[$u['id']]);if(!$u){http_response_code(403);exit;}$temporary=str_ends_with($u['email'],'@registro.fisitaap.local');
    if(is_post()){verify_csrf();try{
        $email=strtolower(trim((string)($_POST['email']??'')));$password=(string)($_POST['password']??'');if(!$temporary)throw new DomainException('Tu cuenta ya tiene un acceso guardado. Usa Cambiar contraseña para modificarlo.');
        if(!filter_var($email,FILTER_VALIDATE_EMAIL)||str_ends_with($email,'.local')||strlen($password)<12||strlen($password)>72||$password!==(string)($_POST['confirm']??''))throw new DomainException('Escribe un correo válido y dos contraseñas iguales de 12 a 72 caracteres.');
        if($app->one('SELECT id FROM users WHERE email=? AND id<>?',[$email,$u['id']]))throw new DomainException('Este correo ya tiene una cuenta. Usa otro correo para guardar este acceso.');
        $app->exec('UPDATE users SET email=?,password_hash=?,email_verified_at=NULL WHERE id=? AND email=?',[$email,password_hash($password,PASSWORD_BCRYPT),$u['id'],$u['email']]);session_regenerate_id(true);$_SESSION['user']['email']=$email;flash('success','Acceso guardado. La próxima vez ingresa con este correo y contraseña.');redirect(url('account'));
    }catch(DomainException $ex){flash('error',$ex->getMessage());}}
    layout_start('Guardar mi acceso');public_header();echo '<main class="auth-page"><section class="card auth-card"><h1>Guardar mi acceso</h1><p>Conserva tus pedidos y beneficios para ingresar desde otro dispositivo.</p>';render_flashes();if($temporary)echo '<form method="post">'.csrf_field().field('Correo','email','',true,'email').field('Contraseña','password','',true,'password').field('Repetir contraseña','confirm','',true,'password').'<button class="btn btn-block">Guardar acceso</button></form>';else echo '<p>Tu cuenta ya usa un correo para ingresar.</p><a class="btn" href="'.url('change-password').'">Cambiar contraseña</a>';echo '<p><a href="'.url('account').'">Volver a mis pedidos</a></p></section></main>';public_footer();layout_end();
}
