<?php
declare(strict_types=1);

function r3_sales(App $app,array $u,array $t): void
{
    $branch=pos_access_148($app,$u,$t);$menu=($t['catalog_label']??'')==='Menú';$screen=(string)($_GET['screen']??'');$id=(int)($_GET['ticket']??0);
    if(!empty($_GET['history'])){r2_sales_history($app,$u,$t);return;}
    if($id&&$screen==='checkout'){r3_collect($app,$u,$t,[$id]);return;}
    if($id&&$screen==='order'){r3_workspace($app,$u,$t,$branch,$id);return;}
    if(is_post()) {
        verify_csrf();try {
            $action=(string)($_POST['action']??'');
            if(in_array($action,['quick','catalog','table','express'],true)) {
                if(!$menu&&!in_array($action,['catalog','quick'],true))throw new DomainException('Esta opción requiere un negocio tipo Menú.');
                $id=pos_open_148($app,$t,$u,$branch,$menu?$action:'catalog',$action==='table'?(int)($_POST['table_id']??0):null);
                redirect(url('admin/ventas?screen=order&ticket='.$id));
            }
            if(in_array($action,['save_table','save_group'],true))pos_table_config_148($app,$t,$u,$branch);
            else throw new DomainException('Acción no disponible.');
        }catch(Throwable $ex){flash('error',$ex->getMessage());}
        redirect(url('admin/ventas'.($screen==='express'?'?screen=express':'')));
    }
    if($menu&&$screen===''&&empty($_GET['waiting'])){r3_floor($app,$u,$t);return;}
    r3_shell_start($app,$u,$t,$branch,$screen==='express'?'Pedido Express':'Venta rápida');r3_pos_nav($t);
    if($menu&&$screen==='express') {
        echo '<section class="r3-panel r3-express"><h2>Iniciar pedido Express</h2><form method="post">'.csrf_field().pos_hidden_148('action','express').pos_hidden_148('open_key',bin2hex(random_bytes(16)));pos_customers_ui_148($app,$t);echo '<label>Dirección y señas de entrega<textarea class="r3-input" name="delivery_address" maxlength="1000" required></textarea></label><button class="r3-button primary">Guardar cliente y comenzar pedido</button></form></section>';
    }
    echo '<section class="r3-panel"><h2>Cuentas y ventas en espera</h2><div class="r3-waiting">';
    foreach($app->all('SELECT t.*,r.name table_name,u.name customer_name FROM pos_tickets t LEFT JOIN restaurant_tables r ON r.id=t.table_id LEFT JOIN users u ON u.id=t.customer_id WHERE t.tenant_id=? AND t.branch_id=? AND t.status NOT IN ("paid","void") ORDER BY t.updated_at DESC LIMIT 100',[$t['id'],$branch['id']]) as $ticket) {
        echo '<a class="r3-waiting-card" href="'.url('admin/ventas?screen=order&ticket='.(int)$ticket['id']).'"><strong>'.e($ticket['table_name']?:$ticket['display_label']?:$ticket['ticket_number']).'</strong><span>'.e($ticket['customer_name']?:'Consumidor final').'</span><small>'.e(ui_label_qa($ticket['status'])).'</small><b>'.money(max(0,(float)$ticket['total']-(float)$ticket['paid_total'])).'</b></a>';
    }echo '</div></section>';
    if(!$menu&&$screen==='')echo '<p class="r3-empty">Pulsa <strong>Venta rápida</strong> para comenzar una venta.</p>';
    r3_shell_end();
}
function r3_workspace(App $app,array $u,array $t,array $branch,int $id): void
{
    $ticket=pos_ticket_get_148($app,$t,$branch,$id);
    if(is_post()) {
        if(in_array($_POST['action']??'',['move_table','join_tables'],true))r2_ticket_move($app,$u,$t,$branch,$id);
        pos_edit_148($app,$t,$u,$branch,$id);
    }
    if(in_array($ticket['status'],['paid','void'],true)) {
        r3_shell_start($app,$u,$t,$branch,'Cuenta cerrada');echo '<p>Esta cuenta ya está cerrada.</p><a class="r3-button primary" href="'.url('admin/ventas').'">Volver a ventas</a>';r3_shell_end();return;
    }
    $items=pos_items_v141($app,$id);$menu=($t['catalog_label']??'')==='Menú';
    $products=r2_catalog_prices($app,$t,pos_catalog_products_v141($app,$t,$branch));
    $categories=$app->all('SELECT id,name FROM categories WHERE tenant_id=? AND is_active=1 ORDER BY sort_order,name',[$t['id']]);
    $customers=$app->all('SELECT u.id,u.name,u.phone FROM tenant_customers c JOIN users u ON u.id=c.user_id WHERE c.tenant_id=? AND u.is_active=1 AND u.role="customer" ORDER BY u.name',[$t['id']]);
    $customerName='Consumidor final';foreach($customers as $c)if((int)$c['id']===(int)$ticket['customer_id'])$customerName=$c['name'];
    $url=url('admin/ventas?screen=order&ticket='.$id);$meta=csrf_field().pos_hidden_148('revision',$ticket['revision']);
    $title=$ticket['sale_type']==='table'?'Pedido de mesa':($ticket['sale_type']==='express'?'Pedido Express':'Venta rápida');
    r3_shell_start($app,$u,$t,$branch,$title);pos_assets_148();
    $open=$app->all('SELECT id,ticket_number,status FROM pos_tickets WHERE tenant_id=? AND branch_id=? AND opened_by=? AND table_id IS NULL AND status NOT IN ("paid","void") ORDER BY id DESC LIMIT 8',[$t['id'],$branch['id'],$u['id']]);
    echo '<nav class="r3-sale-tabs">';foreach($open as $a)echo '<a href="'.url('admin/ventas?screen=order&ticket='.(int)$a['id']).'" class="'.((int)$a['id']===$id?'active':'').'">'.e($a['ticket_number']).($a['status']==='suspended'?' · En espera':'').'</a>';
    echo '<form method="post" action="'.url('admin/ventas').'">'.csrf_field().pos_hidden_148('action',$menu?'quick':'catalog').pos_hidden_148('open_key',bin2hex(random_bytes(16))).'<button>'.r3_icon('plus').'Nueva venta</button></form><span class="r3-spacer"></span><a class="r3-button" href="'.url('admin/ventas?waiting=1').'">En espera</a><a class="r3-button" href="'.url('admin/ventas?history=1').'">'.r3_icon('clock').'Historial / Reimprimir</a></nav>';
    echo '<div class="r3-customer-strip">'.r3_icon('person').'<span>Cliente:</span><strong>'.e($customerName).'</strong><button class="r3-button" type="button" data-dialog-open="r3Customer">Cambiar</button><button class="r3-button" type="button" data-dialog-open="r3Customer" data-new-customer-open>'.r3_icon('plus').'Nuevo cliente</button><span class="r3-spacer"></span><span>Moneda: <b>CRC ₡</b></span></div>';
    echo '<div class="r3-pos-grid"><section class="r3-panel r3-cart-panel"><form class="r3-search" method="get">'.pos_hidden_148('screen','order').pos_hidden_148('ticket',$id).r3_icon('search').'<input name="q" value="'.e($_GET['q']??'').'" placeholder="Escanea un código o busca un producto…" aria-label="Buscar producto" autofocus><button class="r3-button primary">'.r3_icon('plus').'Buscar / agregar</button></form><div class="r3-sale-table-wrap"><table class="r3-sale-table"><thead><tr><th>Código</th><th>Producto / detalle</th><th>Cant.</th><th>Precio</th><th>Desc.</th><th>Importe</th><th>Acciones</th></tr></thead><tbody>';
    foreach($items as $i) {
        $editable=$i['kitchen_status']==='pending'&&(float)$ticket['paid_total']===0.0;
        $p=$app->one('SELECT min_qty,qty_step FROM products WHERE id=?',[$i['product_id']]);
        echo '<tr data-line="'.(int)$i['id'].'"><td>'.e($i['sku']).'</td><td><div class="r3-product-detail"><img src="'.e(public_media_url($i['image'])).'" alt=""><div><strong>'.e($i['product_name']).'</strong>'.order_item_details_html($i).($menu?'<small class="r3-kitchen-state">'.e(['pending'=>'Sin enviar','sent'=>'Enviado a cocina','preparing'=>'Preparando','ready'=>'Listo','served'=>'Servido'][$i['kitchen_status']]??$i['kitchen_status']).'</small>':'').'</div></div></td><td><form method="post" action="'.e($url).'" class="r3-quantity">'.$meta.pos_hidden_148('action','quantity').pos_hidden_148('item_id',$i['id']).'<button type="button" data-quantity-step="-1" '.($editable?'':'disabled').'>−</button><input name="quantity" aria-label="Cantidad de '.e($i['product_name']).'" type="number" min="0" step="'.e($p['qty_step']??'.001').'" value="'.e($i['quantity']).'" '.($editable?'':'disabled').'><button type="button" data-quantity-step="1" '.($editable?'':'disabled').'>+</button><button class="r3-quantity-save" aria-label="Guardar cantidad">'.r3_icon('check').'</button></form></td><td>'.money((float)$i['unit_price']).'</td><td>—</td><td><b>'.money((float)$i['line_subtotal']+(float)$i['line_tax']).'</b></td><td><div class="r3-line-actions"><button type="button" class="r3-button" data-line-edit="'.(int)$i['id'].'" aria-label="Editar '.e($i['product_name']).'" '.($editable?'':'disabled').'>'.r3_icon('edit').'</button><form method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','quantity').pos_hidden_148('item_id',$i['id']).pos_hidden_148('quantity',0).'<button class="r3-button danger" aria-label="Eliminar '.e($i['product_name']).'" '.($editable?'':'disabled').'>'.r3_icon('trash').'</button></form></div></td></tr>';
    }
    if(!$items)echo '<tr><td colspan="7" class="r3-empty">Busca un producto o agrégalo desde el acceso rápido.</td></tr>';
    echo '</tbody></table></div><div class="r3-sale-actions"><button class="r3-button" type="button" data-dialog-open="r3Notes">'.r3_icon('note').'Nota de venta</button><button class="r3-button" type="button" data-dialog-open="r3Discount">'.r3_icon('gift').'Descuento</button>';
    foreach(['suspend'=>'Guardar en espera','void'=>'Cancelar'] as $action=>$label)echo '<form method="post" action="'.e($url).'" '.($action==='void'?'data-confirm="¿Cancelar la venta y devolver los productos al inventario?"':'').'>'.$meta.pos_hidden_148('action',$action).'<button class="r3-button '.($action==='void'?'danger':'').'">'.($action==='suspend'?r3_icon('note'):r3_icon('trash')).$label.'</button></form>';
    if($menu)echo '<form method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','send_kitchen').'<button class="r3-button">'.r3_icon('chef').'Enviar comanda</button></form>';
    echo '</div></section><aside class="r3-quick"><section class="r3-panel"><h3>★ Acceso rápido</h3><div class="r3-categories"><a class="r3-button '.(empty($_GET['category'])?'selected':'').'" href="'.e($url).'">Todos</a>';foreach($categories as $c)echo '<a class="r3-button '.((int)($_GET['category']??0)===(int)$c['id']?'selected':'').'" href="'.e($url.'&category='.(int)$c['id']).'">'.r3_icon('box').e($c['name']).'</a>';echo '</div><div class="r3-quick-products">';
    foreach($products as $p)echo '<form class="pos-product r3-quick-product" data-sku="'.e($p['sku']).'" method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','add_item').pos_hidden_148('product_id',$p['id']).pos_hidden_148('quantity',max(.001,(float)$p['min_qty'])).'<img src="'.e(public_media_url($p['image'])).'" alt=""><div><strong>'.e($p['name']).'</strong><small>'.e($p['sku']).'</small><b>'.money((float)($p['sale_price']?:$p['price'])).'</b></div><button class="r3-button green" aria-label="Agregar '.e($p['name']).'">+</button></form>';
    if(!$products)echo '<p>No hay productos con este filtro.</p>';echo '</div></section><section class="r3-panel r3-options"><h3>'.r3_icon('settings').'Opciones</h3><button class="r3-button" type="button" data-dialog-open="r3Stock">'.r3_icon('box').'Consultar existencia</button><p>Al agregar un producto podrás seleccionar sus variantes, extras y opcionales.</p></section></aside></div>';
    echo '<footer class="r3-sale-total"><div>'.r3_icon('cart').'<span>Productos<b>'.money((float)$ticket['subtotal']+(float)$ticket['tax_total']).'</b></span></div><div>'.r3_icon('gift').'<span>Descuento<b>'.money((float)$ticket['discount_total']).'</b></span></div><div>'.r3_icon('note').'<span>Total<b class="r3-blue">'.money((float)$ticket['total']).'</b><small>Precios finales según configuración</small></span></div><div class="r3-charge-box"><a class="r3-button green" href="'.url('admin/ventas?screen=checkout&ticket='.$id).'">'.r3_icon('card').'Cobrar '.money(max(0,(float)$ticket['total']-(float)$ticket['paid_total'])).'</a><span>Efectivo · Tarjeta · SINPE · Mixto · Crédito</span></div></footer><div class="r3-keyboard-hints">F2 Buscar · F4 Cliente · F8 Cobrar · Supr Quitar línea</div>';
    echo '<dialog id="r3Customer" class="r3-dialog"><h2>Cliente de la venta</h2><form method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','customer');pos_customers_ui_148($app,$t,(int)$ticket['customer_id']);echo '<footer><button class="r3-button" type="button" data-dialog-close>Cancelar</button><button class="r3-button primary">Guardar cliente</button></footer></form></dialog>';
    echo '<dialog id="r3Notes" class="r3-dialog"><h2>Nota de venta</h2><form method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','notes').'<textarea class="r3-input" name="notes" maxlength="1000" rows="4">'.e($ticket['notes']??'').'</textarea><footer><button class="r3-button" type="button" data-dialog-close>Cancelar</button><button class="r3-button primary">Guardar nota</button></footer></form></dialog>';
    echo '<dialog id="r3Discount" class="r3-dialog"><h2>Descuento</h2><form method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','discount').field('Monto','discount',$ticket['discount_total'],true,'number','.01').'<footer><button class="r3-button" type="button" data-dialog-close>Cancelar</button><button class="r3-button primary">Aplicar descuento</button></footer></form></dialog>';
    echo '<dialog id="r3Stock" class="r3-dialog"><h2>Existencias de esta sucursal</h2><div class="r3-stock-list">';foreach($products as $p)echo '<p><strong>'.e($p['name']).'</strong><span>'.($p['track_inventory']?e($p['stock']).' '.e($p['unit']??''):'Sin control de inventario').'</span></p>';echo '</div><button class="r3-button" type="button" data-dialog-close>Cerrar</button></dialog>';
    echo '<dialog id="r3LineEdit" class="r3-dialog"><h2>Editar producto</h2><form method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','edit_item').pos_hidden_148('item_id',0).'<label>Cantidad<input class="r3-input" name="quantity" type="number" min=".001" step=".001" required></label><div data-line-options></div><label>Observaciones<textarea class="r3-input" name="notes" maxlength="500"></textarea></label><footer><button class="r3-button" type="button" data-dialog-close>Cancelar</button><button class="r3-button primary">Guardar cambios</button></footer></form></dialog><script type="application/json" data-r3-items>'.r3_json($items).'</script>';
    r3_shell_end();
}
function r3_collect(App $app,array $u,array $t,array $preset=[]): void
{
    $branch=pos_access_148($app,$u,$t,true);$ids=$preset?:array_values(array_unique(array_filter(array_map('intval',(array)($_GET['tickets']??[($_GET['ticket']??0)])))));sort($ids);
    if(!$ids){pos_collect_148($app,$u,$t);return;}if(count($ids)>20)throw new DomainException('Selecciona hasta 20 cuentas de la misma mesa.');
    if(is_post()) {try{$sale=pos_settle_148($app,$t,$u,$branch,$ids);redirect(url('admin/recibo?venta='.$sale.'&auto='.(!empty($_POST['print_receipt'])?'1':'0')));}catch(Throwable $ex){flash('error',$ex->getMessage());}}
    $tickets=[];$items=[];foreach($ids as $id){$tickets[]=pos_ticket_get_148($app,$t,$branch,$id);$items=array_merge($items,pos_items_v141($app,$id));}
    if(count($tickets)>1){$table=(int)$tickets[0]['table_id'];foreach($tickets as $ticket)if(!$table||(int)$ticket['table_id']!==$table)throw new DomainException('Las cuentas deben pertenecer a la misma mesa.');}
    $split=(int)$tickets[0]['split_parts_paid']?'equal':'all';$parts=max(2,(int)$tickets[0]['split_parts']);
    $full=pos_quote_148($tickets,$items,$split,[],$parts);$ticket=$tickets[0];$back=url('admin/ventas?screen=order&ticket='.(int)$ticket['id']);
    $credit=$app->all('SELECT user_id,credit_enabled,credit_limit,current_balance FROM customer_credit_profiles WHERE tenant_id=?',[$t['id']]);
    $gifts=$app->all('SELECT customer_id,code,balance FROM fisitaap_r3_gift_cards WHERE tenant_id=? AND status="active" AND expires_at>=NOW() AND balance>0',[$t['id']]);
    r3_shell_start($app,$u,$t,$branch,'Venta rápida');r3_pos_nav($t);echo '<section class="r3-payment-context"><h2>'.e($ticket['ticket_number']).'</h2><p>Total pendiente '.money(array_sum(array_map(fn($r)=>max(0,(float)$r['total']-(float)$r['paid_total']),$tickets))).'</p><a class="r3-button" href="'.e($back).'">Volver a la venta</a></section>';
    echo '<dialog open class="r3-payment-modal" data-payment-modal><form method="post" data-r3-collect>'.csrf_field().pos_hidden_148('payment_key',bin2hex(random_bytes(16)));foreach($tickets as $a)echo pos_hidden_148('revisions['.$a['id'].']',$a['revision']);
    echo '<header><div>'.r3_icon('card').'<h2>Cobrar venta</h2></div><a href="'.e($back).'" class="r3-dialog-x" aria-label="Volver a la venta">×</a></header><div class="r3-payment-customer">';pos_customers_ui_148($app,$t,(int)$ticket['customer_id']);echo '</div><section class="r3-pay-amount">'.r3_icon('note').'<div><small>Total a pagar</small><strong data-pay-total>'.money($full['total']/100).'</strong></div><span class="r3-spacer"></span><label>Moneda: <b>CRC ₡</b><small>Conversión a USD: desactivada</small></label></section><h3>Método de pago</h3><div class="r3-method-tiles">';
    foreach(['cash'=>['Efectivo','cash'],'card'=>['Tarjeta','card'],'sinpe'=>['SINPE','transfer'],'mixed'=>['Mixto','split'],'credit'=>['Crédito','note'],'gift'=>['Regalo','gift']] as $key=>[$label,$icon])echo '<button type="button" class="r3-method '.($key==='cash'?'active':'').'" data-payment-method="'.$key.'">'.r3_icon($icon).'<span>'.$label.'</span></button>';
    echo '</div><div class="r3-pay-grid"><section><h3 data-payment-title>'.r3_icon('cash').'Pago en efectivo</h3><div class="r3-payment-fields">';foreach(['cash'=>'Monto recibido','card'=>'Monto con tarjeta','sinpe'=>'Monto con SINPE','credit'=>'Monto a crédito'] as $key=>$label)echo '<label data-pay-field="'.$key.'">'.$label.'<input class="r3-input" type="number" min="0" max="999999999" step=".01" name="'.$key.'" value="'.($key==='cash'?$full['total']/100:0).'"></label>';echo '<div data-pay-field="gift" hidden><label>Código de tarjeta<input class="r3-input" name="gift_code" maxlength="32"></label><label>Monto a usar<input class="r3-input" name="gift_amount" type="number" min="0" step=".01" value="0"></label><p data-gift-status></p></div></div><div class="r3-cash-presets"><button class="r3-button" type="button" data-cash-exact>Exacto</button>';foreach([25000,30000,40000] as $cash)echo '<button class="r3-button" type="button" data-cash-amount="'.$cash.'">'.money($cash).'</button>';echo '</div><section class="r3-change-panel">'.r3_icon('back').'<div><small>Vuelto a entregar</small><strong data-pay-change>'.money(0).'</strong><small data-pay-missing>Saldo pendiente: ₡0</small></div></section><label>Referencia de pago<input class="r3-input" name="payment_reference" maxlength="150"></label></section><section class="r3-pay-summary"><h3>Resumen del cobro</h3><div data-payment-quote></div><p><span>Efectivo recibido</span><b data-pay-received></b></p><p><span>Vuelto</span><b data-pay-change-summary></b></p><button class="r3-button" type="button" data-split-toggle>'.r3_icon('split').'Dividir cuenta</button><h3>'.r3_icon('print').'Comprobante</h3><label><input type="checkbox" name="print_receipt" value="1" checked> Imprimir recibo al confirmar</label><small>Impresora: '.e(printer_profile_148($branch)['name']?:'Caja').' · '.(int)printer_profile_148($branch)['width'].' mm</small></section></div>';
    echo '<section class="r3-split-panel" data-split-panel '.($split==='equal'?'':'hidden').'><h3>Dividir cuenta</h3><div class="r3-split-options">';foreach(['all'=>'Cuenta completa','items'=>'Pasar productos a otro cliente','equal'=>'Partes iguales'] as $key=>$label)echo '<label><input type="radio" name="split_mode" value="'.$key.'" '.($key===$split?'checked':'').' '.($key==='equal'&&count($tickets)>1?'disabled':'').'>'.$label.'</label>';echo '<label>Partes<select class="r3-input" name="parts">';foreach(range(2,20) as $p)echo '<option '.($p===$parts?'selected':'').'>'.$p.'</option>';echo '</select></label></div><div class="r3-split-products"><section><h4>Consumo pendiente</h4><button type="button" class="r3-button" data-split-none>Quitar todo</button>';foreach($items as $i){$qty=max(0,round((float)$i['quantity']-(float)$i['paid_quantity'],3));if($qty<=0)continue;echo '<div class="r3-split-product"><span>'.e($i['product_name']).'<small>Pendiente: '.e((string)$qty).'</small></span><label>Cantidad a cobrar<input class="r3-input" type="number" name="qty['.(int)$i['id'].']" min="0" max="'.e((string)$qty).'" step=".001" value="'.e((string)$qty).'" data-r3-pick="'.(int)$i['id'].'"></label><button class="r3-button" type="button" data-split-move="'.(int)$i['id'].'">→</button></div>';}echo '</section><section><h4>Productos a cobrar</h4><div data-r3-selected-lines></div></section></div></section><p class="r3-payment-error" data-payment-message role="status"></p><footer><a class="r3-button" href="'.e($back).'">'.r3_icon('back').'Volver a la venta</a><button class="r3-button green" data-confirm-payment>'.r3_icon('print').'Confirmar cobro e imprimir</button></footer><small class="r3-pay-footnote">La venta se registra cuando confirmas el cobro.</small></form></dialog><script type="application/json" data-r3-payment-data>'.r3_json(['tickets'=>$tickets,'items'=>$items,'credit'=>$credit,'gifts'=>$gifts]).'</script>';
    pos_assets_148();r3_shell_end();
}
function r3_quote_api(App $app): never
{
    $u=current_user();if(!$u||!in_array($u['role'],['tenant_admin','manager','cashier','editor'],true))json_response(['ok'=>false,'error'=>'Acceso de caja requerido.'],403);
    verify_csrf();if(restructure_can_r1($app,$u,'ventas','view')===false)json_response(['ok'=>false,'error'=>'Consulta no autorizada.'],403);
    $t=$app->one('SELECT * FROM tenants WHERE id=? AND is_active=1',[$u['tenant_id']]);if(!$t)json_response(['ok'=>false,'error'=>'Negocio no disponible.'],403);
    require_module_v12($app,$t,'pos');$branch=physical_branch_v14($app,$t);
    try{$raw=json_decode(file_get_contents('php://input'),true,32,JSON_THROW_ON_ERROR);$ids=array_values(array_unique(array_map('intval',(array)($raw['tickets']??[]))));if(!$ids||count($ids)>20)throw new DomainException('Selecciona cuentas de esta sucursal.');$tickets=[];$items=[];foreach($ids as $id){$tickets[]=pos_ticket_get_148($app,$t,$branch,$id);$items=array_merge($items,pos_items_v141($app,$id));}$q=pos_quote_148($tickets,$items,(string)($raw['mode']??'all'),(array)($raw['quantities']??[]),(int)($raw['parts']??2));json_response(['ok'=>true,'total'=>$q['total'],'net'=>$q['net'],'tax'=>$q['tax'],'service'=>$q['service'],'discount'=>$q['discount']]);}
    catch(Throwable $ex){json_response(['ok'=>false,'error'=>$ex instanceof PDOException?'No se pudo consultar el cobro.':$ex->getMessage()],422);}
}
function r3_table_dialogs(App $app,array $u,array $t,array $branch,array $tables,?array $room): void
{
    $accounts=$app->all('SELECT p.*,u.name customer_name,staff.name waiter_name,(SELECT MAX(pp.sale_id) FROM pos_payments pp WHERE pp.ticket_id=p.id) last_sale FROM pos_tickets p LEFT JOIN users u ON u.id=p.customer_id LEFT JOIN users staff ON staff.id=p.opened_by WHERE p.tenant_id=? AND p.branch_id=? AND p.table_id IS NOT NULL AND p.status NOT IN ("paid","void") ORDER BY p.id',[$t['id'],$branch['id']]);
    $items=$app->all('SELECT i.*,p.image FROM pos_ticket_items i JOIN pos_tickets a ON a.id=i.ticket_id LEFT JOIN products p ON p.id=i.product_id WHERE a.tenant_id=? AND a.branch_id=? AND a.table_id IS NOT NULL AND a.status NOT IN ("paid","void") ORDER BY i.id',[$t['id'],$branch['id']]);
    foreach($items as &$i)$i['image']=public_media_url($i['image']);unset($i);
    echo '<dialog id="r3TableAccount" class="r3-table-modal"><header><h2 data-table-name></h2><span class="r3-status" data-table-state></span><button class="r3-dialog-x" type="button" data-dialog-close aria-label="Cerrar">×</button></header><p class="r3-hint">'.e($room['name']??'').'<span data-table-sector></span></p><div class="r3-table-meta" data-table-meta></div><div data-table-accounts></div><div class="r3-table-detail-grid"><section><h3>Pedido actual</h3><a class="r3-button primary" data-table-add href="#">'.r3_icon('plus').'Agregar productos</a><div data-table-items></div><form method="post" data-table-note-form>'.csrf_field().pos_hidden_148('action','notes').pos_hidden_148('revision',0).'<label>Notas de la mesa<textarea class="r3-input" name="notes" data-table-note maxlength="1000" placeholder="Notas para esta mesa…"></textarea></label><button class="r3-button">Guardar nota</button></form></section><aside><h3>Resumen de cuenta</h3><div data-table-totals></div><p class="r3-service-tag" data-table-service></p><a class="r3-button green" data-table-charge href="#">'.r3_icon('cash').'Cobrar</a><a class="r3-button" data-table-split href="#">'.r3_icon('split').'Dividir cuenta</a></aside></div><form method="post" action="'.url('admin/ventas').'" data-table-open>'.csrf_field().pos_hidden_148('action','table').pos_hidden_148('table_id',0).pos_hidden_148('open_key',bin2hex(random_bytes(16))).'<label data-table-diner hidden>Nombre del comensal<input class="r3-input" name="diner_name" maxlength="150"></label><button class="r3-button primary">Abrir cuenta y agregar productos</button></form><footer class="r3-table-modal-actions"><form method="post" data-table-send>'.csrf_field().pos_hidden_148('action','send_kitchen').pos_hidden_148('revision',0).'<button class="r3-button">'.r3_icon('chef').'Enviar comanda</button></form><form method="post" data-table-prebill>'.csrf_field().pos_hidden_148('action','prebill').pos_hidden_148('revision',0).'<button class="r3-button">'.r3_icon('note').'Precuenta</button></form><button class="r3-button" type="button" data-table-move>'.r3_icon('transfer').'Mover cuenta</button><button class="r3-button" type="button" data-table-join>'.r3_icon('table').'Unir mesas</button><a class="r3-button" data-table-reprint href="#">'.r3_icon('print').'Reimprimir</a><a class="r3-button" data-table-more href="#">Más opciones</a></footer><button class="r3-button" type="button" data-dialog-close>'.r3_icon('back').'Volver al salón</button></dialog>';
    echo '<dialog id="r3MoveTable" class="r3-dialog"><h2 data-move-title>Mover cuenta</h2><form method="post" data-move-form>'.csrf_field().pos_hidden_148('action','move_table').pos_hidden_148('revision',0).'<label>Mesa destino<select class="r3-input" name="target_table">';foreach($tables as $table)echo '<option value="'.(int)$table['id'].'">'.e($table['name']).'</option>';echo '</select></label><p>Los consumos conservan sus precios y cargos originales.</p><footer><button class="r3-button" type="button" data-dialog-close>Cancelar</button><button class="r3-button primary">Confirmar traslado</button></footer></form></dialog><script type="application/json" data-r3-table-data>'.r3_json(['tables'=>$tables,'accounts'=>$accounts,'items'=>$items,'base'=>url(),'csrf'=>csrf_token(),'canCharge'=>restructure_can_r1($app,$u,'ventas','charge')!==false]).'</script>';
}
