<?php
declare(strict_types=1);

function r2_xml_purchase(string $xml):array {
    if(strlen($xml)>2*1024*1024||preg_match('/<!DOCTYPE|<!ENTITY/i',$xml))throw new DomainException('XML no permitido o mayor de 2 MB.');
    $previous=libxml_use_internal_errors(true);
    try{$doc=simplexml_load_string($xml,SimpleXMLElement::class,LIBXML_NONET);if(!$doc)throw new DomainException('El XML no es válido.');
        $root=$doc->getName();if(!in_array($root,['FacturaElectronica','FacturaElectronicaCompra','TiqueteElectronico','compra'],true))throw new DomainException('Se admite factura electrónica de Costa Rica 4.3/4.4 o el formato de compra de FISITAAP.');
        $get=static function(SimpleXMLElement $node,string $path,string $default=''):string{$parts=explode('/',$path);$query='.';foreach($parts as $part)$query.='/*[local-name()="'.$part.'"]';$r=$node->xpath($query);return $r?trim((string)$r[0]):$default;};
        $currency=$get($doc,'ResumenFactura/CodigoTipoMoneda/CodigoMoneda',$get($doc,'moneda','CRC'));if($currency!=='CRC')throw new DomainException('Esta carga admite importes en colones (CRC).');
        $lines=$doc->xpath('./*[local-name()="DetalleServicio"]/*[local-name()="LineaDetalle"]')?:$doc->xpath('./*[local-name()="lineas"]/*[local-name()="linea"]');
        if(!$lines||count($lines)>200)throw new DomainException('La factura debe tener entre 1 y 200 líneas.');$out=[];
        foreach($lines as $line){
            $qty=r2_number($get($line,'Cantidad',$get($line,'cantidad')),0.001,99999);$cost=r2_number($get($line,'PrecioUnitario',$get($line,'costo')));
            $discount=0.0;foreach($line->xpath('./*[local-name()="Descuento"]')?:[] as $descuento)$discount+=r2_number($get($descuento,'MontoDescuento','0'));$gross=round($qty*$cost,2);if($discount>$gross)throw new DomainException('Descuento de línea inválido.');$net=round($gross-$discount,2);
            $tax=0.0;foreach($line->xpath('./*[local-name()="Impuesto"]')?:[] as $impuesto){$exempt=r2_number($get($impuesto,'Exoneracion/MontoExoneracion','0'));$tax+=max(0,r2_number($get($impuesto,'Monto','0'))-$exempt);}
            if($root==='compra')$tax=round($net*r2_number($get($line,'impuesto','0'),0,100)/100,2);
            if($tax>$net)throw new DomainException('El impuesto supera el importe de la línea.');
            $sku=$get($line,'CodigoComercial/Codigo',$get($line,'codigo'));
            $out[]=['sku'=>$sku,'name'=>$get($line,'Detalle',$get($line,'nombre','Producto')),'quantity'=>$qty,'unit_cost'=>$qty>0?round($net/$qty,6):0,'subtotal'=>$net,'tax'=>round($tax,2),'tax_rate'=>$net>0?round($tax/$net*100,4):0];
        }
        $number=$get($doc,'Clave',$get($doc,'NumeroConsecutivo',$get($doc,'numero')));if($number==='')throw new DomainException('El XML no contiene un número de factura.');
        $total=round(array_sum(array_column($out,'subtotal'))+array_sum(array_column($out,'tax')),2);$declared=$get($doc,'ResumenFactura/TotalComprobante',$get($doc,'total',''));if($declared!==''&&abs(r2_number($declared)-$total)>.02)throw new DomainException('El total del XML incluye ajustes o cargos que no coinciden con sus productos. Registra esta compra manualmente y revisa los importes.');
        return ['number'=>mb_substr($number,0,100),'supplier'=>$get($doc,'Emisor/Nombre',$get($doc,'proveedor')),'lines'=>$out,'total'=>round(array_sum(array_column($out,'subtotal'))+array_sum(array_column($out,'tax')),2)];
    }finally{libxml_clear_errors();libxml_use_internal_errors($previous);}
}

function r2_save_purchase(App $app,array $u,array $t,array $branch,int $supplier,array $lines,string $invoice,string $key,float $paid,string $due,string $notes):int {
    if(!$app->one('SELECT id FROM suppliers WHERE id=? AND tenant_id=? AND is_active=1',[$supplier,$t['id']]))throw new DomainException('Selecciona un proveedor de este negocio.');
    if(!$branch||!$app->one('SELECT id FROM branches WHERE id=? AND tenant_id=? AND is_active=1',[$branch['id'],$t['id']]))throw new DomainException('Sucursal no disponible.');
    if(!preg_match('/^[a-f0-9]{32,64}$/',$key)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$due)||(!strtotime($due)||date('Y-m-d',strtotime($due))!==$due))throw new DomainException('Revisa la fecha y vuelve a cargar el formulario.');
    if(!$lines||count($lines)>200)throw new DomainException('Agrega los productos de la compra.');
    usort($lines,fn($a,$b)=>(int)$a['product_id']<=>(int)$b['product_id']);$app->db->beginTransaction();
    try{
        // Lock the branch to serialize duplicate invoices and inventory changes, including retries.
        $app->one('SELECT id FROM branches WHERE id=? AND tenant_id=? FOR UPDATE',[$branch['id'],$t['id']]);
        $prior=$app->one('SELECT purchase_id FROM fisitaap_r2_purchase_keys WHERE tenant_id=? AND purchase_key=?',[$t['id'],$key]);if($prior){$app->db->commit();return (int)$prior['purchase_id'];}
        if($invoice!==''&&$app->one('SELECT id FROM purchases WHERE tenant_id=? AND supplier_id=? AND invoice_number=? AND status="received" LIMIT 1',[$t['id'],$supplier,$invoice]))throw new DomainException('Esta factura del proveedor ya está registrada.');
        $subtotal=0;$tax=0;
        foreach($lines as &$line){$p=$app->one('SELECT id FROM products WHERE id=? AND tenant_id=? AND product_type="simple" FOR UPDATE',[(int)$line['product_id'],$t['id']]);if(!$p)throw new DomainException('Asigna todas las líneas a productos simples de tu negocio.');$line['quantity']=r2_number($line['quantity'],.001,99999);$line['unit_cost']=r2_number($line['unit_cost']);$line['subtotal']=round($line['quantity']*$line['unit_cost'],2);$line['tax']=round(r2_number($line['tax']),2);if($line['tax']>$line['subtotal'])throw new DomainException('Impuesto de línea inválido.');$subtotal+=pos_cents_148($line['subtotal']);$tax+=pos_cents_148($line['tax']);}unset($line);
        $total=($subtotal+$tax)/100;$paid=r2_number($paid,0,$total);$number=physical_number_v14('C');$balance=round($total-$paid,2);
        $app->exec('INSERT INTO purchases(tenant_id,branch_id,supplier_id,purchase_number,invoice_number,purchase_date,due_date,status,payment_status,subtotal,tax_total,total,balance,notes,created_by) VALUES(?,?,?,?,?,CURDATE(),?,"received",?,?,?,?,?,?,?)',[$t['id'],$branch['id'],$supplier,$number,mb_substr($invoice,0,100),$due,$balance<=0?'paid':($paid>0?'partial':'pending'),$subtotal/100,$tax/100,$total,$balance,mb_substr($notes,0,1000),$u['id']]);$id=(int)$app->db->lastInsertId();
        foreach($lines as $line){$app->exec('INSERT INTO purchase_items(purchase_id,product_id,quantity,unit_cost,tax_rate,line_subtotal,line_tax) VALUES(?,?,?,?,?,?,?)',[$id,$line['product_id'],$line['quantity'],$line['unit_cost'],$line['subtotal']>0?round($line['tax']/$line['subtotal']*100,2):0,$line['subtotal'],$line['tax']]);stock_change_v14($app,(int)$t['id'],(int)$branch['id'],(int)$line['product_id'],(float)$line['quantity'],'purchase','purchase',$id,(int)$u['id'],'Compra '.$number,(float)$line['unit_cost']);}
        if($balance>0)$app->exec('INSERT INTO accounts_payable(tenant_id,branch_id,purchase_id,supplier_id,document_number,issue_date,due_date,amount,balance,status) VALUES(?,?,?,?,?,CURDATE(),?,?,?,"pending")',[$t['id'],$branch['id'],$id,$supplier,$number,$due,$total,$balance]);
        $app->exec('INSERT INTO fisitaap_r2_purchase_keys(tenant_id,purchase_key,purchase_id) VALUES(?,?,?)',[$t['id'],$key,$id]);audit($app,(int)$t['id'],(int)$u['id'],'r2_purchase','purchase',$id);$app->db->commit();return $id;
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();throw $ex;}
}
function r2_suppliers(App $app,array $u,array $t):void {
    if(is_post()){verify_csrf();try{$id=(int)($_POST['id']??0);if($id&&!$app->one('SELECT id FROM suppliers WHERE id=? AND tenant_id=?',[$id,$t['id']]))throw new DomainException('Proveedor no disponible.');
        if(($_POST['action']??'')==='delete')$app->exec('UPDATE suppliers SET is_active=0 WHERE id=? AND tenant_id=?',[$id,$t['id']]);
        else{$name=trim((string)($_POST['name']??''));if($name===''||mb_strlen($name)>190)throw new DomainException('Escribe el nombre.');$values=[];foreach(['code','name','tax_id','contact_name','phone','email','address'] as $key)$values[]=trim((string)($_POST[$key]??''));$values[0]=$values[0]!==''?$values[0]:null;$values[]=(int)r2_number($_POST['payment_terms_days']??0,0,3650);if($id)$app->exec('UPDATE suppliers SET code=?,name=?,tax_id=?,contact_name=?,phone=?,email=?,address=?,payment_terms_days=?,is_active=1 WHERE id=? AND tenant_id=?',[...$values,$id,$t['id']]);else$app->exec('INSERT INTO suppliers(tenant_id,code,name,tax_id,contact_name,phone,email,address,payment_terms_days) VALUES(?,?,?,?,?,?,?,?,?)',[$t['id'],...$values]);}flash('success','Proveedor guardado.');
    }catch(Throwable $ex){flash('error',$ex->getMessage());}r2_redirect('proveedores');}
    $edit=$app->one('SELECT * FROM suppliers WHERE id=? AND tenant_id=?',[(int)($_GET['edit']??0),$t['id']]);$q=trim((string)($_GET['q']??''));admin_shell_start('Proveedores',$u,$t,'proveedores');echo '<div class="split"><section class="card admin-card">'.r2_form('save',(int)($edit['id']??0));foreach(['code'=>'Código','name'=>'Nombre','tax_id'=>'Identificación','contact_name'=>'Contacto','phone'=>'Teléfono','email'=>'Correo','address'=>'Dirección','payment_terms_days'=>'Plazo (días)'] as $key=>$label)echo field($label,$key,$edit[$key]??($key==='payment_terms_days'?30:''),$key==='name',$key==='payment_terms_days'?'number':'text');echo '<button class="btn">Guardar</button></form></section><section class="card admin-card"><form method="get">'.field('Buscar','q',$q).'<button class="btn btn-light">Buscar</button></form>';
    foreach($app->all('SELECT * FROM suppliers WHERE tenant_id=? AND name LIKE ? ORDER BY name',[$t['id'],'%'.$q.'%']) as $r)echo '<article class="r2-row"><strong>'.e($r['name']).'</strong><small>'.e($r['phone'].' · '.$r['email']).'</small><span>'.($r['is_active']?'Activo':'Inactivo').'</span><a class="btn btn-light" href="?edit='.(int)$r['id'].'">Editar</a>'.r2_form('delete',(int)$r['id']).'<button class="btn btn-danger">Desactivar</button></form></article>';echo '</section></div>';admin_shell_end();
}
function r2_purchases(App $app,array $u,array $t):void {
    $branch=physical_branch_v14($app,$t);$key=bin2hex(random_bytes(16));
    if(is_post()){verify_csrf();try{
        if(($_POST['action']??'')==='preview'){
            if(($_FILES['xml']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new DomainException('Selecciona un XML de hasta 2 MB.');
            $preview=r2_xml_purchase((string)file_get_contents($_FILES['xml']['tmp_name']));$preview['key']=hash('sha256',file_get_contents($_FILES['xml']['tmp_name']));$_SESSION['r2_xml'][$t['id']]=$preview;flash('success','XML leído. Asigna los productos y revisa el total antes de confirmar.');
        }else{
            $preview=($_POST['action']??'')==='receive_xml'?($_SESSION['r2_xml'][$t['id']]??null):null;$lines=[];
            if($preview){foreach($preview['lines'] as $i=>$line)$lines[]=['product_id'=>(int)($_POST['mapping'][$i]??0)]+$line;$invoice=$preview['number'];$key=$preview['key'];}
            else{$invoice=trim((string)($_POST['invoice_number']??''));$key=(string)($_POST['purchase_key']??'');foreach((array)($_POST['line']??[]) as $row){if(empty($row['product_id']))continue;$qty=r2_number($row['quantity']??0,.001,99999);$cost=r2_number($row['unit_cost']??0);$taxRate=r2_number($row['tax_rate']??0,0,100);$lines[]=['product_id'=>(int)$row['product_id'],'quantity'=>$qty,'unit_cost'=>$cost,'tax'=>round($qty*$cost*$taxRate/100,2)];}}
            if(($_POST['action']??'')==='receive_xml'&&!$preview)throw new DomainException('Vuelve a cargar el XML.');
            r2_save_purchase($app,$u,$t,$branch,(int)($_POST['supplier_id']??0),$lines,$invoice,$key,(float)($_POST['amount_paid']??0),(string)($_POST['due_date']??''),trim((string)($_POST['notes']??'')));unset($_SESSION['r2_xml'][$t['id']]);flash('success','Compra recibida. Se actualizó el inventario y el saldo por pagar.');
        }
    }catch(Throwable $ex){flash('error',$ex->getMessage());}r2_redirect('compras');}
    $products=$app->all('SELECT id,name,sku FROM products WHERE tenant_id=? AND product_type="simple" ORDER BY name',[$t['id']]);$suppliers=$app->all('SELECT id,name FROM suppliers WHERE tenant_id=? AND is_active=1 ORDER BY name',[$t['id']]);admin_shell_start('Compras',$u,$t,'compras');echo '<section class="card admin-card"><h2>Cargar factura XML</h2><form method="post" enctype="multipart/form-data">'.csrf_field().pos_hidden_148('action','preview').'<input class="input" type="file" name="xml" accept=".xml,application/xml,text/xml" required><button class="btn btn-light">Revisar XML</button></form><p>Facturas de Costa Rica 4.3/4.4 en CRC. Los códigos se relacionan con tus SKU; confirma cada línea antes de recibir.</p></section>';
    $preview=$_SESSION['r2_xml'][$t['id']]??null;
    echo '<section class="card admin-card" style="margin-top:20px"><h2>'.($preview?'Confirmar XML · '.e($preview['number']):'Compra manual').'</h2>'.r2_form($preview?'receive_xml':'receive').pos_hidden_148('purchase_key',$key).'<label>Proveedor'.r2_select('supplier_id',$suppliers).'</label>';
    if($preview){echo '<p>Emisor: '.e($preview['supplier']).' · Total de líneas: '.money((float)$preview['total']).'</p><div class="table-wrap"><table class="table"><tr><th>Línea</th><th>Producto en FISITAAP</th><th>Cantidad</th><th>Neto</th><th>Impuesto</th></tr>';foreach($preview['lines'] as $i=>$line){$pid=0;foreach($products as $p)if($line['sku']!==''&&$line['sku']===$p['sku'])$pid=(int)$p['id'];echo '<tr><td>'.e($line['name']).'<br>'.e($line['sku']).'</td><td>'.r2_select('mapping['.$i.']',$products,$pid,'name',true).'</td><td>'.e($line['quantity']).'</td><td>'.money((float)$line['subtotal']).'</td><td>'.money((float)$line['tax']).'</td></tr>';}echo '</table></div>';}
    else{echo field('Número de factura','invoice_number','').'<div class="table-wrap"><table class="table"><thead><tr><th>Producto</th><th>Cantidad</th><th>Costo unitario</th><th>IVA %</th></tr></thead><tbody data-purchase-lines>';for($i=0;$i<5;$i++)echo '<tr><td>'.r2_select('line['.$i.'][product_id]',$products,0,'name',true).'</td><td><input class="input" name="line['.$i.'][quantity]" type="number" step=".001" min=".001" value="1"></td><td><input class="input" name="line['.$i.'][unit_cost]" type="number" step=".000001" min="0" value="0"></td><td><input class="input" name="line['.$i.'][tax_rate]" type="number" step=".01" min="0" max="100" value="0"></td></tr>';echo '</tbody></table></div><button class="btn btn-light" type="button" data-add-purchase-line>Agregar línea</button>';}
    echo '<div class="split">'.field('Abono inicial','amount_paid',0,true,'number','.01').field('Vencimiento','due_date',date('Y-m-d',strtotime('+30 days')),true,'date').'</div>'.field('Notas','notes','').'<button class="btn">Confirmar y recibir compra</button></form></section>';
    [$from,$to]=valid_report_dates_v1();echo '<section class="card admin-card" style="margin-top:20px"><h2>Historial de compras</h2><form method="get"><div class="split">'.field('Desde','from',$from,true,'date').field('Hasta','to',$to,true,'date').'</div><button class="btn btn-light">Filtrar</button></form><div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Compra / factura</th><th>Proveedor</th><th>Total</th><th>Saldo</th></tr>';foreach($app->all('SELECT p.*,s.name FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.tenant_id=? AND p.purchase_date BETWEEN ? AND ? ORDER BY p.id DESC LIMIT 300',[$t['id'],$from,$to]) as $row)echo '<tr><td>'.e($row['purchase_date']).'</td><td>'.e($row['purchase_number'].' / '.$row['invoice_number']).'</td><td>'.e($row['name']).'</td><td>'.money((float)$row['total']).'</td><td>'.money((float)$row['balance']).'</td></tr>';echo '</table></div></section>';admin_shell_end();
}
