<?php
declare(strict_types=1);
require_once __DIR__.'/primary179.php';

function r2_offline_allowed(App $app,array $u):bool {
    if(!$u['is_active']||!in_array($u['role'],['tenant_admin','manager','cashier'],true))return false;
    if($u['role']==='tenant_admin')return true;
    $custom=restructure_can_r1($app,$u,'ventas','charge');
    return $custom===null?in_array($u['role'],['manager','cashier'],true):$custom;
}
function r2_desktop_admin(App $app,array $u,array $t):void {
    if($u['role']!=='tenant_admin'){http_response_code(403);simple_error('Acceso restringido','El dueño configura las cajas sin internet.');return;}
    if(is_post()){verify_csrf();try{
        $action=(string)($_POST['action']??'');$bid=(int)($_POST['branch_id']??0);if(!$app->one('SELECT id FROM branches WHERE id=? AND tenant_id=? AND is_active=1',[$bid,$t['id']]))throw new DomainException('Selecciona una sucursal.');
        if($action==='primary') { primary179_select($app,$t,(int)($_POST['id']??0)); }
        elseif($action==='pair'){
            if(!primary179_active($app)&&$app->one('SELECT id FROM fisitaap_r2_devices WHERE tenant_id=? AND branch_id=? AND is_active=1',[$t['id'],$bid]))throw new DomainException('Ya hay un equipo central para esta sucursal. Desactívalo antes de registrar otro.');
            $name=mb_substr(trim((string)($_POST['name']??'Equipo central')),0,120);$code=bin2hex(random_bytes(16));
            $app->exec('INSERT INTO fisitaap_r2_devices(tenant_id,branch_id,name,pair_hash,pair_expires) VALUES(?,?,?,?,DATE_ADD(NOW(),INTERVAL 30 MINUTE))',[$t['id'],$bid,$name,hash('sha256',$code)]);$id=(int)$app->db->lastInsertId();$_SESSION['r2_pair_once']=['tenant'=>$t['id'],'id'=>$id,'code'=>$code];
        }elseif($action==='revoke'){
            if(primary179_policy($app,['tenant_id'=>$t['id'],'id'=>(int)($_POST['id']??0)])['allowed'])throw new DomainException('Primero libera este equipo desde la caja local después de sincronizar.');
            $app->exec('UPDATE fisitaap_r2_devices SET is_active=0,token_hash=NULL,pair_hash=NULL WHERE id=? AND tenant_id=? AND branch_id=?',[(int)($_POST['id']??0),$t['id'],$bid]);}
        elseif($action==='user'){
            $uid=(int)($_POST['user_id']??0);$staff=$app->one('SELECT * FROM users WHERE id=? AND tenant_id=?',[$uid,$t['id']]);if(!$staff||!r2_offline_allowed($app,$staff))throw new DomainException('Este usuario debe estar activo y autorizado para cobrar en POS.');$password=(string)($_POST['password']??'');if(strlen($password)<12||strlen($password)>72)throw new DomainException('La contraseña local debe tener entre 12 y 72 caracteres.');
            $app->exec('INSERT INTO fisitaap_r2_offline_users(tenant_id,branch_id,user_id,password_hash,is_active) VALUES(?,?,?,?,1) ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),is_active=1',[$t['id'],$bid,$uid,password_hash($password,PASSWORD_BCRYPT)]);
        }elseif($action==='remove_user')$app->exec('UPDATE fisitaap_r2_offline_users SET is_active=0 WHERE tenant_id=? AND branch_id=? AND user_id=?',[$t['id'],$bid,(int)($_POST['user_id']??0)]);
        else throw new DomainException('Acción no disponible.');audit($app,(int)$t['id'],(int)$u['id'],'r2_desktop_'.$action,'branch',$bid);flash('success','Configuración guardada.');
    }catch(Throwable $ex){flash('error',$ex->getMessage());}r2_redirect('escritorio');}
    $branches=$app->all('SELECT id,name FROM branches WHERE tenant_id=? AND is_active=1 ORDER BY name',[$t['id']]);$staff=$app->all('SELECT id,name FROM users WHERE tenant_id=? AND is_active=1 AND role IN ("tenant_admin","manager","cashier") ORDER BY name',[$t['id']]);$pair=session_take176('r2_pair_once');admin_shell_start('Windows y cajas sin internet',$u,$t,'escritorio');
    primary179_admin($app,$t);
    if($pair&&$pair['tenant']==$t['id'])echo '<section class="card admin-card"><h2>Conectar Windows o Android principal</h2><p>En la caja local de la aplicación instalada escribe estos datos. El código dura 30 minutos y sirve una vez. Luego elígelo como principal en esta página y sincroniza su caja.</p><p>Dirección web: <strong>'.e(rtrim(url(),'/')).'</strong></p><p>Número de equipo: <strong>'.(int)$pair['id'].'</strong></p><p>Código: <code>'.e($pair['code']).'</code></p></section>';
    echo '<div class="split"><section class="card admin-card"><h2>Registrar Windows o Android</h2>'.r2_form('pair').'<label>Sucursal'.r2_select('branch_id',$branches).'</label>'.field('Nombre del equipo','name','Equipo principal',true).'<button class="btn">Crear código de conexión</button></form><p>Conecta el equipo con su código y luego elígelo como principal arriba. Solo uno por negocio, aunque tenga varias sucursales. Las cajas secundarias usan la web con internet.</p></section><section class="card admin-card"><h2>Acceso local del cajero</h2>'.r2_form('user').'<label>Sucursal'.r2_select('branch_id',$branches).'</label><label>Usuario'.r2_select('user_id',$staff).'</label>'.field('Contraseña para la caja local','password','',true,'password').'<button class="btn">Autorizar para vender sin internet</button></form><p>Esta contraseña funciona en el Windows o Android principal. Al sincronizar se renuevan los usuarios y sus permisos.</p></section></div><section class="card admin-card" style="margin-top:20px"><h2>Equipos registrados</h2>';
    foreach($app->all('SELECT d.*,b.name branch FROM fisitaap_r2_devices d JOIN branches b ON b.id=d.branch_id WHERE d.tenant_id=? ORDER BY d.id DESC',[$t['id']]) as $d)echo '<article class="r2-row"><strong>'.e($d['name']).'</strong><span>'.e($d['branch']).'</span><small>'.($d['is_active']?'Activo':'Desactivado').' · Última conexión '.e($d['last_sync']??'Pendiente').'</small>'.($d['is_active']?r2_form('revoke',(int)$d['id']).pos_hidden_148('branch_id',$d['branch_id']).'<button class="btn btn-danger">Desactivar equipo</button></form>':'').'</article>';
    echo '<h3>Cajeros autorizados</h3>';foreach($app->all('SELECT o.*,u.name,b.name branch FROM fisitaap_r2_offline_users o JOIN users u ON u.id=o.user_id JOIN branches b ON b.id=o.branch_id WHERE o.tenant_id=? AND o.is_active=1',[$t['id']]) as $s)echo '<article class="r2-row"><strong>'.e($s['name']).'</strong><span>'.e($s['branch']).'</span>'.r2_form('remove_user').pos_hidden_148('branch_id',$s['branch_id']).pos_hidden_148('user_id',$s['user_id']).'<button class="btn btn-danger">Retirar acceso local</button></form></article>';echo '</section><section class="card admin-card" style="margin-top:20px"><h2>Ventas recibidas y diferencias</h2><table class="table"><tr><th>Fecha local</th><th>Venta</th><th>Caja</th><th>Revisión</th></tr>';
    foreach($app->all('SELECT x.*,s.sale_number FROM fisitaap_r2_synced_sales x JOIN fisitaap_r2_devices d ON d.id=x.device_id JOIN sales s ON s.id=x.sale_id WHERE d.tenant_id=? ORDER BY x.local_date DESC LIMIT 200',[$t['id']]) as $row)echo '<tr><td>'.e($row['local_date']).'</td><td>'.e($row['sale_number']).'</td><td>'.e($row['register_name']).'</td><td>'.e($row['conflicts']?:'Recibida').'</td></tr>';echo '</table></section>';admin_shell_end();
}
function r2_snapshot(App $app,array $d):array {
    $t=$app->one('SELECT * FROM tenants WHERE id=? AND is_active=1',[$d['tenant_id']]);$b=$app->one('SELECT * FROM branches WHERE id=? AND tenant_id=? AND is_active=1',[$d['branch_id'],$d['tenant_id']]);if(!$t||!$b||!physical_store_v14($t)||!module_enabled_v12($app,$t,'pos'))throw new DomainException('El negocio o la sucursal no tienen POS activo.');
    $products=$app->all('SELECT p.*,COALESCE(i.quantity,0) stock,COALESCE(i.allow_negative,0) allow_negative FROM products p LEFT JOIN product_inventory i ON i.product_id=p.id AND i.branch_id=? WHERE p.tenant_id=? AND p.status="active" ORDER BY p.id',[$b['id'],$t['id']]);$out=[];
    // Fetch related catalog data in batches instead of several queries per product.
    $branchPrices=[];
    if($t['catalog_mode']==='branches')foreach($app->all('SELECT bp.* FROM branch_products bp JOIN products p ON p.id=bp.product_id AND p.tenant_id=? WHERE bp.branch_id=? AND bp.is_active=1',[$t['id'],$b['id']])as$row)$branchPrices[$row['product_id']]=$row;
    $optionsByGroup=[];
    foreach($app->all('SELECT o.* FROM product_options o JOIN product_option_groups g ON g.id=o.group_id JOIN products p ON p.id=g.product_id WHERE g.tenant_id=? AND p.tenant_id=? AND p.status="active" AND g.is_active=1 AND o.is_active=1 ORDER BY o.group_id,o.sort_order,o.id',[$t['id'],$t['id']])as$o)$optionsByGroup[$o['group_id']][]=['id'=>(int)$o['id'],'name'=>$o['name'],'price'=>pos_cents_148($o['price_delta'])];
    $groupsByProduct=[];
    foreach($app->all('SELECT g.* FROM product_option_groups g JOIN products p ON p.id=g.product_id WHERE g.tenant_id=? AND p.tenant_id=? AND p.status="active" AND g.is_active=1 ORDER BY g.product_id,g.sort_order,g.id',[$t['id'],$t['id']])as$g)$groupsByProduct[$g['product_id']][]=['id'=>(int)$g['id'],'name'=>$g['name'],'min'=>$g['is_required']?max(1,(int)$g['min_select']):(int)$g['min_select'],'max'=>$g['type']==='single'?1:(int)$g['max_select'],'options'=>$optionsByGroup[$g['id']]??[]];
    $componentsByProduct=[];
    foreach($app->all('SELECT c.combo_id,c.product_id,c.quantity,p.name,p.track_inventory,p.cost,COALESCE(i.quantity,0) stock,COALESCE(i.allow_negative,0) allow_negative FROM fisitaap_r2_combo_items c JOIN products combo ON combo.id=c.combo_id AND combo.tenant_id=? AND combo.status="active" JOIN products p ON p.id=c.product_id AND p.tenant_id=? LEFT JOIN product_inventory i ON i.product_id=p.id AND i.branch_id=? ORDER BY c.combo_id,p.id',[$t['id'],$t['id'],$b['id']])as$c)$componentsByProduct[$c['combo_id']][]=['id'=>(int)$c['product_id'],'name'=>$c['name'],'quantity'=>(int)round((float)$c['quantity']*1000),'track'=>(bool)$c['track_inventory'],'cost'=>(float)$c['cost'],'stock'=>(int)round((float)$c['stock']*1000),'allow_negative'=>(bool)$c['allow_negative']];
    foreach($products as $p){
        if($t['catalog_mode']==='branches'){$bp=$branchPrices[$p['id']]??null;if(!$bp)continue;$p['price']=$bp['price_override']??$p['price'];$p['sale_price']=$bp['sale_price_override']??$p['sale_price'];}
        $groups=$groupsByProduct[$p['id']]??[];$components=$componentsByProduct[$p['id']]??[];
        $promo=r2_promotion($app,(int)$t['id'],(int)$p['id']);$normal=pos_cents_148($p['sale_price']??$p['price']);$base=$normal;if($promo&&$promo['kind']==='special')$base=min($base,pos_cents_148($promo['value']));
        $out[]=['id'=>(int)$p['id'],'name'=>$p['name'],'sku'=>$p['sku']??'','price'=>$base,'normal_price'=>$normal,'rate'=>(int)round((float)$p['tax_rate']*100),'cost'=>(float)$p['cost'],'min'=>(int)round((float)$p['min_qty']*1000),'step'=>max(1,(int)round((float)$p['qty_step']*1000)),'stock'=>(int)round((float)$p['stock']*1000),'track'=>(bool)$p['track_inventory'],'allow_negative'=>(bool)$p['allow_negative'],'category_id'=>(int)$p['category_id'],'bogo'=>$promo&&$promo['kind']==='bogo','promo_expires'=>!empty($promo['ends_at'])?date(DATE_ATOM,strtotime($promo['ends_at'])):null,'groups'=>$groups,'components'=>$components];
    }
    $users=[];foreach($app->all('SELECT u.*,o.password_hash local_hash FROM fisitaap_r2_offline_users o JOIN users u ON u.id=o.user_id AND u.tenant_id=o.tenant_id WHERE o.tenant_id=? AND o.branch_id=? AND o.is_active=1',[$t['id'],$b['id']]) as $u)if(r2_offline_allowed($app,$u))$users[]=['id'=>(int)$u['id'],'name'=>$u['name'],'email'=>$u['email'],'password_hash'=>$u['local_hash']];
    $snapshot=['id'=>bin2hex(random_bytes(16)),'generated_at'=>date(DATE_ATOM),'tenant'=>['id'=>(int)$t['id'],'name'=>$t['name'],'tax_included'=>(bool)$t['tax_included']],'branch'=>['id'=>(int)$b['id'],'name'=>$b['name']],'products'=>$out,'users'=>$users,'categories'=>$app->all('SELECT id,name FROM categories WHERE tenant_id=? AND is_active=1 ORDER BY name',[$t['id']]),'customers'=>$app->all('SELECT u.id,u.name,u.phone FROM tenant_customers tc JOIN users u ON u.id=tc.user_id WHERE tc.tenant_id=? AND u.is_active=1 AND u.role="customer" ORDER BY u.name LIMIT 5000',[$t['id']])];
    $snapshot['offline_policy']=primary179_policy($app,$d);
    $latest=$app->one('SELECT data FROM fisitaap_r2_snapshots WHERE device_id=? ORDER BY created_at DESC LIMIT 1',[$d['id']]);if($latest){$previous=json_decode($latest['data'],true,512,JSON_THROW_ON_ERROR);$a=$previous;$b=$snapshot;unset($a['id'],$a['generated_at'],$b['id'],$b['generated_at']);if($a===$b)return $previous;}
    $app->exec('INSERT INTO fisitaap_r2_snapshots(id,device_id,data) VALUES(?,?,?)',[$snapshot['id'],$d['id'],json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)]);return $snapshot;
}
function r2_offline_quote(array $snapshot,array $rows,?int $at=null,int $discount=0):array {
    if(!$rows||count($rows)>100)throw new DomainException('Venta vacía o demasiado extensa.');$map=[];foreach($snapshot['products'] as $p)$map[$p['id']]=$p;$lines=[];$subtotal=0;$tax=0;$stock=[];
    foreach($rows as $row){$p=$map[(int)($row['id']??0)]??null;if(!$p)throw new DomainException('Producto fuera del catálogo autorizado.');$q=(int)($row['quantity']??0);if($q<$p['min']||$q>99999000||(($q-$p['min'])%$p['step'])!==0)throw new DomainException('Cantidad inválida.');$opts=array_values(array_unique(array_map('intval',(array)($row['options']??[]))));$selected=[];$extra=0;
        foreach($p['groups'] as $g){$n=0;foreach($g['options'] as $o)if(in_array($o['id'],$opts,true)){$n++;$selected[]=$o['id'];$extra+=$o['price'];}if($n<$g['min']||$n>$g['max'])throw new DomainException('Revisa las opciones del producto.');}sort($selected);sort($opts);if($selected!==$opts)throw new DomainException('Opción no autorizada.');
        $expired=!empty($p['promo_expires'])&&strtotime($p['promo_expires'])<($at??time());$price=$expired?($p['normal_price']??$p['price']):$p['price'];$paid=(!$expired&&$p['bogo'])?$q-(int)floor($q/2000)*1000:$q;$gross=(int)round(($price*$paid+$extra*$q)/1000);$net=$snapshot['tenant']['tax_included']?(int)round($gross/(1+$p['rate']/10000)):$gross;$iva=$snapshot['tenant']['tax_included']?$gross-$net:(int)round($net*$p['rate']/10000);$subtotal+=$net;$tax+=$iva;
        $lines[]=['product'=>$p,'quantity'=>$q,'net'=>$net,'tax'=>$iva,'options'=>$opts,'note'=>mb_substr((string)($row['note']??''),0,500)];
        if($p['components']){foreach($p['components'] as $c)if($c['track']){$delta=(int)round($q*$c['quantity']/1000);$stock[$c['id']]=($stock[$c['id']]??0)+$delta;}}
        elseif($p['track'])$stock[$p['id']]=($stock[$p['id']]??0)+$q;
    }
    if($discount<0||$discount>$subtotal)throw new DomainException('Descuento fuera del subtotal.');return ['lines'=>$lines,'net'=>$subtotal,'tax'=>$tax,'discount'=>$discount,'total'=>$subtotal+$tax-$discount,'stock'=>$stock];
}
function r2_sync_sales(App $app,array $d,array $payload):array {
    $sales=(array)($payload['sales']??[]);$shifts=(array)($payload['shifts']??[]);if(count($sales)>100||count($shifts)>100)throw new DomainException('Envía hasta 100 operaciones por lote.');$acks=[];$errors=[];$closedShifts=[];
    foreach($shifts as $meta){try{
        $uuid=(string)($meta['id']??'');if(!preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/',$uuid))throw new DomainException('Identificador de turno inválido.');
        $stored=$app->one('SELECT data FROM fisitaap_r2_snapshots WHERE id=? AND device_id=?',[(string)($meta['snapshot_id']??''),$d['id']]);if(!$stored)throw new DomainException('Catálogo del turno no reconocido.');$snap=json_decode($stored['data'],true,512,JSON_THROW_ON_ERROR);$uid=(int)($meta['user_id']??0);$allowed=false;foreach($snap['users'] as $user)if($user['id']===$uid)$allowed=true;if(!$allowed||!$app->one('SELECT id FROM users WHERE id=? AND tenant_id=?',[$uid,$d['tenant_id']]))throw new DomainException('Cajero no autorizado para este turno.');
        $register=mb_substr(trim((string)($meta['register']??'')),0,80);$opening=(int)r2_number($meta['opening_cash']??0,0,99999999999);$opened=strtotime((string)($meta['opened_at']??''));if(!$opened||$opened>time()+300||$opened<strtotime($snap['generated_at'])-300||$register==='')throw new DomainException('Apertura local inválida.');$hash=hash('sha256',json_encode([$uid,$register,$opening,$meta['opened_at']],JSON_THROW_ON_ERROR));
        $app->db->beginTransaction();$app->one('SELECT id FROM fisitaap_r2_devices WHERE id=? FOR UPDATE',[$d['id']]);primary179_assert_snapshot($app,$d,$snap);$link=$app->one('SELECT * FROM fisitaap_r2_shift_links WHERE device_id=? AND shift_uuid=?',[$d['id'],$uuid]);
        if($link){if($link['opening_hash']&&!hash_equals($link['opening_hash'],$hash))throw new DomainException('El turno ya corresponde a otra apertura.');}
        else{$app->exec('INSERT INTO pos_shifts(tenant_id,branch_id,user_id,name,opening_cash,status,opened_at) VALUES(?,?,?,?,?,"open",?)',[$d['tenant_id'],$d['branch_id'],$uid,'Local · '.$register,$opening/100,date('Y-m-d H:i:s',$opened)]);$sid=(int)$app->db->lastInsertId();$app->exec('INSERT INTO fisitaap_r2_shift_links(device_id,shift_uuid,shift_id,opening_hash) VALUES(?,?,?,?)',[$d['id'],$uuid,$sid,$hash]);}$app->db->commit();
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();$errors[]=['id'=>'shift:'.($meta['id']??''),'error'=>$ex instanceof PDOException?'No se pudo registrar la apertura local.':$ex->getMessage()];}}
    foreach($sales as $sale){$uuid=(string)($sale['id']??'');try{
        if(!preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/',$uuid))throw new DomainException('Identificador de venta inválido.');$hash=hash('sha256',json_encode($sale,JSON_THROW_ON_ERROR));
        $app->db->beginTransaction();$app->one('SELECT id FROM fisitaap_r2_devices WHERE id=? FOR UPDATE',[$d['id']]);$prior=$app->one('SELECT * FROM fisitaap_r2_synced_sales WHERE device_id=? AND operation_id=?',[$d['id'],$uuid]);if($prior){if(!hash_equals($prior['payload_hash'],$hash))throw new DomainException('El identificador ya corresponde a otra venta.');$app->db->commit();$acks[]=['id'=>$uuid,'sale_id'=>(int)$prior['sale_id']];continue;}
        $stored=$app->one('SELECT data FROM fisitaap_r2_snapshots WHERE id=? AND device_id=?',[(string)($sale['snapshot_id']??''),$d['id']]);if(!$stored)throw new DomainException('Catálogo de la venta no reconocido.');$snap=json_decode($stored['data'],true,512,JSON_THROW_ON_ERROR);$uid=(int)($sale['user_id']??0);$authorized=false;foreach($snap['users'] as $u)if($u['id']===$uid)$authorized=true;if(!$authorized)throw new DomainException('Cajero no autorizado en ese catálogo.');
        primary179_assert_snapshot($app,$d,$snap);
        $current=$app->one('SELECT * FROM users WHERE id=? AND tenant_id=?',[$uid,$d['tenant_id']]);if(!$current)throw new DomainException('El cajero ya no pertenece al negocio.');$conflicts=[];if(!r2_offline_allowed($app,$current))$conflicts[]='Revisar: acceso del cajero cambió después de preparar la caja.';
        $saleTime=strtotime((string)($sale['created_at']??''));if($saleTime===false)throw new DomainException('Fecha de venta inválida.');$quote=r2_offline_quote($snap,(array)($sale['items']??[]),$saleTime,(int)r2_number($sale['discount']??0,0,99999999999));$payments=[];$noncash=0;foreach(['card'=>'Tarjeta','sinpe'=>'SINPE'] as $key=>$label){$value=(int)r2_number($sale['payments'][$key]??0,0,99999999999);if($value)$payments[$label]=$value;$noncash+=$value;}$cash=(int)r2_number($sale['payments']['cash']??0,0,99999999999);$cashApplied=$quote['total']-$noncash;if($cashApplied<0||$cash<$cashApplied)throw new DomainException('Pago incompleto o superior al total.');if($cashApplied)$payments['Efectivo']=$cashApplied;
        $date=strtotime((string)($sale['created_at']??''));if($date===false||$date>time()+300||$date<strtotime($snap['generated_at'])-300)throw new DomainException('Fecha local de venta inválida.');$dateText=date('Y-m-d H:i:s',$date);$register=mb_substr(trim((string)($sale['register']??'')),0,80);if($register==='')throw new DomainException('Falta el nombre de la caja.');
        $shiftUuid=(string)($sale['shift_id']??'');if(!preg_match('/^[a-f0-9-]{36}$/',$shiftUuid))throw new DomainException('Turno local no válido.');$shift=$app->one('SELECT shift_id FROM fisitaap_r2_shift_links WHERE device_id=? AND shift_uuid=?',[$d['id'],$shiftUuid]);
        if(!$shift){$meta=null;foreach($shifts as $candidate)if(($candidate['id']??'')===$shiftUuid)$meta=$candidate;if(!$meta||(int)$meta['user_id']!==$uid)throw new DomainException('Falta el turno de la venta.');$opening=(int)r2_number($meta['opening_cash']??0,0,99999999999);$app->exec('INSERT INTO pos_shifts(tenant_id,branch_id,user_id,name,opening_cash,status,opened_at) VALUES(?,?,?,?,?,"open",?)',[$d['tenant_id'],$d['branch_id'],$uid,'Local · '.$register,$opening/100,date('Y-m-d H:i:s',strtotime($meta['opened_at'])?:$date)]);$shift=['shift_id'=>(int)$app->db->lastInsertId()];$app->exec('INSERT INTO fisitaap_r2_shift_links(device_id,shift_uuid,shift_id) VALUES(?,?,?)',[$d['id'],$shiftUuid,$shift['shift_id']]);}
        $realShift=$app->one('SELECT * FROM pos_shifts WHERE id=? AND tenant_id=? AND branch_id=? AND user_id=? FOR UPDATE',[$shift['shift_id'],$d['tenant_id'],$d['branch_id'],$uid]);if(!$realShift||$realShift['status']!=='open')throw new DomainException('El turno de esa venta ya está cerrado.');
        $cid=(int)($sale['customer']['id']??0);$customer=null;if($cid){foreach($snap['customers'] as $c)if((int)$c['id']===$cid)$customer=$c;if(!$customer)throw new DomainException('Cliente fuera del catálogo local.');}
        else{$name=mb_substr(trim((string)($sale['customer']['name']??'')),0,150);$phone=trim((string)($sale['customer']['phone']??''));if($name!==''&&$phone!=='')$customer=r2_new_customer($app,['id'=>$d['tenant_id']],$name,$phone,$current,'caja');else{$email='final-'.(int)$d['tenant_id'].'@registro.fisitaap.local';$customer=$app->one('SELECT id,name,phone FROM users WHERE email=? AND role="customer"',[$email]);if(!$customer){$app->exec('INSERT INTO users(name,email,phone,password_hash,role) VALUES("Consumidor final",?,"",?,"customer")',[$email,password_hash(bin2hex(random_bytes(32)),PASSWORD_BCRYPT)]);$customer=['id'=>(int)$app->db->lastInsertId(),'name'=>'Consumidor final'];$app->exec('INSERT IGNORE INTO tenant_customers(tenant_id,user_id) VALUES(?,?)',[$d['tenant_id'],$customer['id']]);}}}$cid=(int)$customer['id'];
        $number='L-'.$d['id'].'-'.substr(str_replace('-','',$uuid),0,16);$payKey=substr(hash('sha256',$d['id'].'|'.$uuid),0,32);
        $app->exec('INSERT INTO sales(tenant_id,branch_id,shift_id,customer_id,sale_number,sale_type,customer_name,payment_method,subtotal,tax_total,total,amount_paid,change_due,status,notes,created_by,payment_key,created_at) VALUES(?,?,?,?,?,"quick",?,?,?,?,?,?,?,"completed",?,?,?,?)',[$d['tenant_id'],$d['branch_id'],$shift['shift_id'],$cid,$number,$customer['name'],count($payments)>1?'Pago combinado':(array_key_first($payments)??'Efectivo'),$quote['net']/100,$quote['tax']/100,$quote['total']/100,$quote['total']/100,($cash-$cashApplied)/100,'Venta local · '.$register,$uid,$payKey,$dateText]);$saleId=(int)$app->db->lastInsertId();$app->exec('UPDATE sales SET discount_total=?,notes=? WHERE id=?',[$quote['discount']/100,'Venta local · '.$register.(empty($sale['note'])?'':' · '.mb_substr((string)$sale['note'],0,1000)),$saleId]);
        $app->exec('INSERT INTO pos_tickets(tenant_id,branch_id,customer_id,ticket_number,sale_type,status,subtotal,tax_total,total,paid_total,opened_by,open_key,created_at) VALUES(?,?,?, ?,"quick","paid",?,?,?,?,?,?,?)',[$d['tenant_id'],$d['branch_id'],$cid,$number,$quote['net']/100,$quote['tax']/100,$quote['total']/100,$quote['total']/100,$uid,$payKey,$dateText]);$ticket=(int)$app->db->lastInsertId();$app->exec('UPDATE pos_tickets SET discount_total=? WHERE id=?',[$quote['discount']/100,$ticket]);if(r3_active($app))$app->exec('UPDATE pos_tickets SET notes=? WHERE id=?',[mb_substr((string)($sale['note']??''),0,1000),$ticket]);
        foreach($quote['lines'] as $line){$p=$line['product'];if(!$app->one('SELECT id FROM products WHERE id=? AND tenant_id=?',[$p['id'],$d['tenant_id']]))throw new DomainException('Un producto fue eliminado del negocio.');$app->exec('INSERT INTO sale_items(sale_id,product_id,product_name,sku,quantity,unit_price,unit_cost,tax_rate,line_subtotal,line_tax) VALUES(?,?,?,?,?,?,?,?,?,?)',[$saleId,$p['id'],$p['name'],$p['sku'],$line['quantity']/1000,$line['quantity']?$line['net']/$line['quantity']*10:0,$p['cost'],$p['rate']/100,$line['net']/100,$line['tax']/100]);if(r3_active($app)){$itemId=(int)$app->db->lastInsertId();$options=[];foreach($p['groups'] as $g)foreach($g['options'] as $o)if(in_array($o['id'],$line['options'],true))$options[]=['id'=>$o['id'],'name'=>$o['name'],'group_name'=>$g['name'],'price_delta'=>$o['price']/100];$app->exec('UPDATE sale_items SET options_json=?,notes=? WHERE id=?',[json_encode($options,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$line['note'],$itemId]);}$now=$app->one('SELECT price,sale_price FROM products WHERE id=?',[$p['id']]);if(pos_cents_148($now['sale_price']??$now['price'])!==$p['price'])$conflicts[]='Precio local conservado: '.$p['name'];}
        $stock=$quote['stock'];ksort($stock,SORT_NUMERIC);foreach($stock as $pid=>$qty){if(!$app->one('SELECT id FROM products WHERE id=? AND tenant_id=?',[$pid,$d['tenant_id']]))throw new DomainException('Componente de inventario eliminado.');$app->exec('INSERT INTO product_inventory(tenant_id,branch_id,product_id,quantity) VALUES(?,?,?,0) ON DUPLICATE KEY UPDATE id=id',[$d['tenant_id'],$d['branch_id'],$pid]);$inv=$app->one('SELECT * FROM product_inventory WHERE tenant_id=? AND branch_id=? AND product_id=? FOR UPDATE',[$d['tenant_id'],$d['branch_id'],$pid]);$before=(float)$inv['quantity'];$after=round($before-$qty/1000,3);if($after<0)$conflicts[]='Revisar inventario negativo: producto '.$pid;$app->exec('UPDATE product_inventory SET quantity=? WHERE id=?',[$after,$inv['id']]);$app->exec('INSERT INTO inventory_movements(tenant_id,branch_id,product_id,movement_type,quantity,before_quantity,after_quantity,reference_type,reference_id,notes,user_id) VALUES(?,?,?,"local_sale",?,?,?,"local_sale",?,?,?)',[$d['tenant_id'],$d['branch_id'],$pid,-$qty/1000,$before,$after,$saleId,'Venta local '.$number,$uid]);}
        foreach($payments as $method=>$amount)$app->exec('INSERT INTO pos_payments(ticket_id,sale_id,customer_id,payment_method,amount,received_by) VALUES(?,?,?,?,?,?)',[$ticket,$saleId,$cid,$method,$amount/100,$uid]);
        $conflicts=array_values(array_unique($conflicts));$app->exec('INSERT INTO fisitaap_r2_synced_sales(device_id,operation_id,payload_hash,sale_id,register_name,conflicts,local_date) VALUES(?,?,?,?,?,?,?)',[$d['id'],$uuid,$hash,$saleId,$register,$conflicts?implode(' · ',$conflicts):null,$dateText]);r2_loyalty_sale($app,$saleId);audit($app,(int)$d['tenant_id'],$uid,'r2_local_sale','sale',$saleId);$app->db->commit();$acks[]=['id'=>$uuid,'sale_id'=>$saleId,'conflicts'=>$conflicts];
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();$errors[]=['id'=>$uuid,'error'=>$ex instanceof PDOException?'La base de datos rechazó esta venta. Solicita revisión.':$ex->getMessage()];}}
    // Only close after every submitted sale is durable. Failed sales remain on the central PC.
    if(!$errors)foreach($shifts as $meta)if(!empty($meta['closed_at'])){
        $link=$app->one('SELECT * FROM fisitaap_r2_shift_links WHERE device_id=? AND shift_uuid=?',[$d['id'],(string)$meta['id']]);if(!$link)continue;$closing=(int)r2_number($meta['closing_cash']??0,0,99999999999);$closed=strtotime((string)$meta['closed_at']);if(!$closed)continue;$hash=hash('sha256',json_encode([$closing,$meta['closed_at']],JSON_THROW_ON_ERROR));if($link['close_hash']&&$link['close_hash']!==$hash){$errors[]=['id'=>'shift:'.$meta['id'],'error'=>'El cierre del turno cambió.'];continue;}
        $app->db->beginTransaction();try{$s=$app->one('SELECT * FROM pos_shifts WHERE id=? FOR UPDATE',[$link['shift_id']]);if($closed<strtotime($s['opened_at'])||$closed>time()+300)throw new DomainException('Fecha de cierre inválida.');$cash=(float)$app->one('SELECT COALESCE(SUM(p.amount),0) total FROM pos_payments p JOIN sales s ON s.id=p.sale_id WHERE s.shift_id=? AND s.status="completed" AND p.payment_method="Efectivo"',[$s['id']])['total'];$expected=(float)$s['opening_cash']+$cash;$app->exec('UPDATE pos_shifts SET status="closed",closed_at=?,closing_cash=?,expected_cash=?,difference_amount=? WHERE id=?',[date('Y-m-d H:i:s',$closed),$closing/100,$expected,$closing/100-$expected,$s['id']]);$app->exec('UPDATE fisitaap_r2_shift_links SET close_hash=? WHERE device_id=? AND shift_uuid=?',[$hash,$d['id'],$meta['id']]);$app->db->commit();$closedShifts[]=$meta['id'];}catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();$errors[]=['id'=>'shift:'.$meta['id'],'error'=>'No se pudo registrar el cierre.'];}
    }
    return ['acknowledged'=>$acks,'closed_shifts'=>$closedShifts,'errors'=>$errors];
}
function r2_desktop_api(App $app,string $action):never {
    if(!is_post())json_response(['ok'=>false,'error'=>'Usa POST.'],405);$raw=file_get_contents('php://input');if(strlen($raw)>2*1024*1024)json_response(['ok'=>false,'error'=>'El lote es demasiado grande.'],413);
    try{$data=json_decode($raw,true,128,JSON_THROW_ON_ERROR);if(!is_array($data))throw new DomainException('Solicitud inválida.');
        if($action==='pair'){
            if(!rate_limit_persistent($app,'device_pair',client_identity((string)($data['device_id']??'')),8,300))json_response(['ok'=>false,'error'=>'Espera antes de intentar otra conexión.'],429);
            $app->db->beginTransaction();$d=$app->one('SELECT * FROM fisitaap_r2_devices WHERE id=? AND is_active=1 AND pair_expires>NOW() FOR UPDATE',[(int)($data['device_id']??0)]);if(!$d||!$d['pair_hash']||!hash_equals($d['pair_hash'],hash('sha256',(string)($data['code']??''))))throw new DomainException('Código de conexión inválido o vencido.');$token=bin2hex(random_bytes(32));$app->exec('UPDATE fisitaap_r2_devices SET token_hash=?,pair_hash=NULL,pair_expires=NULL,last_sync=NOW() WHERE id=?',[hash('sha256',$token),$d['id']]);$snap=r2_snapshot($app,$d);$app->db->commit();json_response(['ok'=>true,'token'=>$token,'snapshot'=>$snap]);
        }
        $headers=function_exists('getallheaders')?array_change_key_case(getallheaders(),CASE_LOWER):[];$auth=(string)($_SERVER['HTTP_AUTHORIZATION']??$_SERVER['REDIRECT_HTTP_AUTHORIZATION']??$headers['authorization']??'');$token=str_starts_with($auth,'Bearer ')?substr($auth,7):(string)($_SERVER['HTTP_X_FISITAAP_DEVICE']??'');if(!preg_match('/^[a-f0-9]{64}$/',$token))json_response(['ok'=>false,'error'=>'Equipo no autorizado.'],401);
        $d=$app->one('SELECT * FROM fisitaap_r2_devices WHERE token_hash=? AND is_active=1',[hash('sha256',$token)]);if(!$d)json_response(['ok'=>false,'error'=>'El equipo fue desactivado. Las ventas pendientes se conservan en Windows.'],401);
        $t=$app->one('SELECT * FROM tenants WHERE id=? AND is_active=1',[$d['tenant_id']]);if(!$t||!physical_store_v14($t)||!module_enabled_v12($app,$t,'pos'))json_response(['ok'=>false,'error'=>'POS no está activo para el negocio.'],403);
        if($action==='release') { primary179_release($app,$d);json_response(['ok'=>true]); }
        if($action==='snapshot'){$snap=r2_snapshot($app,$d);$app->exec('UPDATE fisitaap_r2_devices SET last_sync=NOW() WHERE id=?',[$d['id']]);json_response(['ok'=>true,'snapshot'=>$snap]);}
        if($action==='sync'){$result=r2_sync_sales($app,$d,$data);$app->exec('UPDATE fisitaap_r2_devices SET last_sync=NOW() WHERE id=?',[$d['id']]);json_response(['ok'=>true]+$result);}
        throw new DomainException('Acción no disponible.');
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();json_response(['ok'=>false,'error'=>$ex instanceof PDOException?'No se pudo guardar la operación.':$ex->getMessage()],422);}
}
