<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
if (!isset($app)) exit;
// A normal JSON 200 avoids hosting error pages replacing the old 405 probe.
if (request_path()==='api/desktop/status' && ($_SERVER['REQUEST_METHOD']??'GET')==='GET') {
    header('Cache-Control: no-store, max-age=0');
    if ($app->setting('restructure_r2_active','0')!=='1') json_response(['ok'=>false,'error'=>'La actualización de cajas todavía no está activa.'],503);
    json_response(['ok'=>true,'system'=>'fisitaap','desktop_protocol'=>1,'version'=>'1.7.9']);
}
require_once __DIR__.'/app/admin.php';
require_once __DIR__.'/app/v1.php';
require_once __DIR__.'/app/admin_v1.php';
require_once __DIR__.'/app/branches_v1.php';
require_once __DIR__.'/app/modules_v12.php';
require_once __DIR__.'/app/physical_v14.php';
require_once __DIR__.'/app/pos_v141.php';
require_once __DIR__.'/app/manuals_v142.php';
require_once __DIR__.'/app/fisichat_v143.php';
require_once __DIR__.'/app/restructure_r1.php';
require_once __DIR__.'/app/restructure_r2.php';

$path=request_path();
if($path==='master/actualizar-179') { require_once __DIR__.'/app/primary179.php'; maintenance179($app); exit; }
if($path==='master/actualizar-178') { require_once __DIR__.'/app/maintenance178.php'; maintenance178($app); exit; }
restructure_dispatch_r1($app, $path);
r2_dispatch($app,$path);
$decodedPath=rawurldecode($path);if(str_contains($decodedPath,'catálogo')){$clean=str_replace('catálogo','catalogo',$decodedPath);redirect(url($clean));}
if($path==='robots.txt'){robots_v12();}
if($path==='sitemap.xml'){sitemap_v12($app);}

if($path==='sw.js'){$cacheVersion=preg_replace('/[^a-zA-Z0-9_-]/','',$app->setting('cache_version','1'))?:'1';$assetVersion='?v='.rawurlencode($cacheVersion);header('Content-Type:application/javascript');header('Cache-Control:no-cache, no-store, must-revalidate');echo "const C='fisitapp-".$cacheVersion."',A=['".url()."','".url('assets/app.bundle.css'.$assetVersion)."','".url('assets/v12.css'.$assetVersion)."','".url('assets/fisitapp-logo.webp'.$assetVersion)."','".url('assets/app.js'.$assetVersion)."','".url('assets/placeholder.svg')."','".url('assets/icon.svg')."'];self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>Promise.all(A.map(u=>c.add(u).catch(()=>null)))).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==C).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin===location.origin&&u.pathname.includes('/assets/'))e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(n=>{if(n.ok)caches.open(C).then(c=>c.put(e.request,n.clone()));return n})));else if(e.request.mode==='navigate')e.respondWith(fetch(e.request).catch(()=>caches.match('".url()."')))});";exit;}

if($path==='manifest.webmanifest' || str_ends_with($path,'/manifest.webmanifest')){
    header('Cache-Control: public, max-age=3600');
    $parts=explode('/',$path);$tenant=count($parts)>1?tenant_by_slug($app,$parts[0]):null;$name=$tenant?$tenant['name'].' · FISITAPP':'FISITAPP';$start=$tenant?url($tenant['slug']):url();
    json_response(['name'=>$name,'short_name'=>$tenant?$tenant['name']:'FISITAPP','start_url'=>$start,'scope'=>url('/'),'display'=>'standalone','background_color'=>'#ffffff','theme_color'=>$tenant['primary_color']??'#1769e0','icons'=>[['src'=>url('assets/icon.svg'),'sizes'=>'any','type'=>'image/svg+xml','purpose'=>'any maskable']]]);
}

if($path==='login'){$requestedAudience=(string)($_GET['audience']??'customer');$audience=in_array($requestedAudience,['customer','owner','master','any'],true)?$requestedAudience:'customer';auth_page($app,'login',$audience);exit;}
if($path==='owner-login'){auth_page($app,'login','owner');exit;}
if($path==='master-login'){redirect(url('owner-login'));}
if($path==='register'){auth_page($app,'register','customer');exit;}
if($path==='driver-register'){driver_register_page_v12($app);exit;}
if($path==='forgot-password'){forgot_password_page_v1($app);exit;}
if($path==='reset-password'){reset_password_page_v1($app);exit;}
if($path==='verify-email'){verify_email_page_v1($app);exit;}
if($path==='change-password'){change_password_page($app);exit;}
if($path==='account' || str_starts_with($path,'account/')){customer_account_page_v1($app);exit;}
if($path==='driver'){driver_portal_v12($app);exit;}
if($path==='logout'){if(!is_post())redirect(url());verify_csrf();session_regenerate_id(true);$_SESSION=[];redirect(url());}
if($path==='master' || str_starts_with($path,'master/')){master_routes_v1($app,$path);exit;}
if($path==='admin' || str_starts_with($path,'admin/')){tenant_admin_routes_v1($app,$path);exit;}
if($path==='api/checkout' && is_post()){checkout_api_v6($app);}
if($path==='api/coupon-preview' && is_post()){coupon_preview_api_v1453($app);}
if($path==='api/search-log' && is_post()){search_log_api_v1($app);}
if($path==='api/pos-options'){pos_options_api_v142($app);}
if($path==='api/fisichat'){fisichat_api($app);}
if($path==='api/fisichat-public'){fisichat_public_api($app);}

if($path===''){ob_start();fisitaap_home($app);$html=ob_get_clean();$widget='';ob_start();fisichat_widget(true);$widget=ob_get_clean();echo str_replace('</body>',$widget.'</body>',$html);exit;}
if($path==='demo'){demo_selector_v131($app);exit;}
if($path==='ayuda' || $path==='manuales'){fisitapp_manuals_v142();exit;}
if($path==='demo-restaurante'){$demo=$app->one("SELECT slug,catalog_label FROM tenants WHERE slug='restaurante-demo' AND is_active=1 LIMIT 1");$demo?redirect(url($demo['slug'].'/'.catalog_segment($demo))):redirect(url());}
if($path==='blog'){global_blog_page($app);exit;}
$bits=explode('/',$path);$slug=$bits[0];$tenant=tenant_by_slug($app,$slug);
if(!$tenant){http_response_code(404);simple_error('No encontramos esta página','Revisa el enlace o vuelve al inicio.');exit;}
if(!$tenant['is_active']){layout_start('Temporalmente cerrado',$tenant);echo '<main class="auth-page"><section class="card auth-card" style="text-align:center"><div class="brand-mark" style="margin:auto;width:64px;height:64px;font-size:28px">F</div><h1>'.e($tenant['offline_message']).'</h1><p class="muted">'.e($tenant['name']).'</p></section></main>';layout_end();exit;}
$sessionUser=current_user();if($sessionUser&&$sessionUser['role']==='customer')$_SESSION['active_tenant_slug']=$tenant['slug'];
$sub=$bits[1]??'';
if($sub==='catalogo' || $sub==='menu'){catalog_page_v6($app,$tenant);exit;}
if($sub==='blog'){blog_page($app,$tenant);exit;}
if($sub==='contacto'){contact_page($app,$tenant);exit;}
tenant_home($app,$tenant);

function public_header(array $tenant=null,string $active='inicio'):void{
    global $app;
    $slug=$tenant['slug']??'';$base=$tenant?url($slug):url();$user=current_user();
    $platformLogo=$app->setting('platform_logo',url('assets/fisitapp-logo.webp'));
    $brandLogo=$tenant?($tenant['logo']??null):$platformLogo;
    $brandText=$tenant?($tenant['name']??''):($brandLogo?'':$app->setting('site_name','FISITAPP'));
    $links=[];
    if($user){
        foreach(role_nav_links_v1($app,$user,$tenant) as $route=>$label)$links[]=['href'=>url($route),'label'=>$label,'active'=>str_contains(request_path(),trim($route,'#'))];
    }else{
        $links=[
            ['href'=>$base,'label'=>'Inicio','active'=>$active==='inicio'],
            ['href'=>$tenant?url($slug.'/'.catalog_segment($tenant)):url('demo'),'label'=>$tenant['catalog_label']??'Demo','active'=>$active==='catalogo'],
            ['href'=>$tenant?url($slug.'/blog'):url('blog'),'label'=>'Blog','active'=>$active==='blog'],
            ['href'=>$tenant?url($slug.'/contacto'):url('#contacto'),'label'=>'Contacto','active'=>$active==='contacto'],
        ];
    }
    $renderLinks=static function(array $items):string{$html='';foreach($items as $item)$html.='<a class="'.($item['active']?'active':'').'" href="'.e($item['href']).'">'.e($item['label']).'</a>';return $html;};
    $loginHref='';$loginLabel='';
    if(!$user&&$tenant&&!is_demo_tenant_v12($tenant)){$loginHref=url('login?next='.rawurlencode(current_url_v1()));$loginLabel='Iniciar sesión';}
    elseif(!$user&&!$tenant){$loginHref=url('owner-login');$loginLabel='Acceso negocios';}
    echo '<header class="topbar"><div class="container nav"><a class="brand '.($tenant?(!$brandLogo?'store-name-brand':''):'platform-brand').'" href="'.e($user?role_home_url_v1($app,$user):$base).'">'.($brandLogo?'<img class="brand-logo" src="'.e($brandLogo).'" alt="'.e($tenant['name']??'FISITAAP').'">':($tenant?'':'<span class="brand-mark">F</span>')).($brandText!==''?'<span>'.e($brandText).'</span>':'').'</a><nav class="nav-links role-nav" aria-label="Navegación principal">'.$renderLinks($links).'</nav>';
    echo '<button class="icon-btn mobile-menu-toggle mobile-only" type="button" data-mobile-menu-toggle aria-expanded="false" aria-controls="mobileMenu" aria-label="Abrir menú"><span aria-hidden="true">☰</span></button>';
    if($tenant&&$active==='catalogo')echo '<button class="icon-btn nav-cart" type="button" data-open-cart aria-label="Carrito">🛒<span class="badge-count" data-cart-count>0</span></button>';
    if($user)echo '<form method="post" action="'.url('logout').'" class="nav-logout desktop-nav-action">'.csrf_field().'<button class="icon-btn" title="Cerrar sesión" aria-label="Cerrar sesión">↪</button></form>';
    elseif($loginHref!=='')echo '<a class="btn '.(!$tenant?'btn-light ':'').'desktop-nav-action" href="'.e($loginHref).'">'.e($loginLabel).'</a>';
    echo '</div><nav id="mobileMenu" class="mobile-menu-panel" data-mobile-menu aria-label="Menú móvil" hidden><div class="container mobile-menu-inner">'.$renderLinks($links);
    if($user)echo '<form method="post" action="'.url('logout').'">'.csrf_field().'<button class="mobile-menu-action" type="submit">Cerrar sesión</button></form>';
    elseif($loginHref!=='')echo '<a class="mobile-menu-action" href="'.e($loginHref).'">'.e($loginLabel).'</a>';
    echo '</div></nav></header>';
}

function demo_selector_v131(App $app):void
{
    $demos=$app->all("SELECT * FROM tenants WHERE slug IN ('restaurante-demo','tienda-demo') AND is_active=1 ORDER BY FIELD(slug,'restaurante-demo','tienda-demo')");$bySlug=array_column($demos,null,'slug');
    layout_start('Elige una demostración');public_header(null,'catalogo');echo '<main class="demo-selector-page"><section class="section"><div class="container"><div class="demo-selector-head"><span class="tag">DEMOSTRACIONES INTERACTIVAS</span><h1>Elige el tipo de negocio que quieres probar</h1><p class="muted">Ambas experiencias son independientes de las tiendas reales y permiten completar pedidos sin abrir WhatsApp. Las demos no incluyen asignación de motorizados ni entregas Express reales.</p></div><div class="demo-choice-grid">';
    foreach([['restaurante-demo','Demo de negocio de comida','Restaurante multi-sucursal con menú, tamaños, ingredientes, extras, promociones y fidelización.','slide-food','Entrar al restaurante demo','restaurante.demo@fisitaap.com','DemoRestaurante2026!'],['tienda-demo','Demo de tienda general','Tienda de ropa y tecnología con tallas, colores, garantías y variantes.','slide-fashion','Entrar a la tienda demo','negocio.demo@fisitaap.com','DemoNegocio2026!']] as $choice){$tenant=$bySlug[$choice[0]]??null;if(!$tenant)continue;$href=url($tenant['slug'].'/'.catalog_segment($tenant));echo '<a class="card demo-choice-card" href="'.e($href).'"><div class="demo-choice-image"><img src="'.e(demo_asset_public_v131($choice[3])).'" alt="'.e($choice[1]).'"><span class="tag">'.($choice[0]==='restaurante-demo'?'RESTAURANTE':'ROPA Y TECNOLOGÍA').'</span></div><div class="demo-choice-body"><h2>'.e($choice[1]).'</h2><p>'.e($choice[2]).'</p><div class="demo-panel-access"><small>Acceso al panel del negocio</small><code>'.e($choice[5]).'</code><code>'.e($choice[6]).'</code></div><span class="btn btn-accent">'.e($choice[4]).' →</span></div></a>';}
    if(!$demos)echo '<div class="card empty">Las demostraciones todavía no están disponibles. Ejecuta la actualización desde el panel maestro.</div>';echo '</div><p class="demo-selector-return"><a class="btn btn-light" href="'.url().'">← Volver al sitio oficial</a></p></div></section></main>';public_footer();layout_end();
}

function demo_asset_public_v131(string $name):string{return url('assets/demo/'.$name.'.webp');}

function fisitaap_home(App $app):void{
    $tenants=$app->all("SELECT * FROM tenants WHERE is_active=1 AND is_listed=1 AND slug NOT IN ('tienda-demo','restaurante-demo') ORDER BY name");
    layout_start('Catálogos que venden');public_header();
    echo '<main><section class="hero"><div class="container"><div class="slider">';
    $homeSlides=[[$app->setting('home_slide_1_title',$app->setting('home_title','Vende fácil. Crece rápido.')),$app->setting('home_slide_1_text',$app->setting('home_subtitle','Tu catálogo, pedidos y clientes en una plataforma lista para instalar.')),$app->setting('home_slide_1_image',url('assets/placeholder.svg'))],[$app->setting('home_slide_2_title','Tu negocio siempre cerca'),$app->setting('home_slide_2_text','Tus clientes compran desde PC, tablet o celular.'),$app->setting('home_slide_2_image',url('assets/placeholder.svg'))],[$app->setting('home_slide_3_title','Pedidos claros por WhatsApp'),$app->setting('home_slide_3_text','Menos errores, más velocidad y datos para decidir.'),$app->setting('home_slide_3_image',url('assets/placeholder.svg'))]];
    foreach($homeSlides as $i=>$s)echo adaptive_slide_v1(['tag'=>$app->setting('hero_tag','FISITAPP'),'title'=>$s[0],'body'=>$s[1],'image'=>$s[2]],$i,'linear-gradient(100deg,#123322dd,#9eaf7b55)','');
    echo '<div class="slider-dots"><button class="slider-dot active" aria-label="Ir a diapositiva 1"></button><button class="slider-dot" aria-label="Ir a diapositiva 2"></button><button class="slider-dot" aria-label="Ir a diapositiva 3"></button></div></div>';
    echo '<div class="home-hero-cta"><a class="btn btn-accent" target="_blank" rel="noopener" href="https://wa.me/'.e(preg_replace('/\D+/','',$app->setting('master_whatsapp','50686761771'))).'?text='.rawurlencode($app->setting('hero_whatsapp_message','Hola, quiero FISITAPP para mi empresa.')).'">'.e($app->setting('hero_button','Quiero FISITAPP')).'</a></div>';
    echo '</div></section>';
    echo '<section class="section"><div class="container"><div class="section-head"><div><span class="tag">'.e($app->setting('features_tag','TODO EN UNO')).'</span><h2>'.e($app->setting('features_title','Una tienda que trabaja contigo')).'</h2></div></div><div class="grid grid-3">';
    $features=[[$app->setting('feature_1_title','Catálogo flexible'),$app->setting('feature_1_text','Productos por unidad o a granel, categorías, IVA y promociones.'),$app->setting('feature_1_image',url('assets/placeholder.svg'))],[$app->setting('feature_2_title','Pedidos ordenados'),$app->setting('feature_2_text','Carrito, delivery por zona, cupones y resumen directo a WhatsApp.'),$app->setting('feature_2_image',url('assets/placeholder.svg'))],[$app->setting('feature_3_title','Decisiones con datos'),$app->setting('feature_3_text','Reportes de ventas, clientes, productos y horarios con mayor actividad.'),$app->setting('feature_3_image',url('assets/placeholder.svg'))]];foreach($features as $feature)echo '<article class="card feature"><img loading="lazy" src="'.e($feature[2]).'" alt=""><div class="card-body"><h3>'.e($feature[0]).'</h3><p class="muted">'.e($feature[1]).'</p></div></article>';
    echo '</div></div></section><section id="negocios" class="section section-soft"><div class="container"><div class="section-head"><div><span class="tag">'.e($app->setting('directory_tag','DIRECTORIO')).'</span><h2>'.e($app->setting('directory_title','Negocios en FISITAPP')).'</h2></div></div><div class="grid grid-4">';
    if(!$tenants)echo '<div class="card empty">'.e($app->setting('directory_empty','Las primeras tiendas aparecerán aquí.')).'</div>';foreach($tenants as $t)echo '<a class="card logo-card" target="_blank" rel="noopener" href="'.url($t['slug']).'">'.($t['logo']?'<img loading="lazy" src="'.e($t['logo']).'" alt="'.e($t['name']).'">':'<span class="logo-fallback">'.e($t['name']).'</span>').'</a>';
    echo '</div></div></section><section id="contacto" class="section"><div class="container split"><div><span class="tag">'.e($app->setting('contact_tag','CONTACTO')).'</span><h2>'.e($app->setting('contact_title','¿Quieres FISITAPP?')).'</h2><p class="muted">'.e($app->setting('contact_text','Conversemos sobre la tienda digital de tu empresa.')).'</p></div><div class="cta-stack"><a class="btn btn-accent btn-block" target="_blank" rel="noopener" href="https://wa.me/'.e(preg_replace('/\D+/','',$app->setting('master_whatsapp','50686761771'))).'">'.e($app->setting('contact_button','Escribir por WhatsApp')).'</a><a class="btn btn-light btn-block" href="'.url('owner-login').'">Iniciar sesión de mi negocio</a></div></div></section></main>';public_footer();layout_end();
}

function tenant_home(App $app,array $t):void{
    $content=$app->all('SELECT * FROM tenant_content WHERE tenant_id=? AND is_active=1 AND branch_id IS NULL ORDER BY section_key,sort_order',[$t['id']]);$slides=array_values(array_filter($content,fn($x)=>$x['section_key']==='home_slider'));$blocks=array_values(array_filter($content,fn($x)=>$x['section_key']==='home_block'));
    if(!$slides)$slides=[['title'=>'Todo lo que buscas','body'=>'Explora nuestro catálogo y envíanos tu pedido en pocos pasos.','image'=>url('assets/placeholder.svg')],['title'=>'Promociones para ti','body'=>'Descubre productos seleccionados y ofertas especiales.','image'=>url('assets/placeholder.svg')],['title'=>'Compra desde donde estés','body'=>'Rápido, claro y directo a nuestro WhatsApp.','image'=>url('assets/placeholder.svg')]];
    if(!$blocks)$blocks=[['title'=>'Calidad','body'=>'Productos seleccionados para nuestros clientes.','image'=>url('assets/placeholder.svg')],['title'=>'Atención cercana','body'=>'Haz tu pedido y conversemos por WhatsApp.','image'=>url('assets/placeholder.svg')],['title'=>'Entrega conveniente','body'=>'Elige tu zona y conoce el precio antes de enviar.','image'=>url('assets/placeholder.svg')]];
    layout_start('Inicio',$t);echo '<div data-tenant="'.e($t['slug']).'">';public_header($t);echo '<main><section class="hero"><div class="container"><div class="slider">';foreach($slides as $i=>$s)echo adaptive_slide_v1($s,$i,'linear-gradient(90deg,#111a,#1112)','<a class="btn btn-accent" href="'.url($t['slug'].'/'.catalog_segment($t)).'">Ver '.e($t['catalog_label']).'</a>');echo '<div class="slider-dots">';foreach($slides as $i=>$s)echo '<button class="slider-dot '.($i===0?'active':'').'" aria-label="Ir a diapositiva '.($i+1).'"></button>';echo '</div></div></div></section><section class="section"><div class="container"><div class="grid grid-3">';foreach(array_slice($blocks,0,3) as $b)echo '<article class="card feature"><img loading="lazy" src="'.e(public_media_url($b['image']??null)).'" alt="'.e($b['title']).'"><div class="card-body"><h3>'.e($b['title']).'</h3><p class="muted">'.e($b['body']).'</p></div></article>';echo '</div></div></section></main>';public_footer($t);echo '</div>';layout_end();
}

function catalog_page(App $app,array $t):void{
    $cats=$app->all('SELECT * FROM categories WHERE tenant_id=? AND is_active=1 ORDER BY sort_order,name',[$t['id']]);$products=$app->all("SELECT p.*,c.slug category_slug,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.tenant_id=? AND p.status!='hidden' ORDER BY p.is_featured DESC,p.name",[$t['id']]);
    $promo=$app->all("SELECT * FROM tenant_content WHERE tenant_id=? AND section_key='catalog_slider' AND is_active=1 ORDER BY sort_order LIMIT 3",[$t['id']]);if(!$promo)$promo=[['title'=>$t['catalog_label'],'body'=>'Elige, agrega al carrito y envía tu pedido.','image'=>url('assets/placeholder.svg')]];
    layout_start($t['catalog_label'],$t);echo '<div data-tenant="'.e($t['slug']).'">';public_header($t,'catalogo');echo '<main><section class="hero catalog-hero"><div class="container"><div class="slider">';foreach($promo as $i=>$s)echo '<article class="slide '.($i===0?'active':'').'" style="background-image:linear-gradient(90deg,#0f4faadd,#25d36699),url(\''.e($s['image']?:url('assets/placeholder.svg')).'\')"><div class="slide-content"><h1>'.e($s['title']).'</h1><p>'.e($s['body']).'</p></div></article>';echo '<div class="slider-dots">';foreach($promo as $i=>$s)echo '<button class="slider-dot '.($i===0?'active':'').'" aria-label="Promoción '.($i+1).'"></button>';echo '</div></div><div class="catalog-toolbar"><input id="catalogSearch" class="search" placeholder="Buscar productos…" aria-label="Buscar productos"><div class="chips"><button class="chip active" data-category="all">Todos</button>';foreach($cats as $c)echo '<button class="chip" data-category="'.e($c['slug']).'">'.e($c['name']).'</button>';echo '</div></div><div class="grid grid-4">';
    if(!$products)echo '<div class="card empty">Todavía no hay productos publicados.</div>';foreach($products as $p){$price=(float)($p['sale_price']?:$p['price']);$data=json_encode(['id'=>(int)$p['id'],'name'=>$p['name'],'price'=>$price,'unit'=>$p['unit_label'],'min'=>(float)$p['min_qty'],'step'=>(float)$p['qty_step']],JSON_HEX_APOS|JSON_HEX_QUOT);echo '<article class="card product-card" data-product=\''.e($data).'\' data-search="'.e(strtolower($p['name'].' '.$p['description'].' '.$p['characteristics'])).'" data-category="'.e($p['category_slug']??'').'">';echo '<img class="product-img" loading="lazy" src="'.e($p['image']?:url('assets/placeholder.svg')).'" alt="'.e($p['name']).'"><div class="product-info">'.($p['badge']?'<span class="tag">'.e($p['badge']).'</span>':'').'<h3>'.e($p['name']).'</h3><p class="muted">'.e($p['description']).'</p>'.($p['characteristics']?'<ul class="product-features"><li>'.implode('</li><li>',array_map('e',array_filter(array_map('trim',preg_split('/\R/',(string)$p['characteristics']))))).'</li></ul>':'').'<div class="product-price">'.money($price).'</div><div class="product-meta">Por '.e($p['unit_label']).' · IVA '.e((string)$p['tax_rate']).'%</div><div class="qty-row"><input data-qty class="qty" type="number" min="'.e($p['min_qty']).'" step="'.e($p['qty_step']).'" value="'.e($p['min_qty']).'" '.($p['status']==='sold_out'?'disabled':'').'><button class="btn btn-block" data-add-cart '.($p['status']==='sold_out'?'disabled':'').'>'.($p['status']==='sold_out'?'Agotado':'Agregar').'</button></div></div></article>';}
    echo '</div></div></section></main>';cart_drawer($app,$t);public_footer($t);echo '</div>';layout_end();
}

function catalog_page_v5(App $app,array $t):void
{
    track_event_v1($app,(int)$t['id'],'catalog_view');
    $cats=$app->all('SELECT * FROM categories WHERE tenant_id=? AND is_active=1 ORDER BY sort_order,name',[$t['id']]);$products=$app->all("SELECT p.*,c.slug category_slug,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.tenant_id=? AND p.status!='hidden' ORDER BY p.is_featured DESC,p.name",[$t['id']]);
    $optionRows=$app->all('SELECT g.product_id,g.id group_id,g.name group_name,g.type,g.is_required,g.min_select,g.max_select,o.id option_id,o.name option_name,o.price_delta FROM product_option_groups g JOIN product_options o ON o.group_id=g.id AND o.is_active=1 WHERE g.tenant_id=? AND g.is_active=1 ORDER BY g.product_id,g.sort_order,g.id,o.sort_order,o.id',[$t['id']]);$groupMap=[];foreach($optionRows as $row){$pid=(int)$row['product_id'];$gid=(int)$row['group_id'];if(!isset($groupMap[$pid][$gid]))$groupMap[$pid][$gid]=['id'=>$gid,'name'=>$row['group_name'],'type'=>$row['type'],'required'=>(bool)$row['is_required'],'min'=>(int)$row['min_select'],'max'=>(int)$row['max_select'],'options'=>[]];$groupMap[$pid][$gid]['options'][]=['id'=>(int)$row['option_id'],'name'=>$row['option_name'],'delta'=>(float)$row['price_delta']];}
    $promo=$app->all("SELECT * FROM tenant_content WHERE tenant_id=? AND section_key='catalog_slider' AND is_active=1 ORDER BY sort_order LIMIT 3",[$t['id']]);if(!$promo)$promo=[['title'=>$t['catalog_label'],'body'=>'Elige, personaliza y envía tu pedido.','image'=>url('assets/placeholder.svg')]];
    layout_start($t['catalog_label'],$t);echo '<div data-tenant="'.e($t['slug']).'">';public_header($t,'catalogo');echo '<main>';if($t['slug']==='tienda-demo')echo '<section class="demo-access"><div class="container demo-access-inner"><div><span class="tag">DEMO INTERACTIVA</span><strong>Prueba compras, variantes y pedidos sin enviar WhatsApp real.</strong></div><div class="demo-credentials"><span>Cliente: <b>cliente.demo@fisitaap.com</b></span><span>Clave: <b>DemoCliente2026!</b></span><span>Cupón: <b>NOVA10</b></span></div></div></section>';echo '<section class="hero catalog-hero"><div class="container"><div class="slider">';foreach($promo as $i=>$slide)echo '<article class="slide '.($i===0?'active':'').'" style="background-image:linear-gradient(90deg,#0b1d32dd,#0b7a5588),url(\''.e(public_media_url($slide['image']??null)).'\')"><div class="slide-content"><h1>'.e($slide['title']).'</h1><p>'.e($slide['body']).'</p></div></article>';echo '<div class="slider-dots">';foreach($promo as $i=>$slide)echo '<button class="slider-dot '.($i===0?'active':'').'" aria-label="Promoción '.($i+1).'"></button>';echo '</div></div><div class="catalog-toolbar"><input id="catalogSearch" class="search" placeholder="Buscar productos…" aria-label="Buscar productos"><div class="chips"><button class="chip active" data-category="all">Todos</button>';foreach($cats as $category)echo '<button class="chip" data-category="'.e($category['slug']).'">'.e($category['name']).'</button>';echo '</div></div><div class="grid grid-4">';
    if(!$products)echo '<div class="card empty">Todavía no hay productos publicados.</div>';
    foreach($products as $product){$price=(float)($product['sale_price']?:$product['price']);$groups=array_values($groupMap[(int)$product['id']]??[]);$data=json_encode(['id'=>(int)$product['id'],'name'=>$product['name'],'price'=>$price,'unit'=>$product['unit_label'],'min'=>(float)$product['min_qty'],'step'=>(float)$product['qty_step'],'groups'=>$groups],JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE);$gallery=json_decode((string)($product['gallery']??'[]'),true)?:[];$images=array_values(array_unique(array_map('public_media_url',array_filter(array_merge([$product['image']?:url('assets/placeholder.svg')],$gallery)))));echo '<article class="card product-card" data-product=\''.e($data).'\' data-search="'.e(strtolower($product['name'].' '.$product['description'].' '.$product['characteristics'])).'" data-category="'.e($product['category_slug']??'').'">';echo '<div class="product-gallery"><img class="product-img" data-gallery-main loading="lazy" src="'.e($images[0]).'" alt="'.e($product['name']).'">';if(count($images)>1){echo '<div class="product-thumbs">';foreach($images as $i=>$image)echo '<button type="button" class="product-thumb '.($i===0?'active':'').'" data-gallery-src="'.e($image).'" aria-label="Imagen '.($i+1).'"><img src="'.e($image).'" alt=""></button>';echo '</div>';}echo '</div><div class="product-info">'.($product['badge']?'<span class="tag">'.e($product['badge']).'</span>':'').(($product['product_type']??'simple')==='combo'?'<span class="tag combo-tag">COMBO</span>':'').'<h3>'.e($product['name']).'</h3><p class="muted">'.e($product['description']).'</p>'.($product['characteristics']?'<ul class="product-features"><li>'.implode('</li><li>',array_map('e',array_filter(array_map('trim',preg_split('/\R/',(string)$product['characteristics']))))).'</li></ul>':'').'<div class="product-price">'.money($price).'</div><div class="product-meta">Por '.e($product['unit_label']).' · IVA '.e((string)$product['tax_rate']).'%</div><div class="qty-row"><input data-qty class="qty" type="number" min="'.e($product['min_qty']).'" step="'.e($product['qty_step']).'" value="'.e($product['min_qty']).'" '.($product['status']==='sold_out'?'disabled':'').'><button class="btn btn-block" '.($groups?'data-customize-cart':'data-add-cart').' '.($product['status']==='sold_out'?'disabled':'').'>'.($product['status']==='sold_out'?'Agotado':'Agregar al carrito').'</button></div></div></article>';}
    echo '</div></div></section></main>';cart_drawer($app,$t);echo '<div id="productCustomizer" class="product-modal" aria-hidden="true"><div class="product-modal-bg" data-close-customizer></div><section class="card product-modal-panel"><div class="drawer-head"><div><span class="tag">PERSONALIZAR</span><h2 id="customizerTitle">Producto</h2></div><button class="icon-btn" type="button" data-close-customizer>×</button></div><div id="customizerGroups"></div><div class="form-group"><label>Observaciones para este producto</label><textarea id="customizerNote" class="input" maxlength="500" placeholder="Ejemplo: sin cebolla, salsa aparte…"></textarea></div><div class="split"><div class="form-group"><label>Cantidad</label><input id="customizerQty" class="input" type="number"></div><div class="customizer-total"><small>Total unitario</small><strong id="customizerPrice">₡0,00</strong></div></div><button id="customizerAdd" type="button" class="btn btn-accent btn-block">Agregar al carrito</button></section></div>';public_footer($t);echo '</div>';layout_end();
}

function cart_drawer(App $app,array $t):void{
    $zones=$app->all('SELECT * FROM delivery_zones WHERE tenant_id=? AND is_active=1 ORDER BY name',[$t['id']]);
    $paymentMethods=json_decode((string)($t['payment_methods']??''),true)?:['SINPE Móvil','Efectivo','Tarjeta al recibir','Transferencia'];$deliveryTypes=json_decode((string)($t['delivery_types']??''),true)?:['delivery','pickup','coordinated'];$paymentHtml='';foreach($paymentMethods as $method)$paymentHtml.='<option>'.e($method).'</option>';$deliveryHtml='';foreach(['delivery'=>'Delivery','pickup'=>'Recoger en el negocio','coordinated'=>'Envío coordinado'] as $key=>$label)if(in_array($key,$deliveryTypes,true))$deliveryHtml.='<option value="'.$key.'">'.$label.'</option>';
    $user=current_user();$addresses=$user&&$user['role']==='customer'?$app->all('SELECT * FROM customer_addresses WHERE user_id=? ORDER BY is_default DESC,id DESC',[$user['id']]):[];
    echo '<aside id="cartDrawer" class="drawer"><div class="drawer-bg" data-close-cart></div><div class="drawer-panel"><div class="drawer-head"><h2>Tu pedido</h2><button class="icon-btn" data-close-cart>×</button></div><div id="cartItems"></div><div class="cart-summary"><div class="summary-row"><span>Subtotal estimado</span><strong id="cartSubtotal">₡0,00</strong></div><small class="muted">IVA, descuento y entrega se calculan al confirmar.</small></div><form id="checkoutForm" action="'.url('api/checkout').'">'.csrf_field().'<input type="hidden" name="tenant" value="'.e($t['slug']).'"><div class="form-group"><label>Cédula (opcional)</label><input class="input" name="customer_id_number" maxlength="40"></div><div class="form-group"><label>Forma de pago</label><select class="input" name="payment" required>'.$paymentHtml.'</select></div><div class="form-group"><label>Tipo de entrega</label><select class="input" name="delivery_type">'.$deliveryHtml.'</select></div><div class="form-group"><label>Zona de envío</label><select class="input" name="zone_id"><option value="">Seleccionar</option>';foreach($zones as $z)echo '<option value="'.(int)$z['id'].'">'.e($z['name']).' · '.money((float)$z['price']).'</option>';echo '</select></div>';if($addresses){echo '<div class="form-group"><label>Dirección guardada</label><select class="input" data-saved-address><option value="">Escribir otra dirección</option>';foreach($addresses as $a)echo '<option value="'.e(json_encode(['address'=>$a['address'],'reference'=>$a['reference']],JSON_HEX_APOS|JSON_HEX_QUOT)).'">'.e($a['label']).' · '.e($a['address']).'</option>';echo '</select></div>';}echo '<div class="form-group"><label>Dirección</label><textarea class="input" name="address" placeholder="Provincia, cantón y distrito"></textarea></div><div class="form-group"><label>Referencia</label><textarea class="input" name="address_reference" placeholder="Señas para llegar"></textarea></div><div class="form-group"><label>Programar pedido (opcional)</label><input class="input" type="datetime-local" name="scheduled_at" min="'.date('Y-m-d\TH:i').'"></div><div class="form-group"><label>Código de descuento</label><input class="input" name="coupon" maxlength="60"></div><div class="form-group"><label>Notas</label><textarea class="input" name="notes" placeholder="Detalles para el negocio"></textarea></div><button class="btn btn-accent btn-block" type="submit">Enviar pedido por WhatsApp</button></form></div></aside>';
}

function checkout_api(App $app):never{
    $raw=json_decode(file_get_contents('php://input'),true)?:[];$_POST=$raw+$_POST;verify_csrf();$u=current_user();if(!$u||$u['role']!=='customer')json_response(['ok'=>false,'login'=>url('login?next='.rawurlencode($_SERVER['HTTP_REFERER']??url()))],401);
    if(!rate_limit_persistent($app,'checkout',client_identity((string)$u['id']),10,300))json_response(['ok'=>false,'error'=>'Demasiados intentos. Espera unos minutos.'],429);
    $t=tenant_by_slug($app,(string)($raw['tenant']??''));if(!$t||!$t['is_active'])json_response(['ok'=>false,'error'=>'Tienda no disponible.'],404);$items=$raw['items']??[];if(!$items||count($items)>100)json_response(['ok'=>false,'error'=>'Carrito inválido.'],422);
    $deliveryType=(string)($raw['delivery_type']??'delivery');$payment=(string)($raw['payment']??'');$address=trim((string)($raw['address']??''));
    if(!in_array($deliveryType,['delivery','pickup','coordinated'],true))json_response(['ok'=>false,'error'=>'Tipo de entrega inválido.'],422);
    if(!in_array($payment,['SINPE Móvil','Efectivo','Tarjeta al recibir','Transferencia'],true))json_response(['ok'=>false,'error'=>'Forma de pago inválida.'],422);
    if($deliveryType==='delivery'&&$address==='')json_response(['ok'=>false,'error'=>'Escribe la dirección completa para el delivery.'],422);
    $ids=array_values(array_unique(array_map('intval',array_column($items,'id'))));$ph=implode(',',array_fill(0,count($ids),'?'));$products=$app->all("SELECT * FROM products WHERE tenant_id=? AND status='active' AND id IN ($ph)",array_merge([$t['id']],$ids));$map=[];foreach($products as $p)$map[$p['id']]=$p;if(count($map)!==count($ids))json_response(['ok'=>false,'error'=>'Uno o más productos ya no están disponibles.'],422);
    $subtotal=0;$tax=0;$lines=[];foreach($items as $i){$p=$map[(int)$i['id']];$q=round((float)$i['qty'],(int)$p['decimals']);$min=(float)$p['min_qty'];$step=(float)$p['qty_step'];$steps=($q-$min)/$step;if($q<$min||$q>99999||abs($steps-round($steps))>0.0001)json_response(['ok'=>false,'error'=>'Cantidad inválida para '.$p['name']],422);$price=(float)($p['sale_price']?:$p['price']);$line=$price*$q;$lineTax=$line*((float)$p['tax_rate']/100);$subtotal+=$line;$tax+=$lineTax;$lines[]=[$p,$q,$price,$line,$lineTax];}
    $zoneTotal=0;$zone=null;if($deliveryType==='delivery'){if(empty($raw['zone_id']))json_response(['ok'=>false,'error'=>'Selecciona una zona de envío.'],422);$zone=$app->one('SELECT * FROM delivery_zones WHERE id=? AND tenant_id=? AND is_active=1',[(int)$raw['zone_id'],$t['id']]);if(!$zone)json_response(['ok'=>false,'error'=>'Zona inválida.'],422);if($subtotal<(float)$zone['min_order'])json_response(['ok'=>false,'error'=>'Esta zona requiere una compra mínima de '.money((float)$zone['min_order'])],422);$zoneTotal=(float)$zone['price'];}
    $discount=0;$couponCode=strtoupper(trim((string)($raw['coupon']??'')));$number='';$total=0;
    $app->db->beginTransaction();try{
        if($couponCode){$c=$app->one("SELECT * FROM coupons WHERE tenant_id=? AND code=? AND is_active=1 AND (starts_at IS NULL OR starts_at<=NOW()) AND (ends_at IS NULL OR ends_at>=NOW()) FOR UPDATE",[$t['id'],$couponCode]);if(!$c||($c['max_uses']!==null&&(int)$c['uses_count']>=(int)$c['max_uses'])||$subtotal<(float)$c['min_order'])throw new DomainException('El cupón no es válido para este pedido.');$discount=$c['type']==='percent'?min($subtotal,$subtotal*((float)$c['value']/100)):min($subtotal,(float)$c['value']);}
        $total=$subtotal+$tax+$zoneTotal-$discount;
        $app->exec('INSERT INTO order_sequences(tenant_id,next_number) SELECT ?,COALESCE(MAX(CAST(order_number AS UNSIGNED)),0)+1 FROM orders WHERE tenant_id=? ON DUPLICATE KEY UPDATE tenant_id=VALUES(tenant_id)',[$t['id'],$t['id']]);
        $seq=$app->one('SELECT next_number FROM order_sequences WHERE tenant_id=? FOR UPDATE',[$t['id']]);$next=(int)$seq['next_number'];$app->exec('UPDATE order_sequences SET next_number=next_number+1 WHERE tenant_id=?',[$t['id']]);$number=str_pad((string)$next,5,'0',STR_PAD_LEFT);
        $app->exec('INSERT INTO orders(tenant_id,user_id,order_number,customer_name,customer_phone,address,delivery_zone_id,delivery_type,payment_method,coupon_code,subtotal,tax_total,discount_total,delivery_total,total,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$t['id'],$u['id'],$number,$u['name'],$u['phone']??'',$address,$zone['id']??null,$deliveryType,$payment,$couponCode?:null,$subtotal,$tax,$discount,$zoneTotal,$total,substr((string)($raw['notes']??''),0,1000)]);$oid=(int)$app->db->lastInsertId();foreach($lines as [$p,$q,$price,$line,$lineTax])$app->exec('INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_label,unit_price,tax_rate,line_subtotal,line_tax) VALUES(?,?,?,?,?,?,?,?,?)',[$oid,$p['id'],$p['name'],$q,$p['unit_label'],$price,$p['tax_rate'],$line,$lineTax]);if($couponCode)$app->exec('UPDATE coupons SET uses_count=uses_count+1 WHERE tenant_id=? AND code=?',[$t['id'],$couponCode]);$app->db->commit();
    }catch(DomainException $e){if($app->db->inTransaction())$app->db->rollBack();json_response(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable){if($app->db->inTransaction())$app->db->rollBack();json_response(['ok'=>false,'error'=>'No se pudo guardar el pedido. Intenta nuevamente.'],500);}
    $msg="🛒 NUEVO PEDIDO #{$number}\n📅 ".date('d/m/Y - H:i')." hs\n👤 Cliente: {$u['name']}\n📱 Tel: ".($u['phone']??'')."\n📍 Dirección: {$address}\n━━ PRODUCTOS ━━\n";foreach($lines as [$p,$q,$price,$line])$msg.="• ".rtrim(rtrim(number_format($q,3,'.',''),'0'),'.')." {$p['unit_label']} {$p['name']} — ".money($line)."\n";$msg.="━━━━\nSubtotal: ".money($subtotal)."\nIVA: ".money($tax)."\nDescuento: -".money($discount)."\nEntrega: ".money($zoneTotal)."\nTOTAL: ".money($total)."\n💳 Pago: {$payment}\n🚚 Entrega: ".($zone['name']??($deliveryType==='pickup'?'Recoger en el negocio':'Envío coordinado'));$wa=preg_replace('/\D+/','',$t['whatsapp']?:$t['phone']);json_response(['ok'=>true,'order'=>$number,'whatsapp'=>'https://wa.me/'.$wa.'?text='.rawurlencode($msg)]);
}

function checkout_api_v5(App $app):never
{
    $raw=json_decode(file_get_contents('php://input'),true)?:[];$_POST=$raw+$_POST;verify_csrf();$user=current_user();if($user&&$user['role']!=='customer')json_response(['ok'=>false,'error'=>'Para comprar, cierra tu sesión administrativa e ingresa con una cuenta de cliente.'],403);if(!$user){$next=safe_next_url_v1($app,(string)($_SERVER['HTTP_REFERER']??''));json_response(['ok'=>false,'login'=>url('login'.($next?'?next='.rawurlencode($next):''))],401);}
    if(!rate_limit_persistent($app,'checkout',client_identity((string)$user['id']),10,300))json_response(['ok'=>false,'error'=>'Demasiados intentos. Espera unos minutos.'],429);
    $tenant=tenant_by_slug($app,(string)($raw['tenant']??''));if(!$tenant||!$tenant['is_active'])json_response(['ok'=>false,'error'=>'Tienda no disponible.'],404);$items=$raw['items']??[];if(!is_array($items)||!$items||count($items)>100)json_response(['ok'=>false,'error'=>'Carrito inválido.'],422);
    $deliveryType=(string)($raw['delivery_type']??'delivery');$payment=(string)($raw['payment']??'');$address=trim((string)($raw['address']??''));$reference=trim(substr(strip_tags((string)($raw['address_reference']??'')),0,500));$idNumber=trim(substr(strip_tags((string)($raw['customer_id_number']??'')),0,40));$scheduledAt=null;if(!empty($raw['scheduled_at'])){$scheduled=strtotime((string)$raw['scheduled_at']);if($scheduled===false||$scheduled<time()-60||$scheduled>strtotime('+90 days'))json_response(['ok'=>false,'error'=>'La fecha programada no es válida.'],422);$scheduledAt=date('Y-m-d H:i:s',$scheduled);}$allowedDeliveries=json_decode((string)($tenant['delivery_types']??''),true)?:['delivery','pickup','coordinated'];$allowedPayments=json_decode((string)($tenant['payment_methods']??''),true)?:['SINPE Móvil','Efectivo','Tarjeta al recibir','Transferencia'];if(!in_array($deliveryType,$allowedDeliveries,true))json_response(['ok'=>false,'error'=>'Tipo de entrega inválido.'],422);if(!in_array($payment,$allowedPayments,true))json_response(['ok'=>false,'error'=>'Forma de pago inválida.'],422);if($deliveryType==='delivery'&&$address==='')json_response(['ok'=>false,'error'=>'Escribe la dirección completa para el delivery.'],422);
    $ids=array_values(array_unique(array_filter(array_map('intval',array_column($items,'id')))));if(!$ids)json_response(['ok'=>false,'error'=>'Carrito inválido.'],422);$placeholders=implode(',',array_fill(0,count($ids),'?'));$products=$app->all("SELECT * FROM products WHERE tenant_id=? AND status='active' AND id IN ($placeholders)",array_merge([$tenant['id']],$ids));$productMap=[];foreach($products as $product)$productMap[(int)$product['id']]=$product;if(count($productMap)!==count($ids))json_response(['ok'=>false,'error'=>'Uno o más productos ya no están disponibles.'],422);
    $rows=$app->all("SELECT g.product_id,g.id group_id,g.name group_name,g.type,g.is_required,g.min_select,g.max_select,o.id option_id,o.name option_name,o.price_delta FROM product_option_groups g LEFT JOIN product_options o ON o.group_id=g.id AND o.is_active=1 WHERE g.tenant_id=? AND g.is_active=1 AND g.product_id IN ($placeholders) ORDER BY g.product_id,g.sort_order,g.id,o.sort_order,o.id",array_merge([$tenant['id']],$ids));$groups=[];$optionLookup=[];foreach($rows as $row){$pid=(int)$row['product_id'];$gid=(int)$row['group_id'];if(!isset($groups[$pid][$gid]))$groups[$pid][$gid]=['id'=>$gid,'name'=>$row['group_name'],'type'=>$row['type'],'min'=>(int)$row['min_select'],'max'=>(int)$row['max_select'],'required'=>(bool)$row['is_required'],'options'=>[]];if($row['option_id']!==null){$oid=(int)$row['option_id'];$option=['id'=>$oid,'group_id'=>$gid,'group'=>$row['group_name'],'name'=>$row['option_name'],'delta'=>(float)$row['price_delta']];$groups[$pid][$gid]['options'][$oid]=$option;$optionLookup[$pid][$oid]=$option;}}
    $subtotal=0.0;$tax=0.0;$lines=[];foreach($items as $item){if(!is_array($item))json_response(['ok'=>false,'error'=>'Carrito inválido.'],422);$pid=(int)($item['id']??0);if(!isset($productMap[$pid]))json_response(['ok'=>false,'error'=>'Producto no disponible.'],422);$product=$productMap[$pid];$quantity=round((float)($item['qty']??0),(int)$product['decimals']);$minimum=(float)$product['min_qty'];$step=(float)$product['qty_step'];$steps=($quantity-$minimum)/$step;if($quantity<$minimum||$quantity>99999||abs($steps-round($steps))>0.0001)json_response(['ok'=>false,'error'=>'Cantidad inválida para '.$product['name']],422);
        $optionIds=is_array($item['option_ids']??null)?array_values(array_unique(array_map('intval',$item['option_ids']))):[];if(count($optionIds)>30)json_response(['ok'=>false,'error'=>'Demasiadas opciones para '.$product['name']],422);$selectedByGroup=[];$snapshot=[];$delta=0.0;foreach($optionIds as $optionId){$option=$optionLookup[$pid][$optionId]??null;if(!$option)json_response(['ok'=>false,'error'=>'Una opción de '.$product['name'].' ya no está disponible.'],422);$selectedByGroup[$option['group_id']][]=$optionId;$snapshot[]=['id'=>$option['id'],'group'=>$option['group'],'name'=>$option['name'],'delta'=>$option['delta']];$delta+=$option['delta'];}
        foreach($groups[$pid]??[] as $group){$count=count($selectedByGroup[$group['id']]??[]);$min=$group['required']?max(1,$group['min']):$group['min'];$max=$group['type']==='single'?1:max(1,$group['max']);if($count<$min||$count>$max)json_response(['ok'=>false,'error'=>'Revisa la selección de '.$group['name'].' en '.$product['name'].'.'],422);}
        $base=(float)($product['sale_price']?:$product['price']);$price=$base+$delta;if($price<0)json_response(['ok'=>false,'error'=>'Precio inválido.'],422);$lineSubtotal=$price*$quantity;$lineTax=$lineSubtotal*((float)$product['tax_rate']/100);$note=trim(substr(strip_tags((string)($item['note']??'')),0,500));$subtotal+=$lineSubtotal;$tax+=$lineTax;$lines[]=['product'=>$product,'quantity'=>$quantity,'price'=>$price,'subtotal'=>$lineSubtotal,'tax'=>$lineTax,'options'=>$snapshot,'note'=>$note];
    }
    $zoneTotal=0.0;$zone=null;if($deliveryType==='delivery'){if(empty($raw['zone_id']))json_response(['ok'=>false,'error'=>'Selecciona una zona de envío.'],422);$zone=$app->one('SELECT * FROM delivery_zones WHERE id=? AND tenant_id=? AND is_active=1',[(int)$raw['zone_id'],$tenant['id']]);if(!$zone)json_response(['ok'=>false,'error'=>'Zona inválida.'],422);if($subtotal<(float)$zone['min_order'])json_response(['ok'=>false,'error'=>'Esta zona requiere una compra mínima de '.money((float)$zone['min_order'])],422);$zoneTotal=(float)$zone['price'];}
    $discount=0.0;$couponCode=strtoupper(trim((string)($raw['coupon']??'')));$number='';$total=0.0;$app->db->beginTransaction();try{if($couponCode){$coupon=$app->one("SELECT * FROM coupons WHERE tenant_id=? AND code=? AND is_active=1 AND (starts_at IS NULL OR starts_at<=NOW()) AND (ends_at IS NULL OR ends_at>=NOW()) FOR UPDATE",[$tenant['id'],$couponCode]);if(!$coupon||($coupon['max_uses']!==null&&(int)$coupon['uses_count']>=(int)$coupon['max_uses'])||$subtotal<(float)$coupon['min_order'])throw new DomainException('El cupón no es válido para este pedido.');$discount=$coupon['type']==='percent'?min($subtotal,$subtotal*((float)$coupon['value']/100)):min($subtotal,(float)$coupon['value']);}$total=$subtotal+$tax+$zoneTotal-$discount;
        $app->exec('INSERT INTO order_sequences(tenant_id,next_number) SELECT ?,COALESCE(MAX(CAST(order_number AS UNSIGNED)),0)+1 FROM orders WHERE tenant_id=? ON DUPLICATE KEY UPDATE tenant_id=VALUES(tenant_id)',[$tenant['id'],$tenant['id']]);$sequence=$app->one('SELECT next_number FROM order_sequences WHERE tenant_id=? FOR UPDATE',[$tenant['id']]);$next=(int)$sequence['next_number'];$app->exec('UPDATE order_sequences SET next_number=next_number+1 WHERE tenant_id=?',[$tenant['id']]);$number=str_pad((string)$next,5,'0',STR_PAD_LEFT);
        $app->exec('INSERT INTO orders(tenant_id,user_id,order_number,customer_name,customer_phone,customer_id_number,address,address_reference,scheduled_at,delivery_zone_id,delivery_type,payment_method,coupon_code,subtotal,tax_total,discount_total,delivery_total,total,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$tenant['id'],$user['id'],$number,$user['name'],$user['phone']??'',$idNumber?:null,$address,$reference?:null,$scheduledAt,$zone['id']??null,$deliveryType,$payment,$couponCode?:null,$subtotal,$tax,$discount,$zoneTotal,$total,substr((string)($raw['notes']??''),0,1000)]);$orderId=(int)$app->db->lastInsertId();foreach($lines as $line){$product=$line['product'];$app->exec('INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_label,unit_price,tax_rate,line_subtotal,line_tax,options_json,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[$orderId,$product['id'],$product['name'],$line['quantity'],$product['unit_label'],$line['price'],$product['tax_rate'],$line['subtotal'],$line['tax'],$line['options']?json_encode($line['options'],JSON_UNESCAPED_UNICODE):null,$line['note']?:null]);}if($couponCode)$app->exec('UPDATE coupons SET uses_count=uses_count+1 WHERE tenant_id=? AND code=?',[$tenant['id'],$couponCode]);$app->db->commit();track_event_v1($app,(int)$tenant['id'],'checkout_completed');
    }catch(DomainException $exception){if($app->db->inTransaction())$app->db->rollBack();json_response(['ok'=>false,'error'=>$exception->getMessage()],422);}catch(Throwable){if($app->db->inTransaction())$app->db->rollBack();json_response(['ok'=>false,'error'=>'No se pudo guardar el pedido. Intenta nuevamente.'],500);}
    $message="🛒 NUEVO PEDIDO #{$number}\n📅 ".date('d/m/Y - H:i')." hs".($scheduledAt?"\n⏰ Programado: ".date('d/m/Y H:i',strtotime($scheduledAt)):"")."\n👤 Cliente: {$user['name']}".($idNumber?"\n🪪 Cédula: {$idNumber}":"")."\n📱 Tel: ".($user['phone']??'')."\n📍 Dirección: {$address}".($reference?"\n🧭 Referencia: {$reference}":"")."\n━━ PRODUCTOS ━━\n";foreach($lines as $line){$product=$line['product'];$message.='• '.rtrim(rtrim(number_format($line['quantity'],3,'.',''),'0'),'.').' '.$product['unit_label'].' '.$product['name'].' — '.money($line['subtotal'])."\n";foreach($line['options'] as $option)$message.='   ↳ '.$option['group'].': '.$option['name'].($option['delta']>0?' (+'.money((float)$option['delta']).')':'')."\n";if($line['note'])$message.='   Nota: '.$line['note']."\n";}$message.="━━━━\nSubtotal: ".money($subtotal)."\nIVA: ".money($tax)."\nDescuento: -".money($discount)."\nEntrega: ".money($zoneTotal)."\nTOTAL: ".money($total)."\n💳 Pago: {$payment}\n🚚 Entrega: ".($zone['name']??($deliveryType==='pickup'?'Recoger en el negocio':'Envío coordinado'));$whatsapp=preg_replace('/\D+/','',$tenant['whatsapp']?:$tenant['phone']);$isDemo=$tenant['slug']==='tienda-demo';json_response(['ok'=>true,'order'=>$number,'order_id'=>$orderId,'demo'=>$isDemo,'store'=>$tenant['name'],'preview'=>$isDemo?$message:null,'whatsapp'=>'https://wa.me/'.$whatsapp.'?text='.rawurlencode($message)]);
}

function blog_page(App $app,array $t):void{$posts=$app->all("SELECT p.*,u.name author FROM posts p JOIN users u ON u.id=p.author_id WHERE p.tenant_id=? AND p.status='published' ORDER BY COALESCE(p.published_at,p.created_at) DESC",[$t['id']]);layout_start('Blog',$t);public_header($t);echo '<main class="section section-soft"><div class="container"><div class="section-head"><div><span class="tag">NOVEDADES</span><h2>Blog</h2></div></div>';if(!$posts)echo '<div class="card empty">Pronto compartiremos novedades.</div>';foreach($posts as $p){echo '<article class="card post">';if($p['media_url']&&$p['media_type']==='image')echo '<img class="post-media" loading="lazy" src="'.e($p['media_url']).'" alt="">';if($p['media_url']&&in_array($p['media_type'],['video','link']))echo '<div class="post-body"><a class="btn btn-light" target="_blank" rel="noopener" href="'.e($p['media_url']).'">Ver contenido</a></div>';echo '<div class="post-body"><p>'.nl2br(e($p['body'])).'</p><small class="muted">'.e($p['author']).' · '.e(date('d/m/Y',strtotime($p['published_at']?:$p['created_at']))).'</small></div></article>';}echo '</div></main>';public_footer($t);layout_end();}

function global_blog_page(App $app):void{$posts=$app->all("SELECT p.*,u.name author FROM posts p JOIN users u ON u.id=p.author_id WHERE p.tenant_id IS NULL AND p.status='published' ORDER BY COALESCE(p.published_at,p.created_at) DESC");layout_start('Blog');public_header();echo '<main class="section section-soft"><div class="container"><div class="section-head"><div><span class="tag">FISITAPP</span><h2>Novedades</h2></div></div>';if(!$posts)echo '<div class="card empty">Pronto publicaremos novedades.</div>';foreach($posts as $p)echo '<article class="card post">'.($p['media_url']?'<img class="post-media" src="'.e($p['media_url']).'" alt="">':'').'<div class="post-body">'.nl2br(e($p['body'])).'<br><small class="muted">'.e($p['author']).'</small></div></article>';echo '</div></main>';public_footer();layout_end();}

function contact_page(App $app,array $t):void{if(is_post()){verify_csrf();if(!rate_limit_persistent($app,'contact',client_identity((string)$t['id']),5,600)){flash('error','Espera antes de enviar otro mensaje.');}else{$name=trim($_POST['name']??'');$msg=trim($_POST['message']??'');if($name&&$msg){$email=trim($_POST['email']??'');$subject=trim($_POST['subject']??'Contacto desde FISITAPP');$app->exec('INSERT INTO contacts(tenant_id,name,email,phone,subject,message) VALUES(?,?,?,?,?,?)',[$t['id'],$name,$email,trim($_POST['phone']??''),$subject,$msg]);if(filter_var($t['email'],FILTER_VALIDATE_EMAIL))send_mail_v1($app,$t['email'],'FISITAPP: '.str_replace(["\r","\n"],' ',$subject),"Nombre: $name\nCorreo: $email\nTeléfono: ".trim($_POST['phone']??'')."\n\n$msg",(int)$t['id']);flash('success','Mensaje recibido. Pronto te contactaremos.');}else flash('error','Completa los campos requeridos.');}redirect(url($t['slug'].'/contacto'));}layout_start('Contacto',$t);public_header($t);echo '<main class="section"><div class="container split"><section><span class="tag">CONTACTO</span><h1>Conversemos</h1><p class="muted">'.nl2br(e($t['address'])).'</p><p><strong>Teléfono:</strong> '.e($t['phone']).'<br><strong>Correo:</strong> '.e($t['email']).'</p>'.safe_map_embed($t['map_embed']).'</section><section class="card admin-card">';render_flashes();echo '<form method="post">'.csrf_field().'<div class="form-group"><label>Nombre *</label><input class="input" name="name" required maxlength="150"></div><div class="split"><div class="form-group"><label>Teléfono</label><input class="input" name="phone" maxlength="40"></div><div class="form-group"><label>Correo</label><input class="input" type="email" name="email"></div></div><div class="form-group"><label>Asunto</label><input class="input" name="subject" maxlength="190"></div><div class="form-group"><label>Mensaje *</label><textarea class="input" name="message" required maxlength="3000"></textarea></div><button class="btn btn-block">Enviar mensaje</button></form></section></div></main>';public_footer($t);layout_end();}

function safe_map_embed(?string $html):string{if(!$html)return '';if(!preg_match('/src=["\'](https:\/\/(?:www\.)?google\.com\/maps\/embed[^"\']*)["\']/i',$html,$m))return '';$src=e($m[1]);return '<div class="card" style="overflow:hidden"><iframe src="'.$src.'" width="100%" height="360" style="border:0" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>';}

function auth_page(App $app,string $mode,string $audience='customer'):void
{
    $active=current_user();if($active&&!is_post())redirect(role_home_url_v1($app,$active));$next=safe_next_url_v1($app,(string)($_GET['next']??$_POST['next']??''));$route=$mode==='register'?'register':($audience==='owner'?'owner-login':($audience==='master'?'master-login':'login'.($audience==='any'?'?audience=any':'')));
    if(is_post()){
        verify_csrf();$email=strtolower(trim((string)($_POST['email']??'')));if(!rate_limit_persistent($app,'auth',client_identity($email),8,300)){flash('error','Demasiados intentos. Espera cinco minutos.');redirect(url($route.($next?(str_contains($route,'?')?'&':'?').'next='.rawurlencode($next):'')));}$password=(string)($_POST['password']??'');
        if($mode==='register'){$name=trim((string)($_POST['name']??''));$phone=trim((string)($_POST['phone']??''));if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<10||!$phone)flash('error','Completa los datos y utiliza una contraseña de al menos 10 caracteres.');elseif($app->one('SELECT id FROM users WHERE email=?',[$email]))flash('error','Este correo ya está registrado.');else{$app->exec('INSERT INTO users(name,email,phone,password_hash,role) VALUES(?,?,?,?,?)',[$name,$email,$phone,password_hash($password,PASSWORD_DEFAULT),'customer']);$newUserId=(int)$app->db->lastInsertId();try{issue_email_verification_v1($app,$newUserId,$email);}catch(Throwable){}flash('success','Cuenta creada. Ahora inicia sesión.');redirect(url('login'.($next?'?next='.rawurlencode($next):'')));}}
        else{$user=$app->one('SELECT * FROM users WHERE email=? AND is_active=1',[$email]);$audienceOk=$user&&($audience==='any'||($audience==='customer'&&$user['role']==='customer')||($audience==='master'&&$user['role']==='master')||($audience==='owner'&&in_array($user['role'],['master','tenant_admin','manager','editor','kitchen','cashier','driver'],true)));if(!$audienceOk||!password_verify($password,(string)($user['password_hash']??''))){usleep(250000);flash('error',$audience==='owner'?'Acceso administrativo incorrecto.':($audience==='master'?'Acceso administrativo incorrecto.':'Correo o contraseña incorrectos.'));}else{session_regenerate_id(true);$_SESSION['user']=['id'=>$user['id'],'tenant_id'=>$user['tenant_id'],'name'=>$user['name'],'email'=>$user['email'],'phone'=>$user['phone'],'role'=>$user['role']];$app->exec('UPDATE users SET last_login_at=NOW() WHERE id=?',[$user['id']]);if(!empty($user['force_password_change']))redirect(url('change-password'));if($next&&$user['role']==='customer')redirect(url($next));redirect(role_home_url_v1($app,$user));}}
        redirect(url($route.($next?(str_contains($route,'?')?'&':'?').'next='.rawurlencode($next):'')));
    }
    $titles=['owner'=>'Acceso de negocios','master'=>'Acceso de negocios','customer'=>'Iniciar sesión','any'=>'Iniciar sesión'];$title=$mode==='register'?'Crear cuenta':$titles[$audience];$officialLogo=$app->setting('platform_logo',url('assets/fisitapp-logo.webp'));layout_start($title);echo '<main class="auth-page"><section class="card auth-card"><a class="brand auth-brand" href="'.url().'"><img src="'.e($officialLogo).'" alt="FISITAPP"></a><span class="auth-type">'.e($title).'</span><h1>'.($mode==='login'?'Bienvenido de nuevo':'Crea tu cuenta').'</h1><p class="muted">'.($audience==='owner'?'El sistema detectará automáticamente si tu cuenta es maestra, pertenece a un negocio o es de motorizado.':($audience==='master'?'El sistema detectará automáticamente tu panel.':'Compra en las tiendas de FISITAPP con una sola cuenta.')).'</p>';render_flashes();echo '<form method="post">'.csrf_field().'<input type="hidden" name="next" value="'.e($next??'').'">';if($mode==='register')echo '<div class="form-group"><label>Nombre</label><input class="input" name="name" required maxlength="150"></div><div class="form-group"><label>Teléfono</label><input class="input" name="phone" required maxlength="40"></div>';echo '<div class="form-group"><label>Correo</label><input class="input" type="email" name="email" required autocomplete="email"></div><div class="form-group"><label>Contraseña</label><input class="input" type="password" name="password" required minlength="'.($mode==='register'?'10':'1').'" autocomplete="'.($mode==='register'?'new-password':'current-password').'"></div><button class="btn btn-block">'.($mode==='login'?'Ingresar':'Crear cuenta').'</button></form>'.($mode==='login'?'<p class="muted auth-links"><a href="'.url('forgot-password').'">¿Olvidaste tu contraseña?</a></p>':'').($audience==='owner'?'<p class="muted auth-links">¿Trabajas haciendo entregas? <a href="'.url('driver-register').'">Crear perfil de motorizado</a></p>':'').($audience==='customer'?'<p class="muted auth-links">'.($mode==='login'?'¿No tienes cuenta? <a href="'.url('register'.($next?'?next='.rawurlencode($next):'')).'">Crear usuario</a>':'¿Ya tienes cuenta? <a href="'.url('login'.($next?'?next='.rawurlencode($next):'')).'">Iniciar sesión</a>').'</p>':'').'</section></main>';layout_end();
}

function change_password_page(App $app):void{$u=require_login();if(is_post()){verify_csrf();$p=(string)($_POST['password']??'');$confirm=(string)($_POST['confirm']??'');if(strlen($p)<12||$p!==$confirm)flash('error','Las contraseñas deben coincidir y tener al menos 12 caracteres.');else{$app->exec('UPDATE users SET password_hash=?,force_password_change=0 WHERE id=?',[password_hash($p,PASSWORD_DEFAULT),$u['id']]);flash('success','Contraseña actualizada.');redirect($u['role']==='master'?url('master'):($u['role']==='customer'?url('account'):($u['role']==='driver'?url('driver'):url('admin'))));}redirect(url('change-password'));}layout_start('Cambiar contraseña');echo '<main class="auth-page"><section class="card auth-card"><h1>Crea una contraseña nueva</h1><p class="muted">Este acceso era temporal. Define una contraseña privada antes de continuar.</p>';render_flashes();echo '<form method="post">'.csrf_field().'<div class="form-group"><label>Nueva contraseña</label><input class="input" type="password" name="password" minlength="12" required autocomplete="new-password"></div><div class="form-group"><label>Confirmar contraseña</label><input class="input" type="password" name="confirm" minlength="12" required autocomplete="new-password"></div><button class="btn btn-block">Guardar contraseña</button></form></section></main>';layout_end();}

function repeat_order_item_v5(App $app,array $item,int $tenantId):?array
{
    if(empty($item['product_id'])||($item['product_status']??'')!=='active')return null;$productId=(int)$item['product_id'];$stored=json_decode((string)($item['options_json']??''),true);$stored=is_array($stored)?$stored:[];$selectedIds=array_values(array_unique(array_map('intval',array_column($stored,'id'))));sort($selectedIds);
    $rows=$app->all('SELECT g.id group_id,g.name group_name,g.type,g.is_required,g.min_select,g.max_select,o.id option_id,o.name option_name,o.price_delta FROM product_option_groups g LEFT JOIN product_options o ON o.group_id=g.id AND o.is_active=1 WHERE g.product_id=? AND g.tenant_id=? AND g.is_active=1 ORDER BY g.sort_order,g.id,o.sort_order,o.id',[$productId,$tenantId]);$groups=[];$lookup=[];foreach($rows as $row){$gid=(int)$row['group_id'];if(!isset($groups[$gid]))$groups[$gid]=['type'=>$row['type'],'required'=>(bool)$row['is_required'],'min'=>(int)$row['min_select'],'max'=>(int)$row['max_select']];if($row['option_id']!==null)$lookup[(int)$row['option_id']]=['id'=>(int)$row['option_id'],'groupId'=>$gid,'group'=>$row['group_name'],'name'=>$row['option_name'],'delta'=>(float)$row['price_delta']];}
    $selected=[];$counts=[];$delta=0.0;foreach($selectedIds as $id){if(!isset($lookup[$id]))return null;$option=$lookup[$id];$selected[]=$option;$counts[$option['groupId']]=($counts[$option['groupId']]??0)+1;$delta+=$option['delta'];}foreach($groups as $gid=>$group){$count=$counts[$gid]??0;$min=$group['required']?max(1,$group['min']):$group['min'];$max=$group['type']==='single'?1:max(1,$group['max']);if($count<$min||$count>$max)return null;}
    $note=(string)($item['notes']??'');$price=(float)($item['current_sale_price']?:$item['current_price'])+$delta;$key=$productId.':'.implode(',',array_map(fn($option)=>(string)$option['id'],$selected)).':'.strtolower($note);return ['id'=>$productId,'name'=>$item['product_name'],'price'=>$price,'unit'=>$item['unit_label'],'min'=>(float)$item['min_qty'],'step'=>(float)$item['qty_step'],'options'=>$selected,'option_ids'=>$selectedIds,'note'=>$note,'key'=>$key,'qty'=>(float)$item['quantity']];
}

function customer_account_page(App $app):void
{
    $sessionUser=require_login(['customer']);$user=$app->one('SELECT id,name,email,phone FROM users WHERE id=? AND role="customer"',[$sessionUser['id']]);if(!$user){$_SESSION=[];redirect(url());}
    if(is_post()){
        verify_csrf();$name=trim((string)($_POST['name']??''));$phone=trim((string)($_POST['phone']??''));
        if($name===''||$phone==='')flash('error','Nombre y teléfono son obligatorios.');
        else{$app->exec('UPDATE users SET name=?,phone=? WHERE id=?',[$name,$phone,$user['id']]);$_SESSION['user']['name']=$name;$_SESSION['user']['phone']=$phone;flash('success','Datos actualizados.');}
        redirect(url('account'));
    }
    $orderId=(int)($_GET['order']??0);layout_start('Mi cuenta');public_header();echo '<main class="section section-soft"><div class="container account-layout"><aside class="card admin-card account-nav"><h2>Mi cuenta</h2><p>'.e($user['name']).'<br><small class="muted">'.e($user['email']).'</small></p><a class="btn btn-light btn-block" href="'.url('account').'">Mis pedidos</a><form method="post" action="'.url('logout').'" style="margin-top:10px">'.csrf_field().'<button class="btn btn-light btn-block">Cerrar sesión</button></form></aside><section>';
    render_flashes();
    if($orderId){
        $order=$app->one('SELECT o.*,t.name tenant_name,t.slug tenant_slug,t.catalog_label FROM orders o JOIN tenants t ON t.id=o.tenant_id WHERE o.id=? AND o.user_id=?',[$orderId,$user['id']]);
        if(!$order){echo '<div class="card empty">Pedido no encontrado.</div>';}
        else{
            $items=$app->all('SELECT oi.*,p.status product_status,p.price current_price,p.sale_price current_sale_price,p.min_qty,p.qty_step FROM order_items oi LEFT JOIN products p ON p.id=oi.product_id AND p.tenant_id=? WHERE oi.order_id=? ORDER BY oi.id',[$order['tenant_id'],$orderId]);$repeat=[];
            foreach($items as $item){$repeatItem=repeat_order_item_v5($app,$item,(int)$order['tenant_id']);if($repeatItem)$repeat[]=$repeatItem;}
            echo '<p><a class="btn btn-light" href="'.url('account').'">← Mis pedidos</a></p><article class="card admin-card"><div class="section-head"><div><span class="tag">'.e($order['status']).'</span><h1>Pedido #'.e($order['order_number']).'</h1><p class="muted">'.e($order['tenant_name']).' · '.e(date('d/m/Y H:i',strtotime($order['created_at']))).'</p></div><strong class="total">'.money((float)$order['total']).'</strong></div><div class="order-delivery-data"><p><strong>Entrega:</strong> '.e($order['delivery_type']).(!empty($order['scheduled_at'])?' · Programado '.e(date('d/m/Y H:i',strtotime($order['scheduled_at']))):'').'</p>'.(!empty($order['address'])?'<p><strong>Dirección:</strong> '.nl2br(e($order['address'])).(!empty($order['address_reference'])?'<br><strong>Referencia:</strong> '.nl2br(e($order['address_reference'])):'').'</p>':'').'</div><div class="table-wrap"><table class="table"><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Total</th></tr>';
            foreach($items as $item)echo '<tr><td>'.e($item['product_name']).order_item_details_html($item).'</td><td>'.e($item['quantity']).' '.e($item['unit_label']).'</td><td>'.money((float)$item['unit_price']).'</td><td>'.money((float)$item['line_subtotal']+(float)$item['line_tax']).'</td></tr>';
            echo '</table></div><div class="order-totals"><p>Subtotal <strong>'.money((float)$order['subtotal']).'</strong></p><p>IVA <strong>'.money((float)$order['tax_total']).'</strong></p><p>Descuento <strong>-'.money((float)$order['discount_total']).'</strong></p><p>Entrega <strong>'.money((float)$order['delivery_total']).'</strong></p></div>';
            if($repeat){$payload=json_encode(['tenant'=>$order['tenant_slug'],'catalog'=>url($order['tenant_slug'].'/'.catalog_segment($order)),'items'=>$repeat],JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE);echo '<button class="btn btn-accent" data-repeat-order=\''.e($payload).'\'>Repetir pedido</button>';}
            echo '</article>';
        }
    }else{
        $orders=$app->all('SELECT o.id,o.order_number,o.total,o.status,o.created_at,t.name tenant_name FROM orders o JOIN tenants t ON t.id=o.tenant_id WHERE o.user_id=? ORDER BY o.created_at DESC LIMIT 100',[$user['id']]);
        echo '<section class="card admin-card"><h1>Mis pedidos</h1><div class="table-wrap"><table class="table"><tr><th>Pedido</th><th>Negocio</th><th>Total</th><th>Estado</th><th>Fecha</th><th></th></tr>';foreach($orders as $order)echo '<tr><td>#'.e($order['order_number']).'</td><td>'.e($order['tenant_name']).'</td><td>'.money((float)$order['total']).'</td><td><span class="status">'.e($order['status']).'</span></td><td>'.e(date('d/m/Y',strtotime($order['created_at']))).'</td><td><a class="btn btn-light" href="?order='.(int)$order['id'].'">Ver detalle</a></td></tr>';if(!$orders)echo '<tr><td colspan="6">Todavía no tienes pedidos.</td></tr>';echo '</table></div></section><section class="card admin-card" style="margin-top:20px"><h2>Datos de mi cuenta</h2><form method="post">'.csrf_field().field('Nombre','name',$user['name'],true).field('Teléfono','phone',$user['phone'],true).field('Correo','email',$user['email'],false,'email').'<small class="muted">El correo de acceso no se modifica desde este formulario.</small><button class="btn" style="margin-top:14px">Guardar datos</button></form></section>';
    }
    echo '</section></div></main>';public_footer();layout_end();
}

function public_footer(array $t=null):void{global $app;$isStore=!empty($t['slug']);if($isStore)$t['official_logo']=$t['logo']??'';if(!$t&&isset($app))$t=['name'=>$app->setting('site_name','FISITAPP'),'official_logo'=>$app->setting('platform_logo',url('assets/fisitapp-logo.webp')),'phone'=>$app->setting('master_whatsapp','8676-1771'),'facebook_url'=>$app->setting('facebook_url'),'instagram_url'=>$app->setting('instagram_url'),'tiktok_url'=>$app->setting('tiktok_url'),'footer_text'=>$app->setting('footer_text','Una experiencia de compra rápida, clara y cercana.'),'footer_links_title'=>$app->setting('footer_links_title','Enlaces'),'footer_contact_title'=>$app->setting('footer_contact_title','Contacto'),'footer_credit'=>$app->setting('footer_credit','Creado por Fisital Multiservicios')];echo '<footer class="footer"><div class="container footer-grid"><div>'.(!empty($t['official_logo'])?'<div class="footer-logo-wrap"><img class="footer-logo" src="'.e($t['official_logo']).'" alt="'.e($t['name']??'FISITAAP').'"></div>':'<div class="brand" style="color:#fff">'.($isStore?'':'<span class="brand-mark">F</span>').e($t['name']??'FISITAPP').'</div>').'<p>'.e($t['footer_text']??'Una experiencia de compra rápida, clara y cercana.').'</p>'.(!empty($t['business_hours'])?'<p>'.nl2br(e($t['business_hours'])).'</p>':'').'</div><div><strong>'.e($t['footer_links_title']??'Enlaces').'</strong><p><a href="'.($isStore?url($t['slug']):url()).'">Inicio</a></p><p><a href="'.($isStore?url($t['slug'].'/blog'):url('blog')).'">Blog</a></p>'.($isStore?'<p><a class="footer-sales-link" href="'.url().'"><img src="'.e($app->setting('platform_logo',url('assets/fisitapp-logo.webp'))).'" alt="FISITAAP" style="width:110px;max-height:40px;object-fit:contain;display:block;margin-bottom:10px">¿Quieres vender en línea?</a></p>':'').'</div><div><strong>'.e($t['footer_contact_title']??'Contacto').'</strong><p>'.e($t['phone']??'8676-1771').'</p><div class="socials">';foreach(['facebook_url'=>'f','instagram_url'=>'◎','tiktok_url'=>'♪'] as $key=>$icon)if(!empty($t[$key]))echo '<a class="social" target="_blank" rel="noopener noreferrer" href="'.e($t[$key]).'">'.$icon.'</a>';echo '</div></div></div><div class="container footer-credit">'.e($t['footer_credit']??'Creado por Fisital Multiservicios').' · '.date('Y').'</div></footer>';}
function render_flashes():void{foreach(flashes() as [$type,$msg])echo '<div class="alert alert-'.e($type).'">'.e($msg).'</div>';}
function simple_error(string $title,string $text):void{layout_start($title);echo '<main class="auth-page"><section class="card auth-card"><h1>'.e($title).'</h1><p class="muted">'.e($text).'</p><a class="btn" href="'.url().'">Volver al inicio</a></section></main>';layout_end();}
