<?php
declare(strict_types=1);

function r2_floor_save(App $app,array $u,array $t,array $branch):void {
    verify_csrf();if(restructure_can_r1($app,$u,'mesas','configure')===false||!in_array($u['role'],['tenant_admin','manager'],true))throw new DomainException('No tienes permiso para configurar mesas.');
    $action=(string)($_POST['action']??'');$app->db->beginTransaction();try{
        if($action==='room'){
            $name=trim((string)($_POST['name']??''));if($name===''||mb_strlen($name)>120)throw new DomainException('Escribe el nombre del salón.');$rate=r2_number($_POST['service_rate']??0,0,30);$id=(int)($_POST['room_id']??0);
            if($id){if(!$app->one('SELECT id FROM fisitaap_r2_rooms WHERE id=? AND tenant_id=? AND branch_id=? FOR UPDATE',[$id,$t['id'],$branch['id']]))throw new DomainException('Salón no disponible.');$app->exec('UPDATE fisitaap_r2_rooms SET name=?,service_rate=? WHERE id=?',[$name,$rate,$id]);}
            else $app->exec('INSERT INTO fisitaap_r2_rooms(tenant_id,branch_id,name,service_rate) VALUES(?,?,?,?)',[$t['id'],$branch['id'],$name,$rate]);
        }elseif($action==='layout'){
            $room=(int)($_POST['room_id']??0);if(!$app->one('SELECT id FROM fisitaap_r2_rooms WHERE id=? AND tenant_id=? AND branch_id=? FOR UPDATE',[$room,$t['id'],$branch['id']]))throw new DomainException('Salón no disponible.');
            $layout=json_decode((string)($_POST['layout']??''),true,64,JSON_THROW_ON_ERROR);if(!is_array($layout)||count($layout)>300)throw new DomainException('Plano inválido.');
            foreach($layout as $row){$table=(int)($row['id']??0);if(!$app->one('SELECT id FROM restaurant_tables WHERE id=? AND tenant_id=? AND branch_id=? AND is_active=1',[$table,$t['id'],$branch['id']]))throw new DomainException('Mesa no disponible.');$x=(int)r2_number($row['x']??0,0,900);$y=(int)r2_number($row['y']??0,0,565);$shape=in_array($row['shape']??'',['square','round','bar'],true)?$row['shape']:'square';$app->exec('INSERT INTO fisitaap_r2_floor(table_id,room_id,x,y,shape) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE room_id=VALUES(room_id),x=VALUES(x),y=VALUES(y),shape=VALUES(shape)',[$table,$room,$x,$y,$shape]);}
        }elseif($action==='view'){$mode=($_POST['table_view']??'')==='graphic'?'graphic':'basic';r2_set($app,(int)$t['id'],'table_view',$mode);}
        else throw new DomainException('Acción no disponible.');
        audit($app,(int)$t['id'],(int)$u['id'],'r2_floor_config','branch',(int)$branch['id']);$app->db->commit();
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();throw $ex;}
}
function r2_floor(App $app,array $u,array $t,bool $editor=false):void {
    $branch=pos_access_148($app,$u,$t);if(($t['catalog_label']??'')!=='Menú')throw new DomainException('Las mesas requieren un negocio tipo Menú.');
    if(is_post()){try{r2_floor_save($app,$u,$t,$branch);flash('success','Plano guardado. Las cuentas abiertas conservan sus importes.');}catch(Throwable $ex){flash('error',$ex->getMessage());}r2_redirect('mesas');}
    $rooms=$app->all('SELECT * FROM fisitaap_r2_rooms WHERE tenant_id=? AND branch_id=? ORDER BY id',[$t['id'],$branch['id']]);$roomId=(int)($_GET['room']??($rooms[0]['id']??0));$room=null;foreach($rooms as $r)if((int)$r['id']===$roomId)$room=$r;
    $canConfigure=in_array($u['role'],['tenant_admin','manager'],true)&&restructure_can_r1($app,$u,'mesas','configure')!==false;
    $tables=$app->all('SELECT r.*,f.room_id,f.x,f.y,f.shape,(SELECT COUNT(*) FROM pos_tickets p WHERE p.table_id=r.id AND p.tenant_id=r.tenant_id AND p.status NOT IN ("paid","void")) open_count FROM restaurant_tables r LEFT JOIN fisitaap_r2_floor f ON f.table_id=r.id WHERE r.tenant_id=? AND r.branch_id=? AND r.is_active=1 ORDER BY r.id',[$t['id'],$branch['id']]);
    admin_shell_start('Salones y mesas',$u,$t,'mesas');echo '<div class="r2-row"><a class="btn btn-light" href="'.url('admin/ventas?basic=1').'">Mesas básicas</a><a class="btn btn-light" href="'.url('admin/ventas').'">Venta rápida / Express</a>';foreach($rooms as $r)echo '<a class="btn '.($r['id']==$roomId?'':'btn-light').'" href="?room='.(int)$r['id'].'">'.e($r['name']).'</a>';echo '</div><p>Verde: libre · Azul: ocupada. Selecciona una mesa para ver su cuenta.</p><section class="card admin-card">';
    if(!$room)echo '<p>Crea un salón y las mesas desde la vista básica para organizar el plano.</p>';
    else{
        echo '<h2>'.e($room['name']).'</h2><div class="r2-floor" data-floor="'.(int)$room['id'].'" data-can-edit="'.($canConfigure?'1':'0').'"><svg viewBox="0 0 1000 650" aria-label="Plano de mesas"><rect width="1000" height="650" rx="12" fill="#f5f1e9"/><path d="M20 20 H980 V630 H20 Z" fill="none" stroke="#aaa28e" stroke-width="8"/>';
        $placed=0;foreach($tables as $i=>$table){if($table['room_id']&&$table['room_id']!=$roomId)continue;$x=$table['x']??(35+($placed%7)*135);$y=$table['y']??(40+(int)floor($placed/7)*115);$shape=$table['shape']??($table['space_type']==='bar'?'bar':'square');$placed++;$busy=(int)$table['open_count']>0;
            echo '<g data-floor-table="'.(int)$table['id'].'" data-x="'.(int)$x.'" data-y="'.(int)$y.'" data-shape="'.e($shape).'" transform="translate('.(int)$x.' '.(int)$y.')"><a href="'.url('admin/ventas?table='.(int)$table['id']).'"><rect width="100" height="85" rx="'.($shape==='round'?42:12).'" fill="'.($busy?'#2f74ba':'#317752').'" stroke="white" stroke-width="4"/><text x="50" y="33" text-anchor="middle" fill="white" font-size="13">'.e($table['name']).'</text><text x="50" y="54" text-anchor="middle" fill="white" font-size="11">'.($busy?'Ocupada':'Libre').'</text><text x="50" y="73" text-anchor="middle" fill="white" font-size="11">'.(int)$table['capacity'].' personas</text></a></g>';
        }echo '</svg></div>';
        if($canConfigure)echo '<label><input type="checkbox" data-floor-edit> Mover mesas en el plano</label>'.r2_form('layout').pos_hidden_148('room_id',$roomId).'<input type="hidden" name="layout" data-floor-layout><button class="btn" data-save-floor>Guardar posiciones</button></form><p>Para trasladar una mesa a este salón: selecciona la mesa y su forma en la lista.</p><div class="r2-row"><select class="input" data-floor-assign><option value="0">Agregar mesa a este salón</option>'.implode('',array_map(fn($r)=>'<option value="'.(int)$r['id'].'" data-name="'.e($r['name']).'">'.e($r['name']).'</option>',$tables)).'</select><select class="input" data-floor-shape><option value="square">Cuadrada</option><option value="round">Redonda</option><option value="bar">Barra</option></select><button class="btn btn-light" type="button" data-floor-add>Agregar al plano</button></div>';
    }echo '</section>';
    if($canConfigure){echo '<section class="card admin-card" style="margin-top:20px"><h2>Crear o editar salón / sector</h2>'.r2_form('room').pos_hidden_148('room_id',$roomId).field('Nombre','name',$room['name']??'',true).field('Servicio % (solo en mesas con servicio activado)','service_rate',$room['service_rate']??0,true,'number','.01').'<button class="btn">Guardar salón</button></form>'.r2_form('room').field('Nombre de nuevo salón','name','',true).pos_hidden_148('service_rate',0).'<button class="btn btn-light">Crear salón sin servicio</button></form>'.r2_form('view').'<label>Vista predeterminada<select class="input" name="table_view"><option value="basic">Básica</option><option value="graphic" '.(r2_setting($app,(int)$t['id'],'table_view')==='graphic'?'selected':'').'>Gráfica</option></select></label><button class="btn btn-light">Guardar vista</button></form></section>';}
    admin_shell_end();
}
function r2_table_rate(App $app,int $table,bool $enabled):float {
    if(function_exists('r3_active')&&r3_active($app)){ $sector=r3_sector_rate($app,$table,$enabled);if($sector!==null)return $sector; }
    if(!$enabled)return 0;
    $room=$app->one('SELECT r.service_rate FROM fisitaap_r2_floor f JOIN fisitaap_r2_rooms r ON r.id=f.room_id WHERE f.table_id=?',[$table]);
    return $room?(float)$room['service_rate']:10;
}
function r2_ticket_move(App $app,array $u,array $t,array $branch,int $ticket):void {
    verify_csrf();$target=(int)($_POST['target_table']??0);$app->db->beginTransaction();try{
        $a=pos_ticket_get_148($app,$t,$branch,$ticket,true);if(in_array($a['status'],['paid','void'],true)||(int)$a['revision']!==(int)($_POST['revision']??-1))throw new DomainException('La cuenta cambió. Recarga antes de trasladar.');
        $dest=$app->one('SELECT id FROM restaurant_tables WHERE id=? AND tenant_id=? AND branch_id=? AND is_active=1 FOR UPDATE',[$target,$t['id'],$branch['id']]);if(!$dest)throw new DomainException('Selecciona una mesa de esta sucursal.');
        if(($_POST['action']??'')==='join_tables'){
            if(!$a['table_id'])throw new DomainException('Esta cuenta no pertenece a una mesa.');
            $rows=$app->all('SELECT id FROM pos_tickets WHERE table_id=? AND tenant_id=? AND branch_id=? AND status NOT IN ("paid","void") ORDER BY id FOR UPDATE',[$a['table_id'],$t['id'],$branch['id']]);
            foreach($rows as $row)$app->exec('UPDATE pos_tickets SET table_id=?,revision=revision+1 WHERE id=?',[$target,$row['id']]);
        }else $app->exec('UPDATE pos_tickets SET table_id=?,sale_type="table",revision=revision+1 WHERE id=?',[$target,$ticket]);
        if($a['table_id'])pos_table_state_148($app,(int)$t['id'],(int)$a['table_id']);pos_table_state_148($app,(int)$t['id'],$target);audit($app,(int)$t['id'],(int)$u['id'],'r2_move_account','pos_ticket',$ticket);$app->db->commit();flash('success','Cuenta trasladada. Los consumos y cargos mantienen su valor.');
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();flash('error',$ex->getMessage());}redirect(url('admin/ventas?screen=order&ticket='.$ticket));
}
function r2_quick_workspace(App $app,array $u,array $t,int $id):void {
    $branch=pos_access_148($app,$u,$t);$ticket=pos_ticket_get_148($app,$t,$branch,$id);if(is_post()){if(in_array($_POST['action']??'',['move_table','join_tables'],true))r2_ticket_move($app,$u,$t,$branch,$id);pos_edit_148($app,$t,$u,$branch,$id);}
    if(in_array($ticket['status'],['paid','void'],true)){pos_workspace_148($app,$u,$t,$id);return;}
    $items=pos_items_v141($app,$id);$products=r2_catalog_prices($app,$t,pos_catalog_products_v141($app,$t,$branch));$categories=$app->all('SELECT id,name FROM categories WHERE tenant_id=? AND is_active=1 ORDER BY sort_order,name',[$t['id']]);$url=url('admin/ventas?screen=order&ticket='.$id);$meta=csrf_field().pos_hidden_148('revision',$ticket['revision']);
    $shift=$app->one('SELECT * FROM pos_shifts WHERE tenant_id=? AND branch_id=? AND user_id=? AND status="open" ORDER BY id DESC LIMIT 1',[$t['id'],$branch['id'],$u['id']]);
    admin_shell_start('Venta rápida',$u,$t,'ventas');pos_assets_148();echo '<div class="r2-pos-heading"><strong>'.e($t['name']).'</strong><span>'.e($branch['name']).' · '.e($u['name']).'</span><a class="btn btn-light" href="'.url('admin/turnos').'">'.($shift?'Cerrar turno':'Abrir turno').'</a><a class="btn btn-light" href="'.url('admin/ventas?history=1').'">Historial / Reimprimir</a></div><div class="r2-row"><a class="btn btn-light" href="'.url('admin/ventas').'">Cuentas y ventas en espera</a><strong>'.e($ticket['ticket_number']).'</strong></div><div class="r2-pos-grid"><section class="card admin-card"><form method="get" class="r2-row">'.pos_hidden_148('screen','order').pos_hidden_148('ticket',$id).'<input class="input" name="q" value="'.e($_GET['q']??'').'" placeholder="Escanea un código o busca un producto…" data-pos-search><button class="btn">Buscar</button></form><div class="table-wrap"><table class="table r2-sale-lines"><tr><th>Código</th><th>Producto / detalle</th><th>Cantidad</th><th>Precio</th><th>Importe</th><th>Acciones</th></tr>';
    foreach($items as $i)echo '<tr><td>'.e($i['sku']).'</td><td><strong>'.e($i['product_name']).'</strong>'.order_item_details_html($i).'</td><td><form method="post">'.$meta.pos_hidden_148('action','quantity').pos_hidden_148('item_id',$i['id']).'<input class="input compact" type="number" step=".001" name="quantity" min="0" value="'.e($i['quantity']).'"><button class="btn btn-light" '.($i['kitchen_status']!=='pending'?'disabled':'').'>Actualizar</button></form></td><td>'.money((float)$i['unit_price']).'</td><td>'.money((float)$i['line_subtotal']+(float)$i['line_tax']).'</td><td><form method="post">'.$meta.pos_hidden_148('action','quantity').pos_hidden_148('item_id',$i['id']).pos_hidden_148('quantity',0).'<button class="btn btn-danger" '.($i['kitchen_status']!=='pending'?'disabled':'').'>Eliminar</button></form></td></tr>';
    if(!$items)echo '<tr><td colspan="6">Agrega productos desde la búsqueda o el acceso rápido.</td></tr>';echo '</table></div><div class="r2-row">';foreach(['save'=>'Guardar','suspend'=>'Guardar en espera','void'=>'Cancelar venta'] as $action=>$label)echo '<form method="post">'.$meta.pos_hidden_148('action',$action).'<button class="btn btn-light">'.$label.'</button></form>';echo '</div><details><summary>Descuento</summary><form method="post">'.$meta.pos_hidden_148('action','discount').field('Monto','discount',$ticket['discount_total'],true,'number','.01').'<button class="btn">Aplicar</button></form></details><details><summary>Cliente</summary><form method="post">'.$meta.pos_hidden_148('action','customer');pos_customers_ui_148($app,$t,(int)$ticket['customer_id']);echo '<button class="btn">Guardar cliente</button></form></details></section><aside class="card admin-card"><h3>Acceso rápido</h3><div class="chips">';foreach($categories as $c)echo '<a class="chip" href="'.e($url.'&category='.(int)$c['id']).'">'.e($c['name']).'</a>';echo '</div><div class="r2-quick-products">';
    foreach($products as $p)echo '<form class="pos-product r2-quick-product" method="post" action="'.e($url).'">'.$meta.pos_hidden_148('action','add_item').pos_hidden_148('product_id',$p['id']).pos_hidden_148('quantity',max(1,(float)$p['min_qty'])).'<img src="'.e(public_media_url($p['image'])).'" alt=""><div><strong>'.e($p['name']).'</strong><small>'.e($p['sku']).'</small><b>'.money((float)($p['sale_price']?:$p['price'])).'</b></div><button class="btn" aria-label="Agregar '.e($p['name']).'">+</button></form>';echo '</div></aside></div><section class="card admin-card r2-pos-total"><span>Subtotal <b>'.money((float)$ticket['subtotal']).'</b></span><span>Impuesto <b>'.money((float)$ticket['tax_total']).'</b></span><span>Descuento <b>'.money((float)$ticket['discount_total']).'</b></span><strong>Total '.money((float)$ticket['total']).'</strong><a class="btn btn-accent" href="'.url('admin/ventas?screen=checkout&ticket='.$id).'">Cobrar '.money(max(0,(float)$ticket['total']-(float)$ticket['paid_total'])).'</a></section>';admin_shell_end();
}
function r2_sales_history(App $app,array $u,array $t):void {
    [$from,$to]=valid_report_dates_v1();$branch=physical_branch_v14($app,$t);admin_shell_start('Historial de ventas',$u,$t,'ventas');echo '<section class="card admin-card"><form method="get">'.pos_hidden_148('history',1).'<div class="split">'.field('Desde','from',$from,true,'date').field('Hasta','to',$to,true,'date').'</div><button class="btn btn-light">Filtrar</button></form><table class="table"><tr><th>Fecha</th><th>Venta</th><th>Cliente</th><th>Pago</th><th>Total</th><th>Comprobante</th></tr>';foreach($app->all('SELECT * FROM sales WHERE tenant_id=? AND branch_id=? AND DATE(created_at) BETWEEN ? AND ? ORDER BY id DESC LIMIT 300',[$t['id'],$branch['id'],$from,$to]) as $s)echo '<tr><td>'.e($s['created_at']).'</td><td>'.e($s['sale_number']).'</td><td>'.e($s['customer_name']).'</td><td>'.e($s['payment_method']).'</td><td>'.money((float)$s['total']).'</td><td><a class="btn btn-light" href="'.url('admin/recibo?venta='.(int)$s['id']).'">Ver / reimprimir</a></td></tr>';echo '</table></section>';admin_shell_end();
}
