<?php
declare(strict_types=1);
function r2_shifts(App $app,array $u,array $t):void {
    $b=physical_branch_v14($app,$t);$manage=in_array($u['role'],['tenant_admin','manager'],true);
    if(is_post()){verify_csrf();try{$action=(string)($_POST['action']??'open');$app->db->beginTransaction();$app->one('SELECT id FROM branches WHERE id=? AND tenant_id=? FOR UPDATE',[$b['id'],$t['id']]);
        if($action==='open'){
            if($app->one('SELECT id FROM pos_shifts s WHERE tenant_id=? AND branch_id=? AND user_id=? AND status="open" AND NOT EXISTS(SELECT 1 FROM fisitaap_r2_shift_links l WHERE l.shift_id=s.id)',[$t['id'],$b['id'],$u['id']]))throw new DomainException('Ya tienes un turno web abierto en esta sucursal.');
            $app->exec('INSERT INTO pos_shifts(tenant_id,branch_id,user_id,name,opening_cash,status,opened_at) VALUES(?,?,?,?,?,"open",NOW())',[$t['id'],$b['id'],$u['id'],mb_substr(trim((string)($_POST['name']??'Turno')),0,120),r2_number($_POST['opening_cash']??0)]);
        }elseif($action==='close'){
            $id=(int)($_POST['id']??0);$s=$app->one('SELECT * FROM pos_shifts WHERE id=? AND tenant_id=? AND branch_id=? AND status="open" FOR UPDATE',[$id,$t['id'],$b['id']]);if(!$s||(!$manage&&(int)$s['user_id']!==(int)$u['id']))throw new DomainException('Turno no disponible para tu usuario.');if($app->one('SELECT shift_id FROM fisitaap_r2_shift_links WHERE shift_id=?',[$id]))throw new DomainException('Este turno se cierra desde su caja Windows.');
            $cash=(float)($app->one('SELECT COALESCE(SUM(pp.amount),0) total FROM pos_payments pp JOIN sales v ON v.id=pp.sale_id WHERE v.shift_id=? AND pp.payment_method="Efectivo" AND v.status="completed"',[$id])['total']??0);$expected=round((float)$s['opening_cash']+$cash,2);$closing=r2_number($_POST['closing_cash']??0);$app->exec('UPDATE pos_shifts SET closing_cash=?,expected_cash=?,difference_amount=?,notes=?,status="closed",closed_at=NOW() WHERE id=?',[$closing,$expected,round($closing-$expected,2),mb_substr(trim((string)($_POST['notes']??'')),0,1000),$id]);
        }else throw new DomainException('Operación desconocida.');$app->db->commit();flash('success','Turno actualizado.');
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();flash('error',$ex->getMessage());}redirect(url('admin/turnos'));}
    $from=(string)($_GET['from']??date('Y-m-01'));$to=(string)($_GET['to']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to))throw new DomainException('Fechas inválidas.');$who=$manage?(int)($_GET['user_id']??0):(int)$u['id'];
    $rows=$app->all('SELECT s.*,u.name user_name,l.shift_uuid FROM pos_shifts s JOIN users u ON u.id=s.user_id LEFT JOIN fisitaap_r2_shift_links l ON l.shift_id=s.id WHERE s.tenant_id=? AND s.branch_id=? AND s.opened_at>=? AND s.opened_at<DATE_ADD(?,INTERVAL 1 DAY) AND (?=0 OR s.user_id=?) ORDER BY s.opened_at DESC LIMIT 300',[$t['id'],$b['id'],$from,$to,$who,$who]);
    admin_shell_start('Turnos y finanzas de caja',$u,$t,'turnos');echo '<div class="split"><section class="card admin-card">'.r2_form('open').'<h2>Abrir turno · '.e($b['name']).'</h2>'.field('Nombre','name','Turno '.date('d/m H:i'),true).field('Fondo inicial','opening_cash',0,true,'number','.01').'<button class="btn">Abrir caja</button></form></section><section class="card admin-card"><form method="get"><h2>Filtrar turnos</h2>'.field('Desde','from',$from,true,'date').field('Hasta','to',$to,true,'date');if($manage)echo '<label>Usuario'.r2_select('user_id',array_merge([['id'=>0,'name'=>'Todos']],$app->all('SELECT id,name FROM users WHERE tenant_id=? ORDER BY name',[$t['id']])),$who).'</label>';echo '<button class="btn btn-light">Filtrar</button></form></section></div><section class="card admin-card" style="margin-top:20px"><div class="table-wrap"><table class="table"><tr><th>Usuario / turno</th><th>Apertura</th><th>Finanzas</th><th>Cierre</th><th></th></tr>';
    foreach($rows as $s){$totals=$app->one('SELECT COUNT(*) n,COALESCE(SUM(total),0) total FROM sales WHERE shift_id=? AND status="completed"',[$s['id']]);$payments=$app->all('SELECT p.payment_method,COALESCE(SUM(p.amount),0) amount FROM pos_payments p JOIN sales v ON v.id=p.sale_id WHERE v.shift_id=? AND v.status="completed" GROUP BY p.payment_method',[$s['id']]);echo '<tr><td>'.e($s['user_name'].' · '.$s['name']).'<br>'.($s['shift_uuid']?'Caja local':'Caja web').'</td><td>'.e($s['opened_at']).'<br>Fondo '.money((float)$s['opening_cash']).'</td><td>'.(int)$totals['n'].' ventas · '.money((float)$totals['total']);foreach($payments as $p)echo '<br>'.e($p['payment_method']).' '.money((float)$p['amount']);echo '</td><td>'.e($s['status']==='closed'?$s['closed_at']:'Abierto');if($s['status']==='closed')echo '<br>Contado '.money((float)$s['closing_cash']).'<br>Esperado '.money((float)$s['expected_cash']).'<br>Diferencia '.money((float)$s['difference_amount']).'<br>'.e($s['notes']);echo '</td><td>';if($s['status']==='open'&&!$s['shift_uuid']&&($manage||(int)$s['user_id']===(int)$u['id']))echo r2_form('close',(int)$s['id']).field('Efectivo contado','closing_cash','',true,'number','.01').field('Observación','notes','').'<button class="btn">Cerrar</button></form>';echo '</td></tr>';}echo '</table></div><button class="btn btn-light" type="button" onclick="window.print()">Imprimir</button></section>';admin_shell_end();
}
