<?php
declare(strict_types=1);

function r2_accounts(App $app,array $u,array $t,string $kind):void {
    $ar=$kind==='cxc';$table=$ar?'accounts_receivable':'accounts_payable';$payments=$ar?'ar_payments':'ap_payments';$fk=$ar?'receivable_id':'payable_id';
    if(is_post()){verify_csrf();try{
        $id=(int)($_POST['id']??0);$key=(string)($_POST['payment_key']??'');if(!preg_match('/^[a-f0-9]{32}$/',$key))throw new DomainException('Recarga el estado de cuenta.');$method=(string)($_POST['payment_method']??'');if(!in_array($method,['Efectivo','Tarjeta','SINPE Móvil','Transferencia'],true))throw new DomainException('Forma de pago inválida.');
        $app->db->beginTransaction();$a=$app->one('SELECT * FROM '.$table.' WHERE id=? AND tenant_id=? FOR UPDATE',[$id,$t['id']]);if(!$a)throw new DomainException('Cuenta no disponible.');
        if(!$app->one('SELECT id FROM '.$payments.' WHERE '.$fk.'=? AND payment_key=?',[$id,$key])){
            $amount=pos_cents_148(r2_number($_POST['amount']??0,.01));$balance=pos_cents_148($a['balance']);if($amount>$balance)throw new DomainException('El abono supera el saldo pendiente.');$balance-=$amount;
            $app->exec('INSERT INTO '.$payments.'('.$fk.',amount,payment_method,reference,notes,user_id,payment_key) VALUES(?,?,?,?,?,?,?)',[$id,$amount/100,$method,mb_substr(trim((string)($_POST['reference']??'')),0,150),mb_substr(trim((string)($_POST['notes']??'')),0,500),$u['id'],$key]);
            $app->exec('UPDATE '.$table.' SET balance=?,status=? WHERE id=? AND tenant_id=?',[$balance/100,$balance===0?'paid':'partial',$id,$t['id']]);
            if($ar&&$a['customer_id'])$app->exec('UPDATE customer_credit_profiles SET current_balance=GREATEST(0,current_balance-?) WHERE tenant_id=? AND user_id=?',[$amount/100,$t['id'],$a['customer_id']]);
            elseif(!$ar&&$a['purchase_id'])$app->exec('UPDATE purchases SET balance=?,payment_status=? WHERE id=? AND tenant_id=?',[$balance/100,$balance===0?'paid':'partial',$a['purchase_id'],$t['id']]);
            audit($app,(int)$t['id'],(int)$u['id'],'r2_account_payment',$kind,$id);
        }
        $app->db->commit();flash('success','Abono recibido. Un reintento no aplica el mismo pago dos veces.');
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();flash('error',$ex->getMessage());}redirect(url('admin/'.$kind.'?detail='.(int)($_POST['id']??0)));}
    $q=mb_substr(trim((string)($_GET['q']??'')),0,100);$filter=(string)($_GET['status']??'');$join=$ar?'LEFT JOIN users p ON p.id=a.customer_id':'JOIN suppliers p ON p.id=a.supplier_id';$name=$ar?'COALESCE(p.name,a.customer_name)':'p.name';
    $rows=$app->all('SELECT a.*,'.$name.' party FROM '.$table.' a '.$join.' WHERE a.tenant_id=? AND (a.document_number LIKE ? OR '.$name.' LIKE ?) AND (?="" OR a.status=?) ORDER BY a.due_date,a.id DESC LIMIT 400',[$t['id'],'%'.$q.'%','%'.$q.'%',$filter,$filter]);
    admin_shell_start($ar?'Cuentas por cobrar':'Cuentas por pagar',$u,$t,$kind);echo '<section class="card admin-card"><form method="get"><div class="split">'.field('Cliente, proveedor o documento','q',$q).'<label>Estado<select class="input" name="status"><option value="">Todos</option>';foreach(['pending'=>'Pendiente','partial'=>'Parcial','paid'=>'Pagado','overdue'=>'Vencido'] as $key=>$label)echo '<option value="'.$key.'" '.($filter===$key?'selected':'').'>'.$label.'</option>';echo '</select></label></div><button class="btn btn-light">Filtrar</button></form><h2>Saldo '.money(array_sum(array_map(fn($r)=>(float)$r['balance'],$rows))).'</h2><div class="table-wrap"><table class="table"><tr><th>Documento</th><th>'.($ar?'Cliente':'Proveedor').'</th><th>Vence</th><th>Total</th><th>Saldo</th><th>Estado</th><th></th></tr>';
    foreach($rows as $r)echo '<tr><td>'.e($r['document_number']).'</td><td>'.e($r['party']).'</td><td>'.e($r['due_date']).'</td><td>'.money((float)$r['amount']).'</td><td>'.money((float)$r['balance']).'</td><td>'.e((float)$r['balance']>0&&$r['due_date']<date('Y-m-d')?'Vencido':(['pending'=>'Pendiente','partial'=>'Parcial','paid'=>'Pagado'][$r['status']]??$r['status'])).'</td><td><a class="btn btn-light" href="?detail='.(int)$r['id'].'">Estado de cuenta / abonar</a></td></tr>';echo '</table></div></section>';
    $detail=(int)($_GET['detail']??0);$a=$app->one('SELECT * FROM '.$table.' WHERE id=? AND tenant_id=?',[$detail,$t['id']]);if($a){echo '<section class="card admin-card" style="margin-top:20px"><h2>Estado de cuenta · '.e($a['document_number']).'</h2><table class="table"><tr><th>Fecha</th><th>Pago</th><th>Referencia</th><th>Importe</th></tr>';foreach($app->all('SELECT * FROM '.$payments.' WHERE '.$fk.'=? ORDER BY id',[$detail]) as $p)echo '<tr><td>'.e($p['created_at']).'</td><td>'.e($p['payment_method']).'</td><td>'.e($p['reference']).'</td><td>'.money((float)$p['amount']).'</td></tr>';echo '</table>';if((float)$a['balance']>0)echo r2_form('pay',$detail).pos_hidden_148('payment_key',bin2hex(random_bytes(16))).field('Abono','amount','',true,'number','.01').'<label>Pago<select class="input" name="payment_method"><option>Efectivo</option><option>Tarjeta</option><option>SINPE Móvil</option><option>Transferencia</option></select></label>'.field('Referencia','reference','').field('Notas','notes','').'<button class="btn">Aplicar abono</button></form>';echo '<button class="btn btn-light" type="button" onclick="window.print()">Imprimir estado de cuenta</button></section>';}
    admin_shell_end();
}
