<?php
declare(strict_types=1);
// Promotional gift cards: a fixed discount for one purchase, assigned to one customer.
function r2_gift_issue(App $app,array $u,array $t):never {
    if(function_exists('r3_active')&&r3_active($app))r3_gift_issue($app,$u,$t);
    verify_csrf();try{$cid=(int)($_POST['customer_id']??0);$amount=r2_number($_POST['gift_amount']??0,.01);$date=(string)($_POST['gift_expires']??'');$key=(string)($_POST['issue_key']??'');if(!preg_match('/^[a-f0-9]{32}$/',$key)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||!strtotime($date)||date('Y-m-d',strtotime($date))!==$date||$date<date('Y-m-d'))throw new DomainException('Revisa la fecha de vencimiento y recarga el formulario.');
        if(!$app->one('SELECT user_id FROM tenant_customers WHERE tenant_id=? AND user_id=?',[$t['id'],$cid]))throw new DomainException('Selecciona un cliente de tu negocio.');
        $app->db->beginTransaction();$app->one('SELECT id FROM tenants WHERE id=? FOR UPDATE',[$t['id']]);if(!$app->one('SELECT reward_id FROM fisitaap_r2_gift_keys WHERE tenant_id=? AND issue_key=?',[$t['id'],$key])){
            $program=$app->one('SELECT id FROM loyalty_programs WHERE tenant_id=? AND name="Tarjetas de regalo" AND is_active=0 ORDER BY id LIMIT 1',[$t['id']]);if(!$program){$app->exec('INSERT INTO loyalty_programs(tenant_id,name,mode,earn_value,goal_value,reward_type,reward_value,is_active) VALUES(?,"Tarjetas de regalo","points",1,999999,"fixed",0,0)',[$t['id']]);$program=['id'=>(int)$app->db->lastInsertId()];}
            $app->exec('INSERT INTO loyalty_accounts(tenant_id,user_id) VALUES(?,?) ON DUPLICATE KEY UPDATE updated_at=NOW()',[$t['id'],$cid]);$a=$app->one('SELECT id FROM loyalty_accounts WHERE tenant_id=? AND user_id=? FOR UPDATE',[$t['id'],$cid]);$code='FIEL-'.strtoupper(bin2hex(random_bytes(5)));$app->exec('INSERT INTO loyalty_rewards(account_id,program_id,code,reward_type,reward_value,status,expires_at) VALUES(?,?,?,"fixed",?,"available",?)',[$a['id'],$program['id'],$code,$amount,$date.' 23:59:59']);$reward=(int)$app->db->lastInsertId();$app->exec('INSERT INTO fisitaap_r2_gift_keys(tenant_id,issue_key,reward_id) VALUES(?,?,?)',[$t['id'],$key,$reward]);$app->exec('UPDATE loyalty_accounts SET rewards_available=rewards_available+1 WHERE id=?',[$a['id']]);$app->exec('INSERT INTO loyalty_ledger(account_id,event,description) VALUES(?,"adjust",?)',[$a['id'],'Tarjeta de regalo '.$code.' · '.money($amount).' · un uso']);audit($app,(int)$t['id'],(int)$u['id'],'r2_gift_issue','loyalty_reward',$reward);
        }$app->db->commit();flash('success','Tarjeta de regalo creada. El cliente la verá en su cuenta; puede usar su código en un pedido web o presentarla para el canje en tienda.');
    }catch(Throwable $ex){if($app->db->inTransaction())$app->db->rollBack();flash('error',$ex->getMessage());}redirect(url('admin/fidelizacion'));
}
function r2_gift_form(App $app,array $t):void {
    if(function_exists('r3_active')&&r3_active($app)){r3_gift_form($app,$t);return;}
    $customers=$app->all('SELECT u.id,u.name FROM tenant_customers c JOIN users u ON u.id=c.user_id WHERE c.tenant_id=? AND u.role="customer" AND u.is_active=1 ORDER BY u.name',[$t['id']]);echo '<section class="card admin-card" style="margin-bottom:20px"><h2>Tarjeta de regalo promocional</h2><p>Un descuento fijo para una sola compra, asignado al cliente. Si compra menos que el valor de la tarjeta, no queda saldo para otro pedido. No es una tarjeta de dinero recargable.</p>'.r2_form('gift_card').pos_hidden_148('issue_key',bin2hex(random_bytes(16))).'<div class="split"><label>Cliente'.r2_select('customer_id',$customers,0,'name',true).'</label>'.field('Valor de regalo','gift_amount','',true,'number','.01').field('Vence','gift_expires',date('Y-m-d',strtotime('+1 year')),true,'date').'</div><button class="btn">Crear tarjeta de regalo</button></form></section>';
}

function r2_loyalty_sale(App $app,int $id):void {
    $sale=$app->one('SELECT s.*,u.email FROM sales s JOIN users u ON u.id=s.customer_id WHERE s.id=? AND s.status="completed"',[$id]);if(!$sale||(str_starts_with($sale['email'],'final-')&&str_ends_with($sale['email'],'@registro.fisitaap.local')))return;$t=$app->one('SELECT * FROM tenants WHERE id=?',[$sale['tenant_id']]);if(!$t||!module_enabled_v12($app,$t,'loyalty'))return;$p=$app->one('SELECT * FROM loyalty_programs WHERE tenant_id=? AND is_active=1 AND (branch_id=? OR branch_id IS NULL) ORDER BY branch_id DESC,id LIMIT 1',[$t['id'],$sale['branch_id']]);if(!$p)return;
    $own=!$app->db->inTransaction();if($own)$app->db->beginTransaction();try{
        $app->one('SELECT id FROM sales WHERE id=? FOR UPDATE',[$id]);if($app->one('SELECT id FROM loyalty_ledger WHERE sale_id=? AND event="earn"',[$id])){if($own)$app->db->commit();return;}
        $app->exec('INSERT INTO loyalty_accounts(tenant_id,user_id) VALUES(?,?) ON DUPLICATE KEY UPDATE updated_at=NOW()',[$t['id'],$sale['customer_id']]);$a=$app->one('SELECT * FROM loyalty_accounts WHERE tenant_id=? AND user_id=? FOR UPDATE',[$t['id'],$sale['customer_id']]);$points=$p['mode']==='points'?floor((float)$sale['total']/max(.01,(float)$p['earn_value'])):0;$purchases=$p['mode']==='purchases'?1:0;$spend=$p['mode']==='spend'?(float)$sale['total']:0;
        $app->exec('UPDATE loyalty_accounts SET points_balance=points_balance+?,purchases_balance=purchases_balance+?,spend_balance=spend_balance+? WHERE id=?',[$points,$purchases,$spend,$a['id']]);$app->exec('INSERT INTO loyalty_ledger(account_id,sale_id,event,points_delta,purchases_delta,spend_delta,description) VALUES(?,?,"earn",?,?,?,?)',[$a['id'],$id,$points,$purchases,$spend,'Venta '.$sale['sale_number'].' completada']);$a=$app->one('SELECT * FROM loyalty_accounts WHERE id=?',[$a['id']]);$field=['points'=>'points_balance','purchases'=>'purchases_balance','spend'=>'spend_balance'][$p['mode']];$goal=max(1,(float)$p['goal_value']);if((float)$a[$field]>=$goal){$code='FIEL-'.strtoupper(bin2hex(random_bytes(5)));$app->exec('INSERT INTO loyalty_rewards(account_id,program_id,code,reward_type,reward_value,reward_product_id,status,expires_at) VALUES(?,?,?,?,?,?,"available",DATE_ADD(NOW(),INTERVAL 90 DAY))',[$a['id'],$p['id'],$code,$p['reward_type'],$p['reward_value'],$p['reward_product_id']]);$app->exec('UPDATE loyalty_accounts SET '.$field.'='.$field.'-?,rewards_available=rewards_available+1 WHERE id=?',[$goal,$a['id']]);}if($own)$app->db->commit();
    }catch(Throwable $ex){if($own&&$app->db->inTransaction())$app->db->rollBack();throw $ex;}
}
function r2_final_customer(App $app,int $tenant):array {
    $email='final-'.$tenant.'@registro.fisitaap.local';$existing=$app->one('SELECT id,name,phone FROM users WHERE email=? AND role="customer"',[$email]);if($existing){$app->exec('INSERT IGNORE INTO tenant_customers(tenant_id,user_id) VALUES(?,?)',[$tenant,$existing['id']]);return $existing;}$app->exec('INSERT INTO users(name,email,phone,password_hash,role,is_active) VALUES("Consumidor final",?,"",?,"customer",1) ON DUPLICATE KEY UPDATE id=id',[$email,password_hash(bin2hex(random_bytes(32)),PASSWORD_BCRYPT)]);$u=$app->one('SELECT id,name,phone FROM users WHERE email=? AND role="customer"',[$email]);if(!$u)throw new DomainException('Consumidor final no disponible.');$app->exec('INSERT IGNORE INTO tenant_customers(tenant_id,user_id) VALUES(?,?)',[$tenant,$u['id']]);return $u;
}
